AWSTemplateFormatVersion: "2010-09-09"
Description: SES - Configuration Set

Parameters:

  Application:
    Type: String
    Default: myapp
    Description: Application Name

  Environment:
    Type: String
    Default: stg
    Description: Environment

  ConfigSetName:
    Type: String
    Default: default-config
    Description: Config Set Name

Resources:

  ConfigSet:
    Type: 'AWS::SES::ConfigurationSet'
    Properties:
      Name: !Sub "${Application}-${Environment}-${ConfigSetName}"

Outputs:

  ConfigSetArn:
    Description: ConfigSet
    Value: !Ref ConfigSet
