AWSTemplateFormatVersion: "2010-09-09"
Description: SES - Configuration Set

Parameters:

  Application:
    Type: String
    Default: myapp
    Description: Application Name

  Environment:
    Type: String
    Default: stg
    Description: Environment

  VerifiedIdentityName:
    Type: String
    Default: xxx@yyy.com
    Description: "email address to verify"

Resources:

  VerifiedIdentity:
    Type: AWS::SES::EmailIdentity
    Properties:
      EmailIdentity: !Ref VerifiedIdentityName
      #ConfigurationSetAttributes:
      #  ConfigurationSetName: xxx
      #DkimAttributes:
      #  SigningEnabled: true
      #DkimSigningAttributes:
      #  NextSigningKeyLength: RSA_2048_BIT # RSA_1024_BIT | RSA_2048_BIT
      #FeedbackAttributes:
      #  EmailForwardingEnabled: false
      #MailFromAttributes:
        #BehaviorOnMxFailure: REJECT_MESSAGE # USE_DEFAULT_VALUE | REJECT_MESSAGE
        #MailFromDomain: xxx
Outputs:

  VerifiedIdentityDkimTokenName1:
    Value: !GetAtt VerifiedIdentity.DkimDNSTokenName1

  VerifiedIdentityDkimTokenName2:
    Value: !GetAtt VerifiedIdentity.DkimDNSTokenName2

  VerifiedIdentityDkimTokenName3:
    Value: !GetAtt VerifiedIdentity.DkimDNSTokenName3

  VerifiedIdentityDkimTokenValue1:
    Value: !GetAtt VerifiedIdentity.DkimDNSTokenValue1

  VerifiedIdentityDkimTokenValue2:
    Value: !GetAtt VerifiedIdentity.DkimDNSTokenValue2

  VerifiedIdentityDkimTokenValue3:
    Value: !GetAtt VerifiedIdentity.DkimDNSTokenValue3
