AWSTemplateFormatVersion: "2010-09-09"
Description: "Dynamo DB"

Resources:

  DynamoTable: 
    Type: AWS::DynamoDB::Table
    Properties: 
      TableName: "Character2"
      AttributeDefinitions: 
        - 
          AttributeName: "Region"
          AttributeType: "S"
        - 
          AttributeName: "CharacterName"
          AttributeType: "S"
        - 
          AttributeName: "Race"
          AttributeType: "S"
      KeySchema: 
        - 
          AttributeName: "Region"
          KeyType: "HASH"
        - 
          AttributeName: "CharacterName"
          KeyType: "RANGE"
      ProvisionedThroughput: 
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      LocalSecondaryIndexes: 
        - 
          IndexName: "region-race"
          KeySchema: 
            - 
              AttributeName: "Region"
              KeyType: "HASH"
            - 
              AttributeName: "Race"
              KeyType: "RANGE"
          Projection: 
            NonKeyAttributes: 
              - "CharacterName"
            ProjectionType: "INCLUDE"

Outputs:

  DynamoTableArn:
    Description: Dynamo Database Arn
    Value: !GetAtt DynamoTable.Arn
