AWSTemplateFormatVersion: "2010-09-09"
Description: "API Gateway - REST - Integrate with Lambda Function"

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: "Api Configuration"
        Parameters:
          - ApiGatewayName
          - ResourceName
      -
        Label:
          default: "Api Key & Usage Plan Configuration"
        Parameters:
          - UsagePlanName
          - ApiKeyName

Parameters:

  ApiGatewayName:
    Type: "String"
    Default: "rest-proxy-lambda"
    Description: "HTTP Api Gateway Name"

  ResourceName:
    Description: Resource Name
    Type: String
    Default: "demo"

  UsagePlanName:
    Description: Usage Plan Name
    Type: String
    Default: "rest-proxy-lambda-usage-plan"

  ApiKeyName:
    Description: Api Key Name
    Type: String
    Default: "rest-proxy-lambda-api-key"
    
Resources:

# Lambda Resources

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      #RoleName: "basic-lambda-js-role"
      Description: "Lambda Service Role - REST"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
              - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AWSXrayWriteOnlyAccess
      Tags:
        - Key: "Name"
          Value: "lambda-service-role"
          
  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      #FunctionName : "basic-lambda-js"
      Description: "Basic Lambda"
      Runtime: nodejs16.x
      Role: !GetAtt LambdaExecutionRole.Arn
      Handler: index.handler
      Environment:
        Variables:
          DatabaseName: lambdadb
          DatabaseUser: admin
      EphemeralStorage: # The size of the functionfs /tmp directory in MB
        Size: 512
      MemorySize: 128 #Maximum: 10240
      Timeout: 3 #The default is 3 seconds. The maximum allowed value is 900 seconds.
      #ReservedConcurrentExecutions: 0
      Code:
        ZipFile: |
          exports.handler = async (event, context) => {
              const name = event.pathParameters?.name || "stranger";
              const message = {
                  name: `Greetings ${name}`,
                  timestamp: Date.now()
              };
              const response = {
                  statusCode: 200,
                  headers: {
                    "Access-Control-Allow-Origin": "*"
                  },
                  body: JSON.stringify(message),
              };
              return response;
          };
      TracingConfig:
        Mode: "Active"
      Tags:
        - Key: "name"
          Value: "lambda-basic"

  LambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${LambdaFunction}"
      RetentionInDays: 1

# API

  ApiGatewayRestApi:
    Type: "AWS::ApiGateway::RestApi"
    Properties:
      Name: !Sub "${ApiGatewayName}"
      Description: !Sub "REST API ${ApiGatewayName}"
      DisableExecuteApiEndpoint: false
      Tags:
        - Key: "Environment"
          Value: "dev"

  ApiGatewayDeployment:
    Type: "AWS::ApiGateway::Deployment"
    DependsOn: ApiGatewayMethod
    Properties:
      RestApiId: !Ref ApiGatewayRestApi

  ApiGatewayStage:
    Type: "AWS::ApiGateway::Stage"
    Properties:
      StageName: "stg"
      Description: "Staging"
      RestApiId: !Ref ApiGatewayRestApi
      DeploymentId: !Ref ApiGatewayDeployment
      CacheClusterEnabled: true
      CacheClusterSize: 0.5
      MethodSettings:
        - HttpMethod: "GET"
          ResourcePath: "/"
          CachingEnabled: true
          CacheTtlInSeconds: 600
          LoggingLevel: ERROR
          DataTraceEnabled: false
          MetricsEnabled: false
        - ResourcePath: "/*"
          HttpMethod: "*"
          LoggingLevel: ERROR
          DataTraceEnabled: false
          MetricsEnabled: false
      TracingEnabled: true
      AccessLogSetting:
        DestinationArn: !GetAtt ApiLogGroup.Arn
        Format: $context.identity.sourceIp,$context.identity.caller,$context.identity.user,$context.requestTime,$context.httpMethod,$context.resourcePath,$context.protocol,$context.status,$context.responseLength,$context.requestId
      Variables:
        VariableX: variable-x

  ApiGatewayResource:
    Type: "AWS::ApiGateway::Resource"
    Properties:
      RestApiId: !Ref ApiGatewayRestApi
      ParentId: !GetAtt ApiGatewayRestApi.RootResourceId
      PathPart: !Ref ResourceName

  ApiGatewayResourceRootName:
    Type: "AWS::ApiGateway::Resource"
    Properties:
      RestApiId: !Ref ApiGatewayRestApi
      ParentId: !GetAtt ApiGatewayResource.ResourceId
      PathPart: "{name}"

  ApiGatewayMethod:
    Type: "AWS::ApiGateway::Method"
    Properties:
      RestApiId: !Ref ApiGatewayRestApi
      ResourceId: !Ref ApiGatewayResource
      ApiKeyRequired: True
      HttpMethod: "GET"
      AuthorizationType: "NONE"
      Integration:
        Type: "AWS_PROXY"
        Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${LambdaFunction}/invocations"
        IntegrationHttpMethod: "POST"
        #IntegrationResponses:
        #  - StatusCode: 200
        PassthroughBehavior: WHEN_NO_MATCH
      MethodResponses:
          - StatusCode: 200
            ResponseModels:
              application/json: Empty

  ApiGatewayMethodRootNameGet:
    Type: "AWS::ApiGateway::Method"
    Properties:
      RestApiId: !Ref ApiGatewayRestApi
      ResourceId: !Ref ApiGatewayResourceRootName
      ApiKeyRequired: True
      HttpMethod: "GET"
      AuthorizationType: "NONE"
      Integration:
        Type: "AWS_PROXY"
        Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${LambdaFunction}/invocations"
        IntegrationHttpMethod: "POST"
        #IntegrationResponses:
        #  - StatusCode: 200
        PassthroughBehavior: WHEN_NO_MATCH
      MethodResponses:
          - StatusCode: 200
            ResponseModels:
              application/json: Empty

  ApiGatewayKey:
    Type: "AWS::ApiGateway::ApiKey"
    DependsOn: ApiGatewayDeployment
    Properties:
      Name: !Sub "${ApiKeyName}"
      Enabled: True
      StageKeys:
        - RestApiId: !Ref ApiGatewayRestApi
          StageName: !Ref ApiGatewayStage

  ApiGatewayUsagePlan:
    Type: "AWS::ApiGateway::UsagePlan"
    Properties:
      UsagePlanName: !Sub "${UsagePlanName}"
      ApiStages:
        - ApiId: !Ref ApiGatewayRestApi
          Stage: !Ref ApiGatewayStage
      Quota:
        Limit: 100
        Period: DAY
      Throttle:
        BurstLimit: 10
        RateLimit: 2

  ApiGatewayUsagePlanKey:
    Type: AWS::ApiGateway::UsagePlanKey
    Properties: 
      KeyId: !Ref ApiGatewayKey
      KeyType: "API_KEY"
      UsagePlanId: !Ref ApiGatewayUsagePlan

  ApiInvokeLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${LambdaFunction}"
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      #SourceAccount: !Ref 'AWS::AccountId'  /stg/POST/
      SourceArn: !Sub arn:${AWS::Partition}:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiGatewayRestApi}/*/GET/${ResourceName}

  ApiInvokeLambdaPermissionRootName:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${LambdaFunction}"
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      #SourceAccount: !Ref 'AWS::AccountId'  /stg/POST/
      SourceArn: !Sub arn:${AWS::Partition}:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiGatewayRestApi}/*/GET/${ResourceName}/*
      
  ApiLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "${ApiGatewayRestApi}-access-logs"
      RetentionInDays: 1
      Tags:
        - Key: Environment
          Value: dev
        - Key: Application
          Value: app

Outputs:

  InvokeURL:
    Value: !Sub https://${ApiGatewayRestApi}.execute-api.${AWS::Region}.amazonaws.com/stg/${ResourceName}

#  ApiGatewayRestApiEndpoint:
#    Value: !GetAtt ApiGatewayRestApi.ApiEndpoint
