AWSTemplateFormatVersion: "2010-09-09"
Description: "API Gateway - HTTP - Quick Integrate with Existing Lambda Function"

Parameters:

  LambdaFunctionName:
    Description: Lambda Function Name
    Type: String
    Default: "my-lambda"

  HttpApiLambdaFunctionRouteKeyPath:
    Description: HTTP API Route Key of the Lambda Function Name
    Type: String
    Default: "ping"
    
Conditions:
  IsRouteKeySet: !Not [ !Equals [ !Ref HttpApiLambdaFunctionRouteKeyPath, ""] ]

Resources:

  HttpApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: http-lambda-proxy-quick
      Description: Lambda Proxy using Quick Create
      ProtocolType: HTTP
      Target: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${LambdaFunctionName}
      RouteKey: !If [IsRouteKeySet, !Sub "GET /${HttpApiLambdaFunctionRouteKeyPath}", AWS::NoValue]  #"GET /ping" # If you don't specify a routeKey, a default route of $default is created
      Version: 1
      Tags:
        "Name": "http-lambda-proxy-quick"

  HttpApiInvokeLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${LambdaFunctionName}"
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !If [IsRouteKeySet, !Sub "arn:${AWS::Partition}:execute-api:${AWS::Region}:${AWS::AccountId}:${HttpApi}/*/*/${HttpApiLambdaFunctionRouteKeyPath}", !Sub "arn:${AWS::Partition}:execute-api:${AWS::Region}:${AWS::AccountId}:${HttpApi}/*/$default"] 

Outputs:

  InvokeURL:
    Value: !Sub https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com

  HttpApiEndpoint:
    Value: !GetAtt HttpApi.ApiEndpoint

  HttpApiSourceArn:
    Value: !If [IsRouteKeySet, !Sub "arn:${AWS::Partition}:execute-api:${AWS::Region}:${AWS::AccountId}:${HttpApi}/*/*/${HttpApiLambdaFunctionRouteKeyPath}", !Sub "arn:${AWS::Partition}:execute-api:${AWS::Region}:${AWS::AccountId}:${HttpApi}/*/$default"] 