AWSTemplateFormatVersion: "2010-09-09"
Description: "API Gateway - HTTP - Integrate with Existing Lambda Function - Multi Stage"

Parameters:

  LambdaFunctionName:
    Description: Lambda Function Name
    Type: String
    Default: "my-lambda"

Resources:

  HttpApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: demo-lambda-proxy
      Description: Lambda Proxy / Uses resource-based permissions
      ProtocolType: HTTP

  Integration:
    Type: 'AWS::ApiGatewayV2::Integration'
    Properties:
      ApiId: !Ref HttpApi
      Description: Lambda Integration
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${LambdaFunctionName}/invocations
      IntegrationMethod: POST
      PayloadFormatVersion: '2.0'

  RouteGetDemo:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: 'GET /demo'
      Target: !Join
        - /
        - - integrations
          - !Ref Integration

  StageStaging:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref HttpApi
      StageName: 'stg'
      Description: Stage - Staging
      AutoDeploy: true
      StageVariables:
         FunctionName: my-function-name
      DefaultRouteSettings:
        #DetailedMetricsEnabled: true
        #LoggingLevel: INFO
        #DataTraceEnabled: false
        ThrottlingBurstLimit: 2
        ThrottlingRateLimit: 2

  StageProduction:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref HttpApi
      StageName: 'prd'
      Description: Stage - Production
      AutoDeploy: true

  InvokeLambdaPermissionStaging:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${LambdaFunctionName}"
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:${AWS::Partition}:execute-api:${AWS::Region}:${AWS::AccountId}:${HttpApi}/${StageStaging}/GET/*

  InvokeLambdaPermissionProduction:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${LambdaFunctionName}"
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:${AWS::Partition}:execute-api:${AWS::Region}:${AWS::AccountId}:${HttpApi}/${StageProduction}/GET/*

Outputs:
  InvokeURL:
    Value: !Sub https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com

