AWSTemplateFormatVersion: "2010-09-09"
Description: "API Gateway - WebSocket - Lambda - API"

Parameters:

  LambdaOnConnectFunctionName:
    Type: String
    Default: onconnect
    Description: Name of the lambda function handler for OnConnect

  LambdaOnDisconnectFunctionName:
    Type: String
    Default: ondisconnect
    Description: Name of the lambda function handler for OnDisconnect

  LambdaOnMessageFunctionName:
    Type: String
    Default: onmessage
    Description: Name of the lambda function handler for OnMessage

  LambdaOnCustomListFunctionName:
    Type: String
    Default: onmessage
    Description: Name of the lambda function handler for OnCustomList

Resources:

  WebSocketApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: WebSocketApi
      ProtocolType: WEBSOCKET
      RouteSelectionExpression: "$request.body.action"

  WebSocketConnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WebSocketApi
      RouteKey: $connect
      AuthorizationType: NONE
      OperationName: WebSocketConnectRoute
      Target: !Join
        - '/'
        - - 'integrations'
          - !Ref WebSocketConnectIntegration

  WebSocketConnectIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref WebSocketApi
      Description: Connect Integration
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${LambdaOnConnectFunctionName}/invocations


  WebSocketDisconnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WebSocketApi
      RouteKey: $disconnect
      AuthorizationType: NONE
      OperationName: WebSocketDisconnectRoute
      Target: !Join
        - '/'
        - - 'integrations'
          - !Ref WebSocketDisconnectIntegration

  WebSocketDisconnectIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref WebSocketApi
      Description: Disconnect Integration
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${LambdaOnDisconnectFunctionName}/invocations

  WebSocketMessageRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WebSocketApi
      RouteKey: $default
      AuthorizationType: NONE
      OperationName: WebSocketMessageRoute
      Target: !Join
        - '/'
        - - 'integrations'
          - !Ref WebSocketMessageIntegration

  WebSocketMessageIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref WebSocketApi
      Description: Message Integration
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${LambdaOnMessageFunctionName}/invocations

  WebSocketCustomListRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WebSocketApi
      RouteKey: "list"
      AuthorizationType: NONE
      OperationName: WebSocketCustomListRoute
      Target: !Join
        - '/'
        - - 'integrations'
          - !Ref WebSocketCustomListIntegration

  WebSocketCustomListIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref WebSocketApi
      Description: CustomList Integration
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${LambdaOnCustomListFunctionName}/invocations


# Deployments

  WebSocketDeployment:
    Type: AWS::ApiGatewayV2::Deployment
    DependsOn:
    - WebSocketConnectRoute
    - WebSocketMessageRoute
    - WebSocketDisconnectRoute
    - WebSocketCustomListRoute
    Properties:
      ApiId: !Ref WebSocketApi

  WebSocketStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      StageName: LATEST
      Description: Web Socket Stage
      DeploymentId: !Ref WebSocketDeployment
      ApiId: !Ref WebSocketApi

  WebSocketApiLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/apigateway/${WebSocketApi}/LATEST"
      RetentionInDays: 1

Outputs:

  InvokeURL:
    Value: !Sub wss://${WebSocketApi}.execute-api.${AWS::Region}.amazonaws.com/LATEST

  WebSocketApiEndpoint:
    Value: !GetAtt WebSocketApi.ApiEndpoint
