AWSTemplateFormatVersion: "2010-09-09"
Description: SNS - FIFO

Parameters:

  Application:
    Type: String
    Default: myapp
    Description: Application Name

  Environment:
    Type: String
    Default: stg
    Description: Environment

  TopicName:
    Type: String
    Default: sample-topic.fifo
    Description: Topic Name    

Resources:
  
  SNSTopicFifo:
    Type: "AWS::SNS::Topic"
    Properties:
      TopicName: !Sub "${Application}-${Environment}-${TopicName}"
      DisplayName: "My Topic"
      FifoTopic: true
      ContentBasedDeduplication: true
      Tags:
        -
          Key: "Environment"
          Value: !Ref Environment
        -
          Key: "Application"
          Value: !Ref Application

  QueueFifo:
    Type: AWS::SQS::Queue
    Properties:
      #QueueName: !Sub "${Application}-${Environment}-queue.fifo"
      FifoQueue: true
      ContentBasedDeduplication: true
      Tags:
        -
          Key: "Environment"
          Value: !Ref Environment
        -
          Key: "Application"
          Value: !Ref Application

  QueueFifoPolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues: 
        - !Ref QueueFifo
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                #- "events.amazonaws.com"
                #- "sqs.amazonaws.com"
                - "sns.amazonaws.com"
            Action:
              - "sqs:SendMessage"
              #- "sqs:ReceiveMessage"
            Resource: !GetAtt QueueFifo.Arn
            Condition:
              ArnEquals:
                aws:SourceArn: !Ref SNSTopicFifo

  Subscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: !GetAtt QueueFifo.Arn
      Protocol: sqs
      TopicArn: !Ref SNSTopicFifo
      RawMessageDelivery: 'true'

Outputs:

  SNSTopicArn:
    Description: SNSTopicFifo Arn
    Value: !Ref SNSTopicFifo

