AWSTemplateFormatVersion: "2010-09-09"
Description: SNS

Parameters:
  Application:
    Type: String
    Default: myapp
    Description: Application Name
  Environment:
    Type: String
    Default: stg
    Description: Environment
  TopicName:
    Type: String
    Default: sample-topic
    Description: Environment    

Resources:
  
  SNSTopic:
    Type: "AWS::SNS::Topic"
    Properties:
      TopicName: !Ref TopicName

  Subscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: test@example.com
      Protocol: email
      TopicArn: !Ref SNSTopic

Outputs:

  SNSTopicArn:
    Description: SNSTopic
    Value: !Ref SNSTopic

