AWSTemplateFormatVersion: "2010-09-09"
Description: "ECR"

Parameters:

  Application:
    Type: String
    Default: myapp
    Description: Application Name

  RepositoryName:
    Type: "String"
    Default: "ecr-repository-demo"
    Description: "ECR Repository Name"

Resources:

  EcrRepository: 
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref RepositoryName
      EncryptionConfiguration:
        EncryptionType: AES256 #AES256 | KMS
        #KmsKey
      ImageTagMutability: MUTABLE #IMMUTABLE | MUTABLE
      ImageScanningConfiguration: 
        ScanOnPush: true
      #LifecyclePolicy:
      #  RegistryId: 
      #  LifecyclePolicyText:
      Tags: 
        - Key: "Application"
          Value: !Ref Application
        - Key: "Name"
          Value: !Ref RepositoryName

Outputs:

  EcrRepositoryUri:
    Value: !GetAtt EcrRepository.RepositoryUri
 
  EcrRepositoryArn:
    Value: !GetAtt EcrRepository.Arn