AWSTemplateFormatVersion: "2010-09-09"
Description: "ECR"

Resources:

  EcrPullThroughCacheRule:
    Type: "AWS::ECR::PullThroughCacheRule"
    Properties:
      EcrRepositoryPrefix: "ecr-public"
      UpstreamRegistryUrl: "public.ecr.aws"
