AWSTemplateFormatVersion: "2010-09-09"
Description: "ECR"

Parameters:

  RepositoryName:
    Type: "String"
    Default: "ecr-repository-demo"
    Description: "ECR Repository Name"

Resources:

  EcrRepository: 
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref RepositoryName
      EncryptionConfiguration:
        EncryptionType: AES256
      ImageTagMutability: MUTABLE
      ImageScanningConfiguration: 
        ScanOnPush: true
      #LifecyclePolicy:
      #  RegistryId: 
      #  LifecyclePolicyText:
      Tags: 
        - Key: "Environment"
          Value: "dev"
        - Key: "Name"
          Value: !Ref RepositoryName

Outputs:

  EcrRepositoryUri:
    Value: !GetAtt EcrRepository.RepositoryUri
 
  EcrRepositoryArn:
    Value: !GetAtt EcrRepository.Arn