AWSTemplateFormatVersion: "2010-09-09"
Description: "ECR"

Resources:

  EcrRepository: 
    Type: AWS::ECR::Repository
    Properties: 
      RepositoryName: "ecr-repository-demo"
      ImageTagMutability: MUTABLE
      ImageScanningConfiguration: 
        ScanOnPush: true
      Tags: 
        - Key: "owner"
          Value: "me"
        - Key: "environment"
          Value: "dev"

Outputs:

  EcrRepositoryUri:
    Value: !GetAtt EcrRepository.RepositoryUri