AWSTemplateFormatVersion: '2010-09-09'
Description: Knowledge base with Amazon Opensearch Serverless vector database.

Parameters:

  KnowledgeBaseName:
    Type: String
    Description: The name of the knowledge base.
    Default: ''

  KnowledgeBaseDescription:
    Type: String
    Description: The description of the knowledge base.
    Default: ''

  KnowledgeBaseRoleArn:
    Type: String
    Description: KnowledgeBase role ARN
    Default: arn:aws:iam::123456789012:role/cfn-local-test-role

  VectorDatabaseCollectionArn:
    Type: String
    Description: KnowledgeBase role ARN
    Default: arn:aws:aoss:us-west-2:123456789012:collection/abcdefghij1234567890

  VectorDatabaseIndexName:
    Type: String
    Description: KnowledgeBase role ARN
    Default: arn:aws:aoss:us-west-2:123456789012:collection/abcdefghij1234567890

  VectorDatabaseIndexFieldMetadataName:
    Type: String
    Description: KnowledgeBase role ARN
    Default: arn:aws:aoss:us-west-2:123456789012:collection/abcdefghij1234567890

  DataSourceName:
    Type: String
    Description: The name of the data source.

  DataSourceDescription:
    Type: String
    Description: The description of the data source.

Resources:

  KnowledgeBase:
    Type: AWS::Bedrock::KnowledgeBase
    Properties:
      Name: !Ref KnowledgeBaseName
      Description: !Ref KnowledgeBaseDescription
      RoleArn: !Ref KnowledgeBaseRoleArn
      KnowledgeBaseConfiguration:
        Type: VECTOR
        VectorKnowledgeBaseConfiguration:
          EmbeddingModelArn: !Sub arn:${AWS::Partition}:bedrock:${AWS::Region}::foundation-model/amazon.titan-embed-text-v1
      StorageConfiguration:
        Type: OPENSEARCH_SERVERLESS
        OpensearchServerlessConfiguration:
          CollectionArn: !Ref VectorDatabaseCollectionArn
          VectorIndexName: !Ref VectorDatabaseIndexName
          FieldMapping:
            VectorField: !Ref VectorDatabaseIndexFieldMetadataName
            TextField: text
            MetadataField: metadata

  KnowledgeBaseDataSource:
    Type: AWS::Bedrock::DataSource
    Properties:
      KnowledgeBaseId: !Ref KnowledgeBase
      Name: !Ref DataSourceName
      Description: !Ref DataSourceDescription
      DataSourceConfiguration:
        Type: S3
        S3Configuration:
          BucketArn: arn:aws:s3:::kb-test-aws
          #InclusionPrefixes:
          #  - aws-overview.pdf