AWSTemplateFormatVersion: "2010-09-09"
Description: Bedrock - Roles

# Agents for Bedrock Service Role
### Create an IAM role with the prefix AmazonBedrockExecutionRoleForAgents_

Resources:

  # AmazonBedrockExecutionRoleForAgents

  BedrockAgentRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: "AmazonBedrockExecutionRoleForAgents_007"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - "bedrock.amazonaws.com"
            Action:
              - "sts:AssumeRole"
            #Condition:
            #  StringEquals:
            #    "aws:SourceAccount": !Sub "${AWS::AccountId}"
            #  ArnLike:
            #    "AWS:SourceArn": !Sub "arn:aws:bedrock:${AWS::Region}:${AWS::AccountId}:agent/*"
      Path: /
      ManagedPolicyArns:
        - !Ref BedrockAgentRolePolicy

  BedrockAgentRolePolicy:
    Type: "AWS::IAM::ManagedPolicy"
    Properties:
      Description: "BedrockAgent Role ManagedPolicy"
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - "logs:CreateLogGroup"
              - "logs:CreateLogStream"
              - "logs:PutLogEvents"
            Effect: Allow
            Resource: "*"
          - Action:
              - "s3:GetObject"
              - "s3:PutObject"
              - "s3:GetObjectVersion"
            Effect: Allow
            Resource: "*"
          - Action:
              - "bedrock:*"
            Effect: Allow
            Resource: "*"
          - Action: # Permissions to access your action group Lambda functions
              - "lambda:InvokeFunction"
            Effect: Allow
            Resource: "*" # "arn:aws:lambda:region:account-id:function:function-name"
            #Condition:
            #  StringEquals:
            #    "AWS:SourceAccount": !Sub "${AWS::AccountId}"
            #  ArnLike:
            #    "AWS:SourceArn": !Sub "arn:aws:bedrock:${AWS::Region}:${AWS::AccountId}:agent/agent-id"
          - Action: # (Optional) Permissions to access your knowledge bases
              - "bedrock:Retrieve"
              - "bedrock:RetrieveAndGenerate"
            Effect: Allow
            Resource: "*" # "arn:aws:bedrock:*:account-id:knowledge-base/knowledge-base-id"
          - Action: # Permissions to access Amazon Bedrock models
              - "bedrock:InvokeModel"
            Effect: Allow
            Resource:
              - "arn:aws:bedrock:region::foundation-model/anthropic.claude-v2"
              - "arn:aws:bedrock:region::foundation-model/anthropic.claude-v2:1"
              - "arn:aws:bedrock:region::foundation-model/anthropic.claude-instant-v1"