AWSTemplateFormatVersion: '2010-09-09'
Description: |
  Amazon Bedrock Application Inference Profiles - Comprehensive Setup

  This CloudFormation template creates multiple Application Inference Profiles for different use cases:
  1. Cost Tracking - Separate profiles per team/department for cost allocation
  2. Usage Metrics - Profiles configured for CloudWatch monitoring and analysis
  3. Environment Separation - Profiles for dev/staging/production environments
  4. Cross-Region Tracking - Profiles that track usage across multiple regions

  Prerequisites:
  - Amazon Bedrock model access must be enabled in your AWS account
  - Appropriate IAM permissions to create Bedrock resources
  - CloudWatch Logs should be configured for usage tracking (separate setup required)

  Cost Implications:
  - No additional cost for creating inference profiles
  - Standard model invocation charges apply based on the underlying model pricing
  - CloudWatch Logs charges apply if logging is enabled

  Author: AWS Solutions Architect
  Version: 1.0
  Last Updated: 2024

Parameters:
  Environment:
    Type: String
    Default: production
    AllowedValues:
      - development
      - staging
      - production
    Description: Environment name for resource tagging and identification

  ProjectName:
    Type: String
    Default: my-genai-project
    Description: Project name for resource naming and cost allocation
    MinLength: 3
    MaxLength: 32

  CostCenter:
    Type: String
    Default: engineering
    Description: Cost center for billing and cost allocation tracking

Resources:

  # ============================================================================
  # USE CASE 1: COST TRACKING BY TEAM
  # Track costs separately for different teams using the same model
  # ============================================================================

  MarketingTeamInferenceProfile:
    Type: AWS::Bedrock::ApplicationInferenceProfile
    Properties:
      # Profile name - must be unique within the account
      InferenceProfileName: !Sub '${ProjectName}-marketing-team-claude'

      # Human-readable description
      Description: 'Inference profile for Marketing team to track Claude 3.5 Sonnet usage and costs'

      # Model source - points to Claude 3.5 Sonnet in us-east-1
      # This creates a single-region profile for cost tracking
      ModelSource:
        CopyFrom: 'arn:aws:bedrock:us-east-1::foundation-model/anthropic.claude-3-5-sonnet-20240620-v1:0'

      # Tags for cost allocation - these appear in AWS Cost Explorer
      Tags:
        - Key: Team
          Value: Marketing
        - Key: CostCenter
          Value: !Ref CostCenter
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName
        - Key: Purpose
          Value: CostTracking
        - Key: ManagedBy
          Value: CloudFormation

  EngineeringTeamInferenceProfile:
    Type: AWS::Bedrock::ApplicationInferenceProfile
    Properties:
      InferenceProfileName: !Sub '${ProjectName}-engineering-team-claude'
      Description: 'Inference profile for Engineering team to track Claude 3.5 Sonnet usage and costs'
      ModelSource:
        CopyFrom: 'arn:aws:bedrock:us-east-1::foundation-model/anthropic.claude-3-5-sonnet-20240620-v1:0'
      Tags:
        - Key: Team
          Value: Engineering
        - Key: CostCenter
          Value: !Ref CostCenter
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName
        - Key: Purpose
          Value: CostTracking
        - Key: ManagedBy
          Value: CloudFormation

  CustomerSupportTeamInferenceProfile:
    Type: AWS::Bedrock::ApplicationInferenceProfile
    Properties:
      InferenceProfileName: !Sub '${ProjectName}-support-team-claude'
      Description: 'Inference profile for Customer Support team to track Claude 3.5 Sonnet usage and costs'
      ModelSource:
        CopyFrom: 'arn:aws:bedrock:us-east-1::foundation-model/anthropic.claude-3-5-sonnet-20240620-v1:0'
      Tags:
        - Key: Team
          Value: CustomerSupport
        - Key: CostCenter
          Value: !Ref CostCenter
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName
        - Key: Purpose
          Value: CostTracking
        - Key: ManagedBy
          Value: CloudFormation

  # ============================================================================
  # USE CASE 2: USAGE METRICS BY ENVIRONMENT
  # Separate profiles for dev/staging/prod to track usage patterns
  # ============================================================================

  DevelopmentInferenceProfile:
    Type: AWS::Bedrock::ApplicationInferenceProfile
    Properties:
      InferenceProfileName: !Sub '${ProjectName}-dev-claude'
      Description: 'Development environment inference profile for testing and experimentation'
      ModelSource:
        # Using us-west-2 for development to separate from production region
        CopyFrom: 'arn:aws:bedrock:us-west-2::foundation-model/anthropic.claude-3-5-sonnet-20240620-v1:0'
      Tags:
        - Key: Environment
          Value: development
        - Key: Project
          Value: !Ref ProjectName
        - Key: Purpose
          Value: UsageMetrics
        - Key: Criticality
          Value: Low
        - Key: ManagedBy
          Value: CloudFormation

  StagingInferenceProfile:
    Type: AWS::Bedrock::ApplicationInferenceProfile
    Properties:
      InferenceProfileName: !Sub '${ProjectName}-staging-claude'
      Description: 'Staging environment inference profile for pre-production testing'
      ModelSource:
        CopyFrom: 'arn:aws:bedrock:us-east-1::foundation-model/anthropic.claude-3-5-sonnet-20240620-v1:0'
      Tags:
        - Key: Environment
          Value: staging
        - Key: Project
          Value: !Ref ProjectName
        - Key: Purpose
          Value: UsageMetrics
        - Key: Criticality
          Value: Medium
        - Key: ManagedBy
          Value: CloudFormation

  ProductionInferenceProfile:
    Type: AWS::Bedrock::ApplicationInferenceProfile
    Properties:
      InferenceProfileName: !Sub '${ProjectName}-prod-claude'
      Description: 'Production environment inference profile with usage tracking and monitoring'
      ModelSource:
        CopyFrom: 'arn:aws:bedrock:us-east-1::foundation-model/anthropic.claude-3-5-sonnet-20240620-v1:0'
      Tags:
        - Key: Environment
          Value: production
        - Key: Project
          Value: !Ref ProjectName
        - Key: Purpose
          Value: UsageMetrics
        - Key: Criticality
          Value: High
        - Key: Backup
          Value: Required
        - Key: ManagedBy
          Value: CloudFormation

  # ============================================================================
  # USE CASE 3: CROSS-REGION USAGE TRACKING
  # Track usage across multiple regions using system-defined inference profiles
  # ============================================================================

  CrossRegionUSInferenceProfile:
    Type: AWS::Bedrock::ApplicationInferenceProfile
    Properties:
      InferenceProfileName: !Sub '${ProjectName}-cross-region-us-claude'
      Description: |
        Cross-region inference profile tracking usage across US regions.
        Routes to us-east-1, us-west-2, and other US regions automatically.
        Provides higher throughput and automatic failover.
      ModelSource:
        # Copy from system-defined cross-region profile (note the "us." prefix)
        # This profile automatically routes across multiple US regions
        CopyFrom: 'us.anthropic.claude-3-5-sonnet-20240620-v1:0'
      Tags:
        - Key: Scope
          Value: CrossRegion
        - Key: Regions
          Value: US-Multi
        - Key: Project
          Value: !Ref ProjectName
        - Key: Purpose
          Value: HighThroughput
        - Key: Environment
          Value: !Ref Environment
        - Key: ManagedBy
          Value: CloudFormation

  CrossRegionEUInferenceProfile:
    Type: AWS::Bedrock::ApplicationInferenceProfile
    Properties:
      InferenceProfileName: !Sub '${ProjectName}-cross-region-eu-claude'
      Description: |
        Cross-region inference profile for European users.
        Routes to eu-west-1, eu-central-1, and other EU regions automatically.
        Ensures data residency compliance while providing high availability.
      ModelSource:
        # Copy from EU system-defined cross-region profile
        CopyFrom: 'eu.anthropic.claude-3-5-sonnet-20240620-v1:0'
      Tags:
        - Key: Scope
          Value: CrossRegion
        - Key: Regions
          Value: EU-Multi
        - Key: Project
          Value: !Ref ProjectName
        - Key: Purpose
          Value: DataResidency
        - Key: Compliance
          Value: GDPR
        - Key: Environment
          Value: !Ref Environment
        - Key: ManagedBy
          Value: CloudFormation

  # ============================================================================
  # USE CASE 4: MODEL-SPECIFIC USAGE TRACKING
  # Track usage for different models separately
  # ============================================================================

  ClaudeHaikuInferenceProfile:
    Type: AWS::Bedrock::ApplicationInferenceProfile
    Properties:
      InferenceProfileName: !Sub '${ProjectName}-claude-haiku'
      Description: 'Fast, cost-effective Claude Haiku for simple tasks and high-volume processing'
      ModelSource:
        # Claude Haiku - fastest and most cost-effective
        CopyFrom: 'arn:aws:bedrock:us-east-1::foundation-model/anthropic.claude-3-haiku-20240307-v1:0'
      Tags:
        - Key: ModelType
          Value: Haiku
        - Key: UseCase
          Value: HighVolume
        - Key: CostProfile
          Value: Low
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
        - Key: ManagedBy
          Value: CloudFormation

  ClaudeSonnetInferenceProfile:
    Type: AWS::Bedrock::ApplicationInferenceProfile
    Properties:
      InferenceProfileName: !Sub '${ProjectName}-claude-sonnet'
      Description: 'Balanced Claude Sonnet for general-purpose tasks requiring good performance'
      ModelSource:
        # Claude Sonnet - balanced performance and cost
        CopyFrom: 'arn:aws:bedrock:us-east-1::foundation-model/anthropic.claude-3-5-sonnet-20240620-v1:0'
      Tags:
        - Key: ModelType
          Value: Sonnet
        - Key: UseCase
          Value: GeneralPurpose
        - Key: CostProfile
          Value: Medium
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
        - Key: ManagedBy
          Value: CloudFormation

  ClaudeOpusInferenceProfile:
    Type: AWS::Bedrock::ApplicationInferenceProfile
    Properties:
      InferenceProfileName: !Sub '${ProjectName}-claude-opus'
      Description: 'Premium Claude Opus for complex reasoning and highest quality outputs'
      ModelSource:
        # Claude Opus - highest capability and cost
        CopyFrom: 'arn:aws:bedrock:us-east-1::foundation-model/anthropic.claude-3-opus-20240229-v1:0'
      Tags:
        - Key: ModelType
          Value: Opus
        - Key: UseCase
          Value: ComplexReasoning
        - Key: CostProfile
          Value: High
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
        - Key: ManagedBy
          Value: CloudFormation

  # ============================================================================
  # USE CASE 5: FEATURE-SPECIFIC TRACKING
  # Track usage by application feature or capability
  # ============================================================================

  ChatbotInferenceProfile:
    Type: AWS::Bedrock::ApplicationInferenceProfile
    Properties:
      InferenceProfileName: !Sub '${ProjectName}-chatbot-feature'
      Description: 'Inference profile dedicated to customer-facing chatbot feature'
      ModelSource:
        CopyFrom: 'arn:aws:bedrock:us-east-1::foundation-model/anthropic.claude-3-5-sonnet-20240620-v1:0'
      Tags:
        - Key: Feature
          Value: Chatbot
        - Key: UserFacing
          Value: 'true'
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
        - Key: Purpose
          Value: FeatureTracking
        - Key: ManagedBy
          Value: CloudFormation

  DocumentSummaryInferenceProfile:
    Type: AWS::Bedrock::ApplicationInferenceProfile
    Properties:
      InferenceProfileName: !Sub '${ProjectName}-document-summary-feature'
      Description: 'Inference profile for document summarization and analysis feature'
      ModelSource:
        CopyFrom: 'arn:aws:bedrock:us-east-1::foundation-model/anthropic.claude-3-5-sonnet-20240620-v1:0'
      Tags:
        - Key: Feature
          Value: DocumentSummary
        - Key: UserFacing
          Value: 'true'
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
        - Key: Purpose
          Value: FeatureTracking
        - Key: ManagedBy
          Value: CloudFormation

  CodeGenerationInferenceProfile:
    Type: AWS::Bedrock::ApplicationInferenceProfile
    Properties:
      InferenceProfileName: !Sub '${ProjectName}-code-generation-feature'
      Description: 'Inference profile for code generation and review features'
      ModelSource:
        CopyFrom: 'arn:aws:bedrock:us-east-1::foundation-model/anthropic.claude-3-5-sonnet-20240620-v1:0'
      Tags:
        - Key: Feature
          Value: CodeGeneration
        - Key: UserFacing
          Value: 'false'
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
        - Key: Purpose
          Value: FeatureTracking
        - Key: ManagedBy
          Value: CloudFormation

# ============================================================================
# OUTPUTS
# Export inference profile ARNs and IDs for use in other stacks or applications
# ============================================================================

Outputs:
  # Cost Tracking Profiles
  MarketingTeamProfileArn:
    Description: ARN of the Marketing team inference profile for cost tracking
    Value: !GetAtt MarketingTeamInferenceProfile.InferenceProfileArn
    Export:
      Name: !Sub '${AWS::StackName}-MarketingProfileArn'

  MarketingTeamProfileId:
    Description: ID of the Marketing team inference profile
    Value: !GetAtt MarketingTeamInferenceProfile.InferenceProfileId
    Export:
      Name: !Sub '${AWS::StackName}-MarketingProfileId'

  EngineeringTeamProfileArn:
    Description: ARN of the Engineering team inference profile for cost tracking
    Value: !GetAtt EngineeringTeamInferenceProfile.InferenceProfileArn
    Export:
      Name: !Sub '${AWS::StackName}-EngineeringProfileArn'

  CustomerSupportTeamProfileArn:
    Description: ARN of the Customer Support team inference profile for cost tracking
    Value: !GetAtt CustomerSupportTeamInferenceProfile.InferenceProfileArn
    Export:
      Name: !Sub '${AWS::StackName}-SupportProfileArn'

  # Environment Profiles
  DevelopmentProfileArn:
    Description: ARN of the Development environment inference profile
    Value: !GetAtt DevelopmentInferenceProfile.InferenceProfileArn
    Export:
      Name: !Sub '${AWS::StackName}-DevProfileArn'

  StagingProfileArn:
    Description: ARN of the Staging environment inference profile
    Value: !GetAtt StagingInferenceProfile.InferenceProfileArn
    Export:
      Name: !Sub '${AWS::StackName}-StagingProfileArn'

  ProductionProfileArn:
    Description: ARN of the Production environment inference profile
    Value: !GetAtt ProductionInferenceProfile.InferenceProfileArn
    Export:
      Name: !Sub '${AWS::StackName}-ProdProfileArn'

  # Cross-Region Profiles
  CrossRegionUSProfileArn:
    Description: ARN of the US cross-region inference profile for high throughput
    Value: !GetAtt CrossRegionUSInferenceProfile.InferenceProfileArn
    Export:
      Name: !Sub '${AWS::StackName}-CrossRegionUSArn'

  CrossRegionEUProfileArn:
    Description: ARN of the EU cross-region inference profile for data residency
    Value: !GetAtt CrossRegionEUInferenceProfile.InferenceProfileArn
    Export:
      Name: !Sub '${AWS::StackName}-CrossRegionEUArn'

  # Model-Specific Profiles
  ClaudeHaikuProfileArn:
    Description: ARN of Claude Haiku inference profile for high-volume, low-cost tasks
    Value: !GetAtt ClaudeHaikuInferenceProfile.InferenceProfileArn
    Export:
      Name: !Sub '${AWS::StackName}-HaikuProfileArn'

  ClaudeSonnetProfileArn:
    Description: ARN of Claude Sonnet inference profile for balanced performance
    Value: !GetAtt ClaudeSonnetInferenceProfile.InferenceProfileArn
    Export:
      Name: !Sub '${AWS::StackName}-SonnetProfileArn'

  ClaudeOpusProfileArn:
    Description: ARN of Claude Opus inference profile for complex reasoning
    Value: !GetAtt ClaudeOpusInferenceProfile.InferenceProfileArn
    Export:
      Name: !Sub '${AWS::StackName}-OpusProfileArn'

  # Feature-Specific Profiles
  ChatbotProfileArn:
    Description: ARN of Chatbot feature inference profile
    Value: !GetAtt ChatbotInferenceProfile.InferenceProfileArn
    Export:
      Name: !Sub '${AWS::StackName}-ChatbotProfileArn'

  DocumentSummaryProfileArn:
    Description: ARN of Document Summary feature inference profile
    Value: !GetAtt DocumentSummaryInferenceProfile.InferenceProfileArn
    Export:
      Name: !Sub '${AWS::StackName}-DocSummaryProfileArn'

  CodeGenerationProfileArn:
    Description: ARN of Code Generation feature inference profile
    Value: !GetAtt CodeGenerationInferenceProfile.InferenceProfileArn
    Export:
      Name: !Sub '${AWS::StackName}-CodeGenProfileArn'

  # Usage Instructions
  UsageInstructions:
    Description: How to use these inference profiles in your application
    Value: |
      Use these profile ARNs in your boto3 code:
      bedrock.invoke_model(modelId='<ProfileArn>', body=...)

      View costs in AWS Cost Explorer filtered by tags:
      - Team (Marketing, Engineering, CustomerSupport)
      - Environment (development, staging, production)
      - Feature (Chatbot, DocumentSummary, CodeGeneration)

      Monitor usage in CloudWatch (requires separate log configuration):
      - Set up model invocation logging in Bedrock console
      - Filter logs by inference profile ID