AWSTemplateFormatVersion: '2010-09-09'
Description: RDS - Aurora Serverless v2 (Aurora3)

# TODO: Meta

Parameters:

  VpcId:
    Description: VPC ID
    Type: AWS::EC2::VPC::Id

  VpcSubnetList:
    Description: Private VpcSubnets for Web Servers
    Type: List<AWS::EC2::Subnet::Id>

  DatabaseClusterName:
    Description: DatabaseClusterName
    Type: String
    Default: rdsserverlessclusterbasic

  MasterUsername:
    Description: MasterUsername
    Type: String
    Default: admin
    MinLength: '1'
    MaxLength: '16'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: must begin with a letter and contain only alphanumeric characters.

  MasterUserPassword:
    Description: MasterUserPassword
    Type: String
    Default: password
    NoEcho: true
    MinLength: '3'
    MaxLength: '24'
    AllowedPattern: '[a-zA-Z0-9]*'
    ConstraintDescription: must contain only alphanumeric characters.

  DatabaseClientCidr:
    Description: DB Client CIDR Block
    Type: String
    Default: 0.0.0.0/32

Resources:

  DatabaseSubnetGroup:
    Type: "AWS::RDS::DBSubnetGroup"
    Properties:
      #DBSubnetGroupName
      DBSubnetGroupDescription: !Sub "rds-aurora-serverless-v2-basic-subnet-group"
      SubnetIds: !Ref VpcSubnetList
      Tags:
        - 
          Key: "Name"
          Value: !Sub "rds-aurora-serverless-v2-basic-subnet-group"

  DatabaseSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      VpcId: !Ref VpcId
      GroupDescription: !Sub "rds-aurora-serverless-v2-basic-sg"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          CidrIp: !Ref DatabaseClientCidr

  DatabaseClusterParameterGroup:
    Type: "AWS::RDS::DBClusterParameterGroup"
    Properties:
      DBClusterParameterGroupName: !Sub "rds-aurora-serverless-v2-basic-cluster-parameter-group"
      Description: !Sub "rds-aurora-serverless-v2-basic-cluster-parameter-group"
      Family: aurora-mysql8.0
      Parameters:
        character_set_server: utf8
        character_set_client: utf8
        character_set_connection: utf8
        character_set_results: utf8
        character_set_database: utf8
        performance_schema: 1
      Tags:
        - 
          Key: "Name"
          Value: !Sub "rds-aurora-serverless-v2-basic-cluster-parameter-group"

  DatabaseParameterGroup:
    Type: "AWS::RDS::DBParameterGroup"
    Properties:
      DBParameterGroupName: "rds-aurora-serverless-v2-basic-parameter-group"
      Description: !Sub "rds-aurora-serverless-v2-basic-parameter-group"
      Family: aurora-mysql8.0
      Parameters:
        general_log: 0
        slow_query_log: 1
        long_query_time: 5000
        log_output: FILE
      Tags:
       - 
         Key: "Name"
         Value: !Sub "rds-aurora-serverless-v2-basic-parameter-group"

  DatabaseCluster:
    Type: "AWS::RDS::DBCluster"
    DeletionPolicy: Snapshot
    Properties:
      DatabaseName: !Ref DatabaseClusterName
      MasterUsername: !Ref MasterUsername
      MasterUserPassword: !Ref MasterUserPassword
      DBSubnetGroupName: !Ref DatabaseSubnetGroup
      Engine: aurora-mysql
      EngineVersion: 8.0.mysql_aurora.3.02.0
      VpcSecurityGroupIds:
        - !Ref DatabaseSecurityGroup
      DBClusterParameterGroupName: !Ref DatabaseClusterParameterGroup
      PreferredMaintenanceWindow: Fri:20:00-Fri:22:00
      PreferredBackupWindow: 18:00-19:00
      BackupRetentionPeriod: 7
      ServerlessV2ScalingConfiguration: 
        MaxCapacity: 16
        MinCapacity: 0.5
      Tags:
        - 
          Key: "Name"
          Value: !Sub "rds-aurora-serverless-v2-basic-cluster"

  DatabaseInstance1:
    Type: "AWS::RDS::DBInstance"
    Properties:
      DBClusterIdentifier: !Ref DatabaseCluster
      DBInstanceClass: db.serverless
      DBParameterGroupName: !Ref DatabaseParameterGroup
      Engine: aurora-mysql
      EnablePerformanceInsights: true
      PreferredMaintenanceWindow: Thu:19:05-Thu:19:35
      PromotionTier: 0
      AvailabilityZone: !Select
        - 0
        - !GetAZs
          Ref: AWS::Region
      Tags:
        - 
          Key: "Name"
          Value: !Sub "rds-aurora-serverless-v2-db-instance-1"
          
  DatabaseInstance2:
    Type: "AWS::RDS::DBInstance"
    Properties:
      DBClusterIdentifier: !Ref DatabaseCluster
      DBInstanceClass: db.serverless
      DBParameterGroupName: !Ref DatabaseParameterGroup
      Engine: aurora-mysql
      EnablePerformanceInsights: true
      PreferredMaintenanceWindow: Thu:19:05-Thu:19:35
      PromotionTier: 1
      AvailabilityZone: !Select
        - 1
        - !GetAZs
          Ref: AWS::Region
      Tags:
        - 
          Key: "Name"
          Value: !Sub "rds-aurora-serverless-v2-db-instance-2"