AWSTemplateFormatVersion: "2010-09-09"
Description: "App Runner AutoScaling Confguration"

Parameters:

  AutoScalingMaxConcurrency:
    Type: String
    Default: "100"

  AutoScalingMinSize:
    Type: String
    Default: "1" #Min 1

  AutoScalingMaxSize:
    Type: String
    Default: "25"

Resources:

  AppRunnerAutoScalingConfiguration:
    Type: AWS::AppRunner::AutoScalingConfiguration
    Properties:
      #AutoScalingConfigurationName: "AUTO_SCALING_CONFIGURATION_NAME"
      MaxConcurrency: !Ref AutoScalingMaxConcurrency
      MinSize: !Ref AutoScalingMinSize
      MaxSize: !Ref AutoScalingMaxSize
      Tags:
        - Key: "Name"
          Value: "AppRunnerAutoScalingCfg"

Outputs:    

  AppRunnerAutoScalingConfigurationArn:
    Value: !Sub "${AppRunnerAutoScalingConfiguration.AutoScalingConfigurationArn}"

  #AppRunnerAutoScalingConfigurationRevision:
  #  Value: !Sub "${AppRunnerAutoScalingConfiguration.AutoScalingConfigurationArn}:${AppRunnerAutoScalingConfiguration.AutoScalingConfigurationRevision}"
