AWSTemplateFormatVersion: "2010-09-09"
Description: "Provision an AppRunner Service Role, Instance Role and Service backed by ECR Public Image"

Parameters:

  ContainerImageUri:
    Type: String
    Default: "public.ecr.aws/aws-containers/hello-app-runner:latest"

  ContainerServicePort:
    Type: String
    Default: "8000"

  ContainerRepositoryType:
    Type: String
    Default: "ECR_PUBLIC"

  ObservabilityConfigurationArn:
    Type: String
    Default: "arn:aws:apprunner:us-west-1:0000000000:observabilityconfiguration/name"
  
  AppRunnerAutoScalingConfigurationArn:
    Type: String
    Default: "arn:aws:apprunner:us-west-1:0000000000:autoscalingconfiguration/name"

Resources:

  AppRunnerInstanceRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - tasks.apprunner.amazonaws.com
            Action:
              - "sts:AssumeRole"
      Path: /
      ManagedPolicyArns:
        - !Ref AppRunnerInstanceRolePolicy

  AppRunnerInstanceRolePolicy:
    Type: "AWS::IAM::ManagedPolicy"
    Properties:
      Description: "App Runner Instance Role ManagedPolicy"
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - 'logs:CreateLogGroup'
              - 'logs:CreateLogStream'
              - 'logs:PutLogEvents'
            Effect: Allow
            Resource: '*'
          - Action:
              - 's3:GetObject'
              - 's3:PutObject'
              - 's3:GetObjectVersion'
            Effect: Allow
            Resource: '*'
          - Action:
              - 'bedrock:*'
            Effect: Allow
            Resource: '*'
          - Action:
              - 'ssm:GetParameters'
            Effect: Allow
            Resource: '*'
          - Action:
              - 'secretsmanager:GetSecretValue'
            Effect: Allow
            Resource: '*'
          - Action:
              - 'kms:Decrypt*'
            Effect: Allow
            Resource: '*'

  AppRunnerService:
    Type: AWS::AppRunner::Service
    Properties:
      #ServiceName: 
      SourceConfiguration:
        #AuthenticationConfiguration:
        #  AccessRoleArn: !GetAtt AppRunnerServiceRole.Arn
        AutoDeploymentsEnabled: false
        ImageRepository:
          ImageIdentifier: !Ref ContainerImageUri
          ImageRepositoryType: !Ref ContainerRepositoryType
          ImageConfiguration:
            Port: !Ref ContainerServicePort
      InstanceConfiguration:
        Cpu: 1 vCPU
        Memory: 2 GB
        InstanceRoleArn: !GetAtt AppRunnerInstanceRole.Arn
      ObservabilityConfiguration:
        ObservabilityEnabled: true
        ObservabilityConfigurationArn: !Ref ObservabilityConfigurationArn
      AutoScalingConfigurationArn: !Ref AppRunnerAutoScalingConfigurationArn
      Tags:
        - Key: "Name"
          Value: "AppRunnerService"

Outputs:    

  AppRunnerServiceUrl:
    Value: !GetAtt AppRunnerService.ServiceUrl
