AWSTemplateFormatVersion: 2010-09-09
Description: Organization Access Role

Parameters:

  OrganizationManagementAccountId:
    Type: String
    Default: myapp
    Description: OrganizationManagementAccountId
    
Resources:

  OrganizationAccountAccessRole: 
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/AdministratorAccess
      RoleName: OrganizationAccountAccessRole
      AssumeRolePolicyDocument:
       Version: 2012-10-17
       Statement:
         - Effect: Allow
           Action: sts:AssumeRole
           Principal:
            AWS: !Ref OrganizationManagementAccountId
      Tags:
        - Key: "Name"
          Value: "organization-account-access-role"
 
Outputs:

  OrganizationAccountAccessRoleArn:
    Value: !GetAtt OrganizationAccountAccessRole.Arn
