AWSTemplateFormatVersion: '2010-09-09'

Parameters:

  CodeBucketName:
    Type: String
    Default: demo-cloudformation
    Description: Bucket containing lambda code

  CodeObjectKey:
    Type: String
    Default: beanstalk/tomcat.zip
    Description: Object Key of the zipped code

  PlatformVersion:
    Type: String
    Default: 64bit Amazon Linux 2018.03 v3.4.20 running Tomcat 8.5 Java 8
    Description: Platform Version

  VpcId:
    Description: VPC ID
    Type: AWS::EC2::VPC::Id

  VpcSubnetListLoadBalancer:
    Description: Public VpcSubnets for Load Balancer
    Type: List<AWS::EC2::Subnet::Id>

  VpcSubnetListWebServer:
    Description: Private VpcSubnets for Web Servers
    Type: List<AWS::EC2::Subnet::Id>

Resources:

  sampleApplication:
    Type: AWS::ElasticBeanstalk::Application
    Properties:
      Description: AWS Elastic Beanstalk Sample Application

  sampleApplicationVersion:
    Type: AWS::ElasticBeanstalk::ApplicationVersion
    Properties:
      ApplicationName:
        Ref: sampleApplication
      Description: AWS ElasticBeanstalk Sample Application Version
      SourceBundle:
        S3Bucket: !Ref CodeBucketName
        S3Key: !Ref CodeObjectKey

  sampleConfigurationTemplate:
    Type: AWS::ElasticBeanstalk::ConfigurationTemplate
    Properties:
      ApplicationName:
        Ref: sampleApplication
      Description: AWS ElasticBeanstalk Sample Configuration Template
      SolutionStackName: !Ref PlatformVersion
      OptionSettings:
      - Namespace: aws:ec2:vpc
        OptionName: VPCId
        Value: !Ref VpcId
      - Namespace: aws:ec2:vpc
        OptionName: Subnets
        Value: !Join [',', !Ref VpcSubnetListWebServer]
      - Namespace: aws:ec2:vpc
        OptionName: ELBSubnets
        Value: !Join [',', !Ref VpcSubnetListLoadBalancer]
      - Namespace: aws:ec2:vpc
        OptionName: AssociatePublicIpAddress
        Value: false # Using Private Subnet
      - Namespace: aws:ec2:vpc
        OptionName: ELBScheme
        Value: public # Public Facing
      - Namespace: aws:autoscaling:asg
        OptionName: MinSize
        Value: '1'
      - Namespace: aws:autoscaling:asg
        OptionName: MaxSize
        Value: '1'
      - Namespace: aws:elasticbeanstalk:environment
        OptionName: EnvironmentType
        Value: LoadBalanced
      - Namespace: aws:autoscaling:launchconfiguration
        OptionName: IamInstanceProfile
        Value: !Ref MyInstanceProfile

      #- Namespace: aws:ec2:vpc
      #  OptionName: DBSubnets
      #  Value: LoadBalanced

  sampleEnvironment:
    Type: AWS::ElasticBeanstalk::Environment
    Properties:
      ApplicationName:
        Ref: sampleApplication
      Description: AWS ElasticBeanstalk Sample Environment
      TemplateName:
        Ref: sampleConfigurationTemplate
      VersionLabel:
        Ref: sampleApplicationVersion
      Tags: 
        - Key: "env"
          Value: "prd"

  MyInstanceRole:
    Type: AWS::IAM::Role
    Properties: 
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Description: Beanstalk EC2 role
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/AWSElasticBeanstalkWebTier
        - arn:aws:iam::aws:policy/AWSElasticBeanstalkMulticontainerDocker
        - arn:aws:iam::aws:policy/AWSElasticBeanstalkWorkerTier
      Tags:
        - Key: 'environment'
          Value: common

  MyInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties: 
      Roles:
        - !Ref MyInstanceRole
