AWSTemplateFormatVersion: '2010-09-09'
Description: 'Stage 2: Bedrock AgentCore Runtime (Deploy AFTER building image)'

Parameters:
  AgentRuntimeName:
    Type: String
    Default: my_bedrock_agent_runtime
    Description: Name for the AgentCore Runtime (letters, numbers, underscores only)
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9_]{0,47}'
    ConstraintDescription: Must start with a letter and contain only letters, numbers, and underscores

  ImageUri:
    Type: String
    Description: Full ECR image URI (from Stage 1 outputs)

Resources:
  # ============================================
  # AgentCore Runtime IAM Role
  # ============================================
  RuntimeRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${AWS::StackName}-RuntimeRole'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AssumeRolePolicy
            Effect: Allow
            Principal:
              Service: bedrock-agentcore.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: AgentCoreRuntimePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              # Bedrock permissions
              - Sid: BedrockPermissions
                Effect: Allow
                Action:
                  - bedrock:InvokeModel
                  - bedrock:InvokeModelWithResponseStream
                Resource: '*'

              # ECR permissions
              - Sid: ECRImageAccess
                Effect: Allow
                Action:
                  - ecr:BatchGetImage
                  - ecr:GetDownloadUrlForLayer
                Resource: !Sub 'arn:aws:ecr:${AWS::Region}:${AWS::AccountId}:repository/*'

              - Sid: ECRTokenAccess
                Effect: Allow
                Action:
                  - ecr:GetAuthorizationToken
                Resource: '*'

              # CloudWatch Logs permissions
              - Sid: LogsCreateAndDescribe
                Effect: Allow
                Action:
                  - logs:DescribeLogStreams
                  - logs:CreateLogGroup
                Resource: !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/bedrock-agentcore/runtimes/*'

              - Sid: LogsDescribeGroups
                Effect: Allow
                Action:
                  - logs:DescribeLogGroups
                Resource: !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:*'

              - Sid: LogsPutEvents
                Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/bedrock-agentcore/runtimes/*:log-stream:*'

              # X-Ray permissions
              - Sid: XRayAccess
                Effect: Allow
                Action:
                  - xray:PutTraceSegments
                  - xray:PutTelemetryRecords
                  - xray:GetSamplingRules
                  - xray:GetSamplingTargets
                Resource: '*'

              # CloudWatch Metrics
              - Sid: CloudWatchMetrics
                Effect: Allow
                Action:
                  - cloudwatch:PutMetricData
                Resource: '*'

              # Workload Identity permissions
              - Sid: GetAgentAccessToken
                Effect: Allow
                Action:
                  - bedrock-agentcore:GetWorkloadAccessToken
                  - bedrock-agentcore:GetWorkloadAccessTokenForJWT
                  - bedrock-agentcore:GetWorkloadAccessTokenForUserId
                Resource:
                  - !Sub 'arn:aws:bedrock-agentcore:${AWS::Region}:${AWS::AccountId}:workload-identity-directory/default'
                  - !Sub 'arn:aws:bedrock-agentcore:${AWS::Region}:${AWS::AccountId}:workload-identity-directory/default/workload-identity/${AgentRuntimeName}-*'

  # ============================================
  # AgentCore Runtime
  # ============================================
  AgentRuntime:
    Type: AWS::BedrockAgentCore::Runtime
    Properties:
      AgentRuntimeName: !Ref AgentRuntimeName
      RoleArn: !GetAtt RuntimeRole.Arn
      NetworkConfiguration:
        NetworkMode: PUBLIC
      AgentRuntimeArtifact:
        ContainerConfiguration:
          ContainerUri: !Ref ImageUri

Outputs:
  AgentRuntimeArn:
    Description: AgentCore Runtime ARN
    Value: !GetAtt AgentRuntime.AgentRuntimeArn
    Export:
      Name: !Sub '${AWS::StackName}-AgentRuntimeArn'

  AgentRuntimeName:
    Description: AgentCore Runtime Name
    Value: !Ref AgentRuntime
    Export:
      Name: !Sub '${AWS::StackName}-AgentRuntimeName'

  RuntimeRoleArn:
    Description: Runtime IAM Role ARN
    Value: !GetAtt RuntimeRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-RuntimeRoleArn'