AWSTemplateFormatVersion: "2010-09-09"
Description: Batch (Fargate) - Extra Service

Metadata:

  AWS::CloudFormation::Interface:

    ParameterGroups:
      -
        Label:
          default: "Application Configuration"
        Parameters:
          - Application
          - Environment
          - Service
      -
        Label:
          default: "Batch Configuration"
        Parameters:
          - BatchComputeEnvironmentArn
          - BatchJobRoleArn
          - BatchJobExecutionRoleArn
      -
        Label:
          default: "Job Configuration"
        Parameters:
          - JobDefinitionImage
          - JobDefinitionCommand
          - JobDefinitionBucketOutputName

Parameters:

  Application:
    Type: String
    Default: myapp
    Description: Application Name

  Environment:
    Type: String
    Default: dev
    Description: Environment

  Service:
    Type: String
    Default: order
    Description: Service Name

  BatchComputeEnvironmentArn:
    Type: String
    Default: "arn:aws:batch:us-east-1:916902469227:compute-environment/BatchComputeEnvironment-Uq15Z9u80zeu4O55"
    Description: Compute Environment Arn

  BatchJobRoleArn:
    Type: String
    Default: "arn:aws:iam::916902469227:role/batch-fargate-BatchJobRole-Z7VTR3V5ZRMTP"
    Description: Batch Job Role Arn
  
  BatchJobExecutionRoleArn:
    Type: String
    Default: "arn:aws:iam::916902469227:role/batch-fargate-BatchJobExecutionRole-3IEW58IE4PQHT"
    Description: Batch Job Role Arn
  
  JobDefinitionImage:
    Description: Job Definition Image
    Type: String
    Default: "busybox"

  JobDefinitionCommand:
    Description: Job Definition Command
    Type: String
    Default: "echo fargate;"

  JobDefinitionBucketOutputName:
    Description: Job Definition Output Bucket Name
    Type: String
    Default: ""

Resources:

  BatchJobQueue:
    Type: AWS::Batch::JobQueue
    Properties:
      #JobQueueName: cfn-queue # (Optional)
      Priority: 1 # Job queues with a higher priority (or a higher integer value for the priority parameter) are evaluated first
      ComputeEnvironmentOrder:
        - Order: 1
          ComputeEnvironment: !Ref BatchComputeEnvironmentArn
      State: ENABLED # if the job queue state is DISABLED, new jobs can't be added to the queue, but jobs already in the queue can finish.
      Tags: { "Name": !Ref Service, "Application": !Ref Application, "Environment": !Ref Environment }

  BatchJobLogGroup:
    Type: "AWS::Logs::LogGroup"
    Properties:
      LogGroupName: !Sub "/batch/logs/batch-fargate/${Service}"
      RetentionInDays: 1
      Tags: 
        - Key: "Application"
          Value: !Ref Application
        - Key: "Environment"
          Value: !Ref Environment
        - Key: "Service"
          Value: !Ref Service

  BatchJobDefinition:
    Type: AWS::Batch::JobDefinition
    Properties:
      Type: container # container | multinode - multinode isn't supported for Fargate
      #JobDefinitionName: "JobDefinitionName" # (Optional)
      PlatformCapabilities: 
        - FARGATE
      Parameters: { "Service": !Ref Service }
      ContainerProperties:
        FargatePlatformConfiguration:
          PlatformVersion: LATEST
        Image: !Ref JobDefinitionImage
        Privileged: false # Must be false for Fargate
        ReadonlyRootFilesystem: false
        JobRoleArn: !Ref BatchJobRoleArn  # AM role that the container can assume for AWS permissions. 
        ExecutionRoleArn: !Ref BatchJobExecutionRoleArn  #execution role that AWS Batch can assume.
        #Memory: 1024 # This parameter is deprecated, use resourceRequirements to specify the memory requirements for the job definition.
        #Vcpus: 2 #Deprecated. For jobs running on EC2 resources, it specifies the number of vCPUs reserved for the job.
        ResourceRequirements:
          - Type: VCPU
            Value: 0.25
          - Type: MEMORY
            Value: 512
        Command: # ["echo","hi"]  ["sh","-c","echo fargate;"] ["sh","-c","echo fargate && ls && java -jar batch.jar"]
          - sh 
          - -c 
          - !Ref JobDefinitionCommand
        NetworkConfiguration:
          AssignPublicIp: DISABLED # DISABLED | ENABLED
        Environment:
          - Name: APP_ENV
            Value: !Ref Environment
          - Name: APP_SERVICE_NAME
            Value: !Ref Service
          - Name: APP_AWS_OUT_BUCKET_NAME
            Value: !Ref JobDefinitionBucketOutputName
        #Secrets:
        #  - Name: DB_URL
        #    ValueFrom: "/demo/database/endpoint"
        LogConfiguration:
          LogDriver: awslogs # Fargate resources are restricted to the awslogs and splunk log drivers.
          Options:
            awslogs-group: !Ref BatchJobLogGroup #/aws/batch/job
            awslogs-region: !Ref "AWS::Region"
            awslogs-stream-prefix: "my-batch"
          #SecretOptions:
          #  - Name: LOG_DB_URL
          #    ValueFrom: "/demo/database/endpoint" # ARN of Secret or SSM
      RetryStrategy:
        Attempts: 1
      Timeout:
        AttemptDurationSeconds: 60 #minimum value for the timeout is 60 seconds.

Outputs:

  BatchJobQueueArn:
    Value: !Ref BatchJobQueue

  BatchJobDefinitionArn:
    Value: !Ref BatchJobDefinition