AWSTemplateFormatVersion: "2010-09-09"
Description: Batch (Fargate)

Metadata:

  AWS::CloudFormation::Interface:

    ParameterGroups:
      -
        Label:
          default: "Application Configuration"
        Parameters:
          - Application
          - Environment
          - Service
      -
        Label:
          default: "Network Configuration"
        Parameters:
          - VpcId
          - VpcSubnetListCompute
      -
        Label:
          default: "Job Configuration"
        Parameters:
          - JobDefinitionImage
          - JobDefinitionCommand
          - JobDefinitionBucketOutputName
          - JobDefinitionResourceVcpu
          - JobDefinitionResourceMemory
          - JobDefinitionTimeoutSeconds

Parameters:

  Application:
    Type: String
    Default: myapp
    Description: Application Name

  Environment:
    Type: String
    Default: dev
    Description: Environment

  Service:
    Type: String
    Default: demo
    Description: Service Name

  VpcId:
    Description : "VPC ID"
    Type: AWS::EC2::VPC::Id

  VpcSubnetListCompute:
    Description: Private VpcSubnets for Web Servers
    Type: List<AWS::EC2::Subnet::Id>

  JobDefinitionImage:
    Description: Job Definition Image
    Type: String
    Default: "busybox"

  JobDefinitionCommand:
    Description: Job Definition Command
    Type: String
    Default: "echo fargate;"

  JobDefinitionBucketOutputName:
    Description: Job Definition Output Bucket Name
    Type: String
    Default: ""

  JobDefinitionResourceVcpu:
    Description: Job Definition Resource Requirement VCPU
    Type: Number
    Default: "0.25"
    
  JobDefinitionResourceMemory:
    Description: Job Definition Resource Requirement Memory
    Type: Number
    Default: "512"

  JobDefinitionTimeoutSeconds:
    Description: Job Definition Resource Timeout Seconds
    Type: Number
    Default: "1200"

Resources:

  BatchServiceRole:
    Type: "AWS::IAM::Role"
    Properties:
      #RoleName: !Sub "BatchServiceRole"
      Description: "Batch Service Role"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Action:
              - 'sts:AssumeRole'
            Effect: Allow
            Principal:
              Service: batch.amazonaws.com
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSBatchServiceRole
        #- arn:aws:iam::aws:policy/aws-service-role/BatchServiceRolePolicy
        - !Ref BatchServiceRolePolicy
      Path: "/" #/
      Tags:
        - Key: "Application"
          Value: !Ref Application
        - Key: "Environment"
          Value: !Ref Environment

  BatchServiceRolePolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      Description: "Batch Service Role ManagedPolicy"
      #ManagedPolicyName: "code-build-demo-policy"
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - 'logs:CreateLogGroup'
              - 'logs:CreateLogStream'
              - 'logs:PutLogEvents'
            Effect: Allow
            Resource: '*'
          - Action:
              - "s3:*"
            Effect: Allow
            Resource: '*'

  BatchComputeSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VpcId
      GroupDescription: "BatchComputeEnvironment (Fargate)"
      Tags:
        - Key: Name
          Value: !Sub "batch-fargate-sg"

  BatchComputeEnvironment:
    Type: "AWS::Batch::ComputeEnvironment"
    Properties:
      #ComputeEnvironmentName: cfn-env # (Optional)
      Type: MANAGED
      State: ENABLED
      ServiceRole: !GetAtt BatchServiceRole.Arn
      ComputeResources:
        Type: FARGATE #FARGATE or FARGATE_SPOT
        #MinvCpus: 0
        MaxvCpus: 8
        #DesiredvCpus: 0
        SecurityGroupIds:
          - !Ref BatchComputeSecurityGroup
        Subnets: !Ref VpcSubnetListCompute
        #InstanceRole: !GetAtt BatchComputeInstanceProfile.Arn #Needed if EC2
        #InstanceTypes:
        #  - optimal
        #Tags: {"Name": "Batch (Fargate) Compute Environment"} #tags is not applicable for Fargate

  BatchJobQueue:
    Type: AWS::Batch::JobQueue
    Properties:
      #JobQueueName: cfn-queue # (Optional)
      Priority: 1 # Job queues with a higher priority (or a higher integer value for the priority parameter) are evaluated first
      ComputeEnvironmentOrder:
        - Order: 1
          ComputeEnvironment: !Ref BatchComputeEnvironment
      State: ENABLED # if the job queue state is DISABLED, new jobs can't be added to the queue, but jobs already in the queue can finish.
      Tags: { "Name": "Batch Job Queue Fargate", "Application": !Ref Application, "Environment": !Ref Environment }

  BatchJobLogGroup:
    Type: "AWS::Logs::LogGroup"
    Properties:
      LogGroupName: !Sub "/batch/logs/batch-fargate/${Service}"
      RetentionInDays: 1
      Tags: 
        - Key: "Application"
          Value: !Ref Application
        - Key: "Environment"
          Value: !Ref Environment
        - Key: "Service"
          Value: !Ref Service

  BatchJobRole:
    Type: 'AWS::IAM::Role'
    Properties:
      #RoleName: !Sub "BatchInstanceRole"
      Description: !Sub "Batch Job Role (Fargate)"
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - 'sts:AssumeRole'
            Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
      ManagedPolicyArns:
        - !Ref BatchJobRolePolicy
        #- 'arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy'
        #- 'arn:aws:iam::aws:policy/AmazonElasticFileSystemFullAccess'
      Path: /
      Tags:
        - Key: "Application"
          Value: !Ref Application
        - Key: "Environment"
          Value: !Ref Environment

  BatchJobRolePolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      Description: "Batch Role ManagedPolicy"
      #ManagedPolicyName: "batch-job-role-policy"
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - 'logs:CreateLogGroup'
              - 'logs:CreateLogStream'
              - 'logs:PutLogEvents'
            Effect: Allow
            Resource: '*'
          - Action:
              - 's3:ListAllMyBuckets'
            Effect: Allow
            Resource: '*'
          - Action:
              - 's3:ListBucket'
              - "s3:GetBucketLocation"
            Effect: Allow
            Resource: '*'
          - Action:
              - 's3:GetObject'
              - 's3:PutObject'
              - 's3:GetObjectVersion'
            Effect: Allow
            Resource: "*"
            #Resource: !Sub "arn:aws:s3:::code-build-demo-bucket/*"
          - Action:
              - 'ecr:GetAuthorizationToken'
            Effect: Allow
            Resource: '*'
          - Action:
              - 'ecr:GetDownloadUrlForLayer'
              - 'ecr:BatchGetImage'
              - 'ecr:BatchCheckLayerAvailability'
              - 'ecr:PutImage'
              - 'ecr:InitiateLayerUpload'
              - 'ecr:UploadLayerPart'
              - 'ecr:CompleteLayerUpload'
            Effect: Allow
            Resource: !Sub "arn:aws:ecr:${AWS::Region}:${AWS::AccountId}:repository/code-image-repository-demo"
          - Action:
              - 'ecr:BatchGetImage'
              - 'ecr:GetDownloadUrlForLayer'
            Effect: Allow
            Resource: 
              - !Sub "arn:aws:ecr:${AWS::Region}:${AWS::AccountId}:repository/code-image-repository-cmn/*"
          - Action:
              - 'ssm:GetParameter'
              - 'ssm:GetParameters'
              - 'ssm:GetParametersByPath'
            Effect: Allow
            Resource: 
              - !Sub "arn:aws:ssm:*:${AWS::AccountId}:parameter/*"

  BatchJobExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      #RoleName: !Sub "BatchInstanceRole"
      Description: !Sub "Batch Job Execution Role (Fargate)"
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - 'sts:AssumeRole'
            Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
        - !Ref BatchJobExecutionRolePolicy
      Path: /
      Tags:
        - Key: "Application"
          Value: !Ref Application
        - Key: "Environment"
          Value: !Ref Environment

  BatchJobExecutionRolePolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      Description: "Batch Job Execution Role ManagedPolicy"
      #ManagedPolicyName: "batch-job-execution-role-policy"
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - 'ssm:GetParameter'
              - 'ssm:GetParameters'
              - 'ssm:GetParametersByPath'
            Effect: Allow
            Resource: 
              - !Sub "arn:aws:ssm:*:${AWS::AccountId}:parameter/*"
              
  BatchJobDefinition:
    Type: AWS::Batch::JobDefinition
    Properties:
      Type: container # container | multinode - multinode isn't supported for Fargate
      #JobDefinitionName: "JobDefinitionName" # (Optional)
      PlatformCapabilities: 
        - FARGATE
      Parameters: { "Service": !Ref Service }
      ContainerProperties:
        FargatePlatformConfiguration:
          PlatformVersion: LATEST
        Image: !Ref JobDefinitionImage
        Privileged: false # Must be false for Fargate
        ReadonlyRootFilesystem: false
        JobRoleArn: !GetAtt BatchJobRole.Arn  # AM role that the container can assume for AWS permissions. 
        ExecutionRoleArn: !GetAtt BatchJobExecutionRole.Arn #execution role that AWS Batch can assume.
        #Memory: 1024 # This parameter is deprecated, use resourceRequirements to specify the memory requirements for the job definition.
        #Vcpus: 2 #Deprecated. For jobs running on EC2 resources, it specifies the number of vCPUs reserved for the job.
        ResourceRequirements:
          - Type: VCPU
            Value: !Ref JobDefinitionResourceVcpu
          - Type: MEMORY
            Value: !Ref JobDefinitionResourceMemory
        Command: # ["echo","hi"]  ["sh","-c","echo fargate;"] ["sh","-c","echo fargate && ls && java -jar batch.jar"]
          - sh 
          - -c 
          - !Ref JobDefinitionCommand
        NetworkConfiguration:
          AssignPublicIp: DISABLED # DISABLED | ENABLED
        Environment:
          - Name: APP_ENV
            Value: !Ref Environment
          - Name: APP_SERVICE_NAME
            Value: !Ref Service
          - Name: APP_AWS_OUT_BUCKET_NAME
            Value: !Ref JobDefinitionBucketOutputName
        Secrets:
          - Name: DB_URL
            ValueFrom: "/demo/database/endpoint"
        LogConfiguration:
          LogDriver: awslogs # Fargate resources are restricted to the awslogs and splunk log drivers.
          Options:
            awslogs-group: !Ref BatchJobLogGroup #/aws/batch/job
            awslogs-region: !Ref "AWS::Region"
            awslogs-stream-prefix: "my-batch"
          SecretOptions:
            - Name: LOG_DB_URL
              ValueFrom: "/demo/database/endpoint" # ARN of Secret or SSM
      RetryStrategy:
        Attempts: 1
      Timeout:
        AttemptDurationSeconds: !Ref JobDefinitionTimeoutSeconds #minimum value for the timeout is 60 seconds.

Outputs:


  BatchServiceRoleArn:
    Value: !GetAtt BatchServiceRole.Arn

  BatchJobRoleArn:
    Value: !GetAtt BatchJobRole.Arn

  BatchJobExecutionRoleArn:
    Value: !GetAtt BatchJobExecutionRole.Arn


  BatchJobQueueArn:
    Value: !Ref BatchJobQueue

  BatchServiceRoleArn:
    Value: !Ref BatchServiceRole
