AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::LanguageExtensions
Description: LanguageExtensions

Parameters:

  InputText:
    Type: String
    Default: Text Value
    Description: "Text Value"

  InputList:
    Type: CommaDelimitedList
    Default: 1,2,3
    Description: "Comma Delimited Text"

Resources:

  DummyResourceRole: 
    Type: "AWS::IAM::Role"
    Properties: 
      Path: "/"
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Principal: 
              Service: 
                - "ec2.amazonaws.com"
            Action: 
              - "sts:AssumeRole"

Outputs:

  InputListLength:
    Value: 
      Fn::Length: !Ref InputList

  ObjectJsonString:
    Value: 
      Fn::ToJsonString: 
        Key1: !Sub "${InputText}-1"
        Key2: !Sub "${InputText}-2"

  ArrayJsonString:
    Value: 
      Fn::ToJsonString: 
        - Element1: !Sub "${InputText}-1"
          Element2: !Sub "${InputText}-2"
