AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::LanguageExtensions
Description: LanguageExtensions

Parameters:

  InputList:
    Type: CommaDelimitedList

Resources:

  DummyResourceRole: 
    Type: "AWS::IAM::Role"
    Properties: 
      Path: "/"
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Principal: 
              Service: 
                - "ec2.amazonaws.com"
            Action: 
              - "sts:AssumeRole"

Outputs:

  InputListLength:
    Value: 
      Fn::Length: !Ref InputList

  

