AWSTemplateFormatVersion: "2010-09-09"
Description: Pseudo parameters

Parameters:

  InputText:
    Type: String
    Default: Text Value
    Description: "Text Value"

Conditions:

  IsInputTextProduction: !Equals 
    - !Ref InputText
    - prd

  IsInputTextNotEmpty: !Not 
    - !Equals 
      - !Ref InputText
      - ''

Resources:

  ResourceExample:
    Type: AWS::IAM::Role
    Properties:
      Description:
        Fn::If:
          - IsInputTextNotEmpty
          - !Ref InputText
          - !Ref AWS::NoValue      
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - 'sts:AssumeRole'
            Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com      
      Path: /
      Tags:
        - Key: "Region"
          Value: !Sub "${AWS::Region}"
        - Key: "AccountId"
          Value: !Sub "${AWS::AccountId}"


Outputs:

  OutResourceExample:
    Value: !Ref ResourceExample
                    