AWSTemplateFormatVersion: "2010-09-09"
Description: A sample template

Mappings: 
  RegionMap: 
    us-east-1: 
      "HVM64": "ami-0ff8a91507f77f867"
    us-west-1: 
      "HVM64": "ami-0bdb828fd58c52235"
    eu-west-1: 
      "HVM64": "ami-047bb4163c506cd98"
    ap-southeast-1: 
      "HVM64": "ami-08569b978cc4dfa10"
    ap-northeast-1: 
      "HVM64": "ami-06cd52961ce9f0d85"
      
Parameters:

  InstanceTypeParameter:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - m1.small
      - m1.large
    Description: Enter t2.micro, m1.small, or m1.large. Default is t2.micro.
    
Resources:

  ResourceExample:
    Type: AWS::IAM::Role
    Properties:
      #RoleName: !Sub "code-build-demo-role"
      Description: !Sub "CodeBuild Role"
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - 'sts:AssumeRole'
            Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com      
      Path: /
      Tags:
        - Key: "DynamicSsmLatest"
          Value: !Sub "{{resolve:ssm:/demo/database/name}}"
        - Key: "DynamicSsmVersion"
          Value: !Sub "{{resolve:ssm:/demo/database/name:1}}"
        - Key: "MappingsValue"
          Value: !FindInMap [RegionMap, !Ref "AWS::Region", HVM64]

Outputs:

  ResourceExampleRef:
    Value: !Ref ResourceExample
