AWSTemplateFormatVersion: "2010-09-09"
Description: Pseudo parameters

    
Resources:

  ResourceExample:
    Type: AWS::IAM::Role
    Properties:
      Description: !Sub "Example Resource Role"
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - 'sts:AssumeRole'
            Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com      
      Path: /
      Tags:
        - Key: "Region"
          Value: !Sub "${AWS::Region}"



