AWSTemplateFormatVersion: "2010-09-09"
Description: A sample template

Parameters:

  InstanceTypeParameter:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - m1.small
      - m1.large
    Description: Enter t2.micro, m1.small, or m1.large. Default is t2.micro.
    
Resources:

  ResourceExample:
    Type: AWS::IAM::Role
    Properties:
      #RoleName: !Sub "code-build-demo-role"
      Description: !Sub "CodeBuild Role"
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - 'sts:AssumeRole'
            Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com      
      Path: /
      Tags:
        - Key: "DynamicSsmLatest"
          Value: !Sub "{{resolve:ssm:/demo/database/name}}"
        - Key: "DynamicSsmVersion"
          Value: !Sub "{{resolve:ssm:/demo/database/name:1}}"              