AWSTemplateFormatVersion: 2010-09-09
Description: CloudFront S3 Bucket Origin (Origin Access Control)

Parameters:

  CloudFrontDistributionId:
    Type: String
    Description: "CloudFrontDistributionId"
    Default: "E1521E835ZN7KD"

  CloudFrontOriginAccessControlName:
    Type: String
    Description: "CloudFrontOriginAccessControlName"
    Default: "S3OAC"

Resources:

  Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      #BucketName: !Ref BucketName
      AccessControl: "Private" # Private, PublicRead, PublicReadWrite, AuthenticatedRead, LogDeliveryWrite, BucketOwnerRead, BucketOwnerFullControl, or AwsExecRead.
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        IgnorePublicAcls: True
        BlockPublicPolicy: True
        RestrictPublicBuckets: True
      VersioningConfiguration:
         Status: Suspended
      BucketEncryption: # SSE-KMS (CMK)
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256 #AES256 | aws:kms
            BucketKeyEnabled: true
      Tags:
        - Key: "Name"
          Value: "cloudfront-s3-oac-origin"
        - Key: "Version"
          Value: "20221007"

  CloudFrontOriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties: 
      OriginAccessControlConfig: 
        Description: S3 Origin Access Control
        Name: !Ref CloudFrontOriginAccessControlName
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  BucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket: !Ref Bucket
      PolicyDocument:
        Statement:
        - Action: "s3:GetObject"
          Effect: Allow
          Resource: !Sub "arn:aws:s3:::${Bucket}/*"
          Principal:
            Service: "cloudfront.amazonaws.com"
          Condition:
            "ForAnyValue:StringEquals":
              AWS:SourceArn: 
                - !Sub "arn:aws:cloudfront::${AWS::AccountId}:distribution/${CloudFrontDistributionId}"
                - !Sub "arn:aws:cloudfront::${AWS::AccountId}:distribution/E85IID7DAFXTMY"

Outputs:

  BucketDomainName:
    Description: S3 Bucket DomainName
    Value: !Sub "${Bucket.DomainName}"

  CloudFrontOriginAccessControlId:
    Description: CloudFrontOriginAccessControl ID
    Value: !GetAtt CloudFrontOriginAccessControl.Id