AWSTemplateFormatVersion: '2010-09-09'
Description: Cloudfront Signed Cookies

Resources:

  ## Signer (Optional)
  
  
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      #RoleName: "cloudfront-lambda-origin-role"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
              - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AWSXrayWriteOnlyAccess

  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      #FunctionName : "basic-lambda-python"
      Description: "Basic Lambda Python"
      Runtime: python3.9
      Role: !GetAtt LambdaExecutionRole.Arn
      Handler: index.handler
      Environment:
        Variables:
          COOKIE_KEYPAIR: CloudFront-Key-Pair-Id=foo; Path=/
          COOKIE_POLICY: CloudFront-Policy=foo; Path=/
          COOKIE_SIGNATURE: CloudFront-Signature=foo; Path=/
      Code:
        ZipFile: |
            import json
            import boto3
            import os
            def handler(event, context):
              COOKIE_KEYPAIR = os.environ['COOKIE_KEYPAIR']
              COOKIE_POLICY = os.environ['COOKIE_POLICY']
              COOKIE_SIGNATURE = os.environ['COOKIE_SIGNATURE']
              return { 'statusCode': 200, 'body': "<html><div><b>V3</b></div></html>",  "headers": { "Content-Type": "text/html" }, "cookies": [ COOKIE_KEYPAIR, COOKIE_POLICY, COOKIE_SIGNATURE ] }
      TracingConfig:
        Mode: "Active"
      Tags:
        - Key: "Name"
          Value: "cloudfront-signer"

  LambdaUrl:
    Type: AWS::Lambda::Url
    Properties:
      TargetFunctionArn: !Ref LambdaFunction
      #Qualifier: dev # The alias name.
      AuthType: NONE
      Cors:
        AllowOrigins:
          - "https://*"

  LambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      #FunctionName: !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${LambdaFunction}"
      FunctionName: !GetAtt LambdaFunction.Arn
      FunctionUrlAuthType: NONE
      Action: lambda:InvokeFunctionUrl
      Principal: "*"

  LambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${LambdaFunction}"
      RetentionInDays: 1
      
  ##

  Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      #BucketName: !Ref BucketName
      AccessControl: "Private" # Private, PublicRead, PublicReadWrite, AuthenticatedRead, LogDeliveryWrite, BucketOwnerRead, BucketOwnerFullControl, or AwsExecRead.
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        IgnorePublicAcls: True
        BlockPublicPolicy: True
        RestrictPublicBuckets: True
      VersioningConfiguration:
         Status: Suspended
      BucketEncryption: # SSE-KMS (CMK)
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256 #AES256 | aws:kms
            BucketKeyEnabled: true
      Tags:
        - Key: "Name"
          Value: "cloudfront-s3-oac-origin"
        - Key: "Version"
          Value: "20221007"

  OriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Description: 'OAC'
        #Name: {origin access contlor name}
        Name: "OAC"
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    DependsOn:
      - CloudFrontKeyGroup
    Properties:
      DistributionConfig:
        Enabled: true
        PriceClass: PriceClass_100
        HttpVersion: http2
        IPV6Enabled: false
        Comment: !Sub Distribution with S3 Bucket (OAI)
        Origins:
          - DomainName: !GetAtt Bucket.RegionalDomainName
            Id: oac-test-bucket
            OriginAccessControlId: !GetAtt OriginAccessControl.Id
            S3OriginConfig: {}
          - DomainName: !Select [2, !Split ["/", !GetAtt LambdaUrl.FunctionUrl]]
            Id: LambdaOrigin
            ConnectionAttempts: 3
            ConnectionTimeout: 10
            CustomOriginConfig:
              HTTPSPort: 443
              OriginProtocolPolicy: https-only #http-only | https-only | match-viewer
              OriginKeepaliveTimeout: 5
              OriginReadTimeout: 30
            OriginCustomHeaders:
              - HeaderName: c_security
                HeaderValue: secret
        CacheBehaviors:
          - PathPattern: /secure/*
            AllowedMethods:
              - GET
              - HEAD
            TargetOriginId: oac-test-bucket
            ViewerProtocolPolicy: redirect-to-https
            #CachePolicyId: !Ref 'CloudFrontStaticCachePolicy'
            Compress: true
            ForwardedValues:
              Cookies:
                Forward: none #all | none | whitelist
              QueryString: false
            TrustedKeyGroups: # When a cache behavior contains trusted key groups, CloudFront requires signed URLs or signed cookies for all requests that match the cache behavior.
              - !Ref 'CloudFrontKeyGroup'
          - PathPattern: "/sign/*"
            AllowedMethods:
            - GET
            - HEAD
            DefaultTTL: 900
            MaxTTL: 900
            MinTTL: 900
            ForwardedValues:
              Cookies:
                Forward: all #all | none | whitelist
              QueryString: false
            TargetOriginId: LambdaOrigin
            ViewerProtocolPolicy: redirect-to-https
            Compress: true
        DefaultCacheBehavior:
          ForwardedValues:
              QueryString: 'false'
              Cookies:
                Forward: none
          TargetOriginId: oac-test-bucket
          ViewerProtocolPolicy: redirect-to-https #ViewerProtocolPolicy: allow-all
        ViewerCertificate:
          CloudFrontDefaultCertificate: true
        #ViewerCertificate:
        #  SslSupportMethod: sni-only
        #  MinimumProtocolVersion: TLSv1.1_2016
        #  AcmCertificateArn: !Sub "arn:aws:acm:us-east-1:${AWS::AccountId}:certificate/${CertificateID}"
      Tags:
        - Key: "management"
          Value: "manual"

  BucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket: !Ref Bucket
      PolicyDocument:
        Statement:
        - Action: "s3:GetObject"
          Effect: Allow
          Resource: !Sub "arn:aws:s3:::${Bucket}/*"
          Principal:
            Service: cloudfront.amazonaws.com
          Condition:
            "ForAnyValue:StringEquals":
              AWS:SourceArn: 
                - !Sub "arn:aws:cloudfront::${AWS::AccountId}:distribution/${CloudFrontDistribution}"

##

  CloudFrontPublicKey:
    Type: AWS::CloudFront::PublicKey
    Properties:
      PublicKeyConfig:
        Name: "cfn-public-key"
        Comment: cfn-example signed public key
        CallerReference: "20230208000512.523756"
        EncodedKey: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0ZCz4OoFhfPm38JraZKT
          85GRaxS2mfZC2IWfatpzirsBb7vX1HIVyEhE7uiLAyftO6Y0xj9HzKQFkzuIl9iD
          oI69MovHGtb+BM5f4VnN4Srf2CkWgpF5jqwf8jRTpvKkoKyNGABWCTIYIbJrt0JM
          xIg5xt4UFa7ARGxiMejqOwvlf2dwtmwEaNvdZGxCpnDQ9cpKUvlxzs6sn+KclsR3
          WhRQPueY5nfy0C+ICyzwXSc+yUharjtuyFYbh5WKgrFcXRgixKzHVaIhAaaAkuA6
          z9cn/AbbTO4NzhP/pKwyw0dm1E0RkOkCprEVLWvWA9bgxYLQRoO1ii0khtUtBZ6Z
          PwIDAQAB
          -----END PUBLIC KEY-----

  CloudFrontKeyGroup:
    Type: AWS::CloudFront::KeyGroup
    DependsOn:
      - CloudFrontPublicKey
    Properties:
      KeyGroupConfig:
        Name: "cfn-public-key-group-config"
        Comment: cfn-example signed key group
        Items:
          - !Ref 'CloudFrontPublicKey'

Outputs:

  BucketDomainName:
    Description: S3 Bucket DomainName
    Value: !Sub "${Bucket.DomainName}"
    
  CloudFrontDistributionUrl:
    Description: CloudFrontDistributionUrl 
    Value: !Sub "https://${CloudFrontDistribution.DomainName}"

  LambdaFunctionUrl:
    Value: !GetAtt LambdaUrl.FunctionUrl