AWSTemplateFormatVersion: 2010-09-09
Description: CloudFront S3 Bucket origin

#Parameters:

#  BucketName:
#    Type: String

Resources:

  Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      #BucketName: !Ref BucketName
      AccessControl: PublicRead
      VersioningConfiguration:
         Status: Suspended
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html

  BucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket: !Ref Bucket
      PolicyDocument:
        Statement:
        - Action: "s3:GetObject"
          Effect: Allow
          Resource: !Sub "arn:aws:s3:::${Bucket}/*"
          Principal: '*'

Outputs:

  BucketWebsiteUrl:
    Description: S3 Bucket WebSite URL
    Value: !Sub "${Bucket.WebsiteURL}"
