AWSTemplateFormatVersion: 2010-09-09
Description: CloudFront S3 Bucket origin (Origin Access Identifier)

#Parameters:

#  BucketName:
#    Type: String

Resources:

  Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      #BucketName: !Ref BucketName
      AccessControl: Private
      VersioningConfiguration:
         Status: Suspended
      #BucketEncryption: # SSE-KMS (CMK)
      #  ServerSideEncryptionConfiguration:
      #    - ServerSideEncryptionByDefault:
      #        SSEAlgorithm: 'aws:kms' #AES256 | aws:kms
      #WebsiteConfiguration:
      #  IndexDocument: index.html
      #  ErrorDocument: index.html
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - '*'
            AllowedMethods:
              - GET
              - HEAD
            AllowedOrigins:
              - '*'
            #ExposedHeaders:
            #  - '*' - ExposeHeader "*" contains wildcard. We currently do not support wildcard for ExposeHeader.
            Id: cors-rule-1
            MaxAge: 3600        
      Tags:
        - Key: "Name"
          Value: "cloudfront-s3-oai-origin"

  CloudFrontOriginAccessIdentity:
    Type: "AWS::CloudFront::CloudFrontOriginAccessIdentity"
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub "access-identity-${Bucket}"

  BucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket: !Ref Bucket
      PolicyDocument:
        Statement:
        - Action: "s3:GetObject"
          Effect: Allow
          Resource: !Sub "arn:aws:s3:::${Bucket}/*"
          Principal:
            CanonicalUser: !GetAtt CloudFrontOriginAccessIdentity.S3CanonicalUserId



Outputs:

  BucketDomainName:
    Description: S3 Bucket DomainName
    Value: !Sub "${Bucket.DomainName}"

  CloudFrontOriginAccessIdentityId:
    Description: CloudFrontOriginAccessIdentity ID
    Value: !Sub "${CloudFrontOriginAccessIdentity}"
