AWSTemplateFormatVersion: '2010-09-09'
Description: Cloudfront Signed Cookies

Resources:

  Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      #BucketName: !Ref BucketName
      AccessControl: "Private" # Private, PublicRead, PublicReadWrite, AuthenticatedRead, LogDeliveryWrite, BucketOwnerRead, BucketOwnerFullControl, or AwsExecRead.
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        IgnorePublicAcls: True
        BlockPublicPolicy: True
        RestrictPublicBuckets: True
      VersioningConfiguration:
         Status: Suspended
      BucketEncryption: # SSE-KMS (CMK)
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256 #AES256 | aws:kms
            BucketKeyEnabled: true
      Tags:
        - Key: "Name"
          Value: "cloudfront-s3-oac-origin"
        - Key: "Version"
          Value: "20221007"

  OriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Description: 'OAC'
        #Name: {origin access contlor name}
        Name: "OAC"
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        PriceClass: PriceClass_100
        HttpVersion: http2
        IPV6Enabled: false
        Comment: !Sub Distribution with S3 Bucket (OAI)
        Origins:
          - DomainName: !GetAtt Bucket.RegionalDomainName
            Id: oac-test-bucket
            OriginAccessControlId: !GetAtt OriginAccessControl.Id
            S3OriginConfig: {}
        DefaultCacheBehavior:
          ForwardedValues:
              QueryString: 'false'
              Cookies:
                Forward: none
          TargetOriginId: oac-test-bucket
          ViewerProtocolPolicy: redirect-to-https #ViewerProtocolPolicy: allow-all
        ViewerCertificate:
          CloudFrontDefaultCertificate: true
        #ViewerCertificate:
        #  SslSupportMethod: sni-only
        #  MinimumProtocolVersion: TLSv1.1_2016
        #  AcmCertificateArn: !Sub "arn:aws:acm:us-east-1:${AWS::AccountId}:certificate/${CertificateID}"
      Tags:
        - Key: "management"
          Value: "manual"

  BucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket: !Ref Bucket
      PolicyDocument:
        Statement:
        - Action: "s3:GetObject"
          Effect: Allow
          Resource: !Sub "arn:aws:s3:::${Bucket}/*"
          Principal:
            Service: cloudfront.amazonaws.com
          Condition:
            "ForAnyValue:StringEquals":
              AWS:SourceArn: 
                - !Sub "arn:aws:cloudfront::${AWS::AccountId}:distribution/${CloudFrontDistribution}"

Outputs:

  BucketDomainName:
    Description: S3 Bucket DomainName
    Value: !Sub "${Bucket.DomainName}"