AWSTemplateFormatVersion: 2010-09-09
Description: CloudFront S3 Bucket Origin

Resources:

  Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      #BucketName: !Ref BucketName
      AccessControl: PublicRead
      VersioningConfiguration:
         Status: Suspended
      BucketEncryption: # SSE-KMS (CMK)
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256 #AES256 | aws:kms
            BucketKeyEnabled: true
      Tags:
        - Key: "Name"
          Value: "cloudfront-s3-origin"

  BucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket: !Ref Bucket
      PolicyDocument:
        Statement:
        - Action: "s3:GetObject"
          Effect: Allow
          Resource: !Sub "arn:aws:s3:::${Bucket}/*"
          Principal: '*'

Outputs:

  BucketDomainName:
    Description: S3 Bucket DomainName
    Value: !Sub "${Bucket.DomainName}"
