AWSTemplateFormatVersion: "2010-09-09"
Description: SQS FIFO Queue - Normal Throughput (DeduplicationScope=queue, FifoThroughputLimit=perQueue)

Resources:

  FifoQueue: 
    Type: AWS::SQS::Queue
    Properties: 
       FifoQueue: true
       QueueName: sqs-queue-fifo.fifo
       VisibilityTimeout: 30
       #MaximumMessageSize: 262144
       #DelaySeconds: 0
       MessageRetentionPeriod: 345600
       ReceiveMessageWaitTimeSeconds: 20
       KmsMasterKeyId: alias/aws/sqs # AWS managed CMK for Amazon SQS
       KmsDataKeyReusePeriodSeconds: 3600 # 60 (1 minute) and 86,400 (24 hours). The default is 300 (5 minutes)
       RedriveAllowPolicy:
         redrivePermission: allowAll
       ContentBasedDeduplication: true # For first-in-first-out (FIFO) queues, specifies whether to enable content-based deduplication.
       DeduplicationScope: queue # messageGroup | queue # whether message deduplication occurs at the message group or queue level
       FifoThroughputLimit: perQueue # perMessageGroupId | perQueue # whether the FIFO queue throughput quota applies to the entire queue or per message group 
       Tags:
         -
            Key: env
            Value: test

Outputs:

  FifoQueueArn: 
    Description: "ARN of queue"
    Value: !GetAtt FifoQueue.Arn

  FifoQueueUrl: 
    Description: "URL of queue"
    Value: !Ref FifoQueue
