AWSTemplateFormatVersion: "2010-09-09"
Description: SQS Standard Queue with Dead Letter Queue

Resources:

  StandardQueue: 
    Type: AWS::SQS::Queue
    Properties: 
       QueueName: sqs-queue-deadletter
       VisibilityTimeout: 30
       RedrivePolicy: 
         deadLetterTargetArn: !GetAtt StandardQueueDeadLetter.Arn
         maxReceiveCount: 5
       Tags:
         -
            Key: env
            Value: test

  StandardQueueDeadLetter: 
    Type: AWS::SQS::Queue
    Properties: 
       QueueName: sqs-queue-deadletter-dlq
       Tags:
         -
            Key: env
            Value: test

Outputs:

  StandardQueueArn: 
    Description: "ARN of queue"
    Value: !GetAtt StandardQueue.Arn

  StandardQueueDeadLetterArn: 
    Description: "ARN of dead-letter queue"
    Value: !GetAtt StandardQueueDeadLetter.Arn
