AWSTemplateFormatVersion: "2010-09-09"
Description: SQS Standard Queue

Resources:

  StandardQueue: 
    Type: AWS::SQS::Queue
    Properties: 
       QueueName: sqs-queue-standard
       VisibilityTimeout: 30
       Tags:
         -
            Key: env
            Value: test
  
  # Required if you need to permit other accounts to access the queue
  StandardQueuePolicy: 
    Type: AWS::SQS::QueuePolicy
    Properties: 
      Queues: 
        - !Ref StandardQueue
      PolicyDocument: 
        Statement: 
          - 
            Action: 
              - "SQS:SendMessage" 
              - "SQS:ReceiveMessage"
            Effect: "Allow"
            Resource: !GetAtt StandardQueue.Arn
            Principal:  
              AWS: 
                - !Sub "${AWS::AccountId}"

Outputs:

  StandardQueueArn: 
    Description: "ARN of queue"
    Value: !GetAtt StandardQueue.Arn

  StandardQueueUrl: 
    Description: "URL of queue"
    Value: !Ref StandardQueue
