AWSTemplateFormatVersion: "2010-09-09"

Resources: 
  StandardQueue: 
    Type: AWS::SQS::Queue
    Properties: 
       QueueName: standard-queue

Outputs: 
  StandardQueueARN: 
    Description: "ARN of queue"
    Value: !GetAtt StandardQueue.Arn
