AWSTemplateFormatVersion: "2010-09-09"
Description: SQS Standard Queue

Resources:

  StandardQueue: 
    Type: AWS::SQS::Queue
    Properties: 
       #FifoQueue: false
       QueueName: sqs-queue-standard
       VisibilityTimeout: 30
       #MaximumMessageSize: 262144 # 1,024 bytes (1 KiB) to 262,144 bytes (256 KiB)
       #DelaySeconds: 0
       MessageRetentionPeriod: 43200 #60 seconds (1 minute) to 1,209,600 seconds (14 days), default value is 345,600 seconds (4 days)
       ReceiveMessageWaitTimeSeconds: 20 # Long Polling
       KmsMasterKeyId: alias/aws/sqs # AWS managed CMK for Amazon SQS
       KmsDataKeyReusePeriodSeconds: 3600 # 60 (1 minute) and 86,400 (24 hours). The default is 300 (5 minutes)
       RedriveAllowPolicy:
         redrivePermission: allowAll
       Tags:
         -
            Key: env
            Value: test
  
  # Required if you need to permit other accounts to access the queue
  StandardQueuePolicy: 
    Type: AWS::SQS::QueuePolicy
    Properties: 
      Queues: 
        - !Ref StandardQueue
      PolicyDocument: 
        Statement: 
          - 
            Action: 
              - "SQS:SendMessage" 
              - "SQS:ReceiveMessage"
            Effect: "Allow"
            Resource: !GetAtt StandardQueue.Arn
            Principal:  
              AWS: 
                - !Sub "${AWS::AccountId}"

Outputs:

  StandardQueueArn: 
    Description: "ARN of queue"
    Value: !GetAtt StandardQueue.Arn

  StandardQueueUrl: 
    Description: "URL of queue"
    Value: !Ref StandardQueue
