AWSTemplateFormatVersion: "2010-09-09"

Resources:

  StandardQueue: 
    Type: AWS::SQS::Queue
    Properties: 
       QueueName: sqs-queue-standard
       VisibilityTimeout: 30
       Tags:
         -
            Key: env
            Value: test
Outputs:

  StandardQueueARN: 
    Description: "ARN of queue"
    Value: !GetAtt StandardQueue.Arn
