---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'VPC with Public Subnets only and spans 3 Availability Zones'

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: "Application Configuration"
        Parameters:
          - Application
          - Environment
      -
        Label:
          default: "Network Configuration"
        Parameters:
          - VpcBlock
          - PublicSubnet01Block
          - PublicSubnet02Block
          - PublicSubnet03Block
          
Parameters:

  Application:
    Type: String
    Default: myapp
    Description: Application Name
    
  Environment:
    Type: String
    Default: dev
    Description: Environment

  VpcBlock:
    Type: String
    Default: 10.0.0.0/16
    Description: The CIDR range for the VPC. This should be a valid private (RFC 1918) CIDR range.

  PublicSubnet01Block:
    Type: String
    Default: 10.0.128.0/24
    Description: CidrBlock for public subnet 01 within the VPC

  PublicSubnet02Block:
    Type: String
    Default: 10.0.144.0/24
    Description: CidrBlock for public subnet 02 within the VPC

  PublicSubnet03Block:
    Type: String
    Default: 10.0.160.0/24
    Description: CidrBlock for public subnet 03 within the VPC

Resources:

  VPC:
    Type: "AWS::EC2::VPC"
    Properties:
      CidrBlock: !Ref VpcBlock
      EnableDnsSupport: true
      EnableDnsHostnames: true
      InstanceTenancy: "default"
      Tags:
      - Key: Name
        Value: !Sub "${Application}-${Environment}-vpc"

  VPCIpv6CidrBlock:
      Type: AWS::EC2::VPCCidrBlock
      Properties:
        VpcId: !Ref VPC
        AmazonProvidedIpv6CidrBlock: true

  InternetGateway:
    Type: "AWS::EC2::InternetGateway"
    Properties:
      Tags:
      - Key: Name
        Value: !Sub "${Application}-${Environment}-igw"

  VPCGatewayAttachment:
    Type: "AWS::EC2::VPCGatewayAttachment"
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  PublicRouteTable:
    Type: "AWS::EC2::RouteTable"
    Properties:
      VpcId: !Ref VPC
      Tags:
      - Key: Description
        Value: Public Subnet Route Table
      - Key: Network
        Value: Public
      - Key: Name
        Value: !Sub "${Application}-${Environment}-rt-public"

  PublicRoute:
    Type: "AWS::EC2::Route"
    DependsOn: VPCGatewayAttachment
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  PublicRouteIpv6:
      Type: AWS::EC2::Route
      DependsOn: [VPCGatewayAttachment, VPCIpv6CidrBlock]
      Properties:
        RouteTableId: !Ref PublicRouteTable
        DestinationIpv6CidrBlock: "::/0"
        GatewayId: !Ref InternetGateway
        
  PublicSubnet01:
    Type: AWS::EC2::Subnet
    DependsOn: VPCIpv6CidrBlock
    Metadata:
      Comment: Public Subnet 01
    Properties:
      VpcId: !Ref VPC
      MapPublicIpOnLaunch: true
      AvailabilityZone:
        Fn::Select:
        - 0
        - Fn::GetAZs:
            Ref: AWS::Region
      CidrBlock:
        Ref: PublicSubnet01Block
      AssignIpv6AddressOnCreation: true
      Ipv6CidrBlock: 
        Fn::Select: 
          - 0
          - Fn::Cidr: 
              - !Select [ 0, !GetAtt VPC.Ipv6CidrBlocks ]
              - 256 
              - 64
      Tags:
      - Key: Name
        Value: !Sub "${Application}-${Environment}-vpc-subnet-public-1"

  PublicSubnet02:
    Type: AWS::EC2::Subnet
    DependsOn: VPCIpv6CidrBlock
    Metadata:
      Comment: Public Subnet 02
    Properties:
      VpcId: !Ref VPC
      MapPublicIpOnLaunch: true
      AvailabilityZone:
        Fn::Select:
        - 1
        - Fn::GetAZs:
            Ref: AWS::Region
      CidrBlock:
        Ref: PublicSubnet02Block
      AssignIpv6AddressOnCreation: true
      Ipv6CidrBlock: 
        Fn::Select: 
          - 1
          - Fn::Cidr: 
              - !Select [ 0, !GetAtt VPC.Ipv6CidrBlocks ]
              - 256 
              - 64
      Tags:
      - Key: Name
        Value: !Sub "${Application}-${Environment}-vpc-subnet-public-2"

  PublicSubnet03:
    Type: AWS::EC2::Subnet
    DependsOn: VPCIpv6CidrBlock
    Metadata:
      Comment: Public Subnet 03
    Properties:
      VpcId: !Ref VPC
      MapPublicIpOnLaunch: true
      AvailabilityZone:
        Fn::Select:
        - 2
        - Fn::GetAZs:
            Ref: AWS::Region
      CidrBlock:
        Ref: PublicSubnet03Block
      AssignIpv6AddressOnCreation: true
      Ipv6CidrBlock: 
        Fn::Select: 
          - 2
          - Fn::Cidr: 
              - !Select [ 0, !GetAtt VPC.Ipv6CidrBlocks ]
              - 256 
              - 64
      Tags:
      - Key: Name
        Value: !Sub "${Application}-${Environment}-vpc-subnet-public-3"

      
  PublicSubnet01RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet01
      RouteTableId: !Ref PublicRouteTable

  PublicSubnet02RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet02
      RouteTableId: !Ref PublicRouteTable

  PublicSubnet03RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet03
      RouteTableId: !Ref PublicRouteTable

Outputs:

  VpcId:
    Description: VPC ID
    Value: !Ref "VPC"

  VpcDefaultNetworkAcl:
    Description: The ID of the default network ACL for the VPC.
    Value: !GetAtt VPC.DefaultNetworkAcl

  VpcDefaultSecurityGroup:
    Description: The ID of the default security group for the VPC. 
    Value: !GetAtt VPC.DefaultSecurityGroup

  PublicSubnet01Id:
    Description: Public Subnet 1 ID
    Value: !Ref PublicSubnet01

  PublicSubnet02Id:
    Description: Public Subnet 2 ID
    Value: !Ref PublicSubnet02

  PublicSubnet03Id:
    Description: Public Subnet 3 ID
    Value: !Ref PublicSubnet03

##
  VpcIpv6CidrBlock:
    Description: The IPv6 CIDR block associated with the VPC
    Value: !Select [ 0, !GetAtt VPC.Ipv6CidrBlocks ] # Example value: 2600:1f16:844:9c00::/56  (not /64)

  PublicSubnet01Ipv6CidrBlock:
    Description: Public Subnet 1 IPv6 CIDR
    Value: !Select [ 0, !GetAtt PublicSubnet01.Ipv6CidrBlocks ] # Example value: 2600:1f16:844:9c00::/64

  PublicSubnet02Ipv6CidrBlock:
    Description: Public Subnet 2 IPv6 CIDR
    Value: !Select [ 0, !GetAtt PublicSubnet02.Ipv6CidrBlocks ] # Example value: 2600:1f16:844:9c01::/64

  PublicSubnet03Ipv6CidrBlock:
    Description: Public Subnet 3 IPv6 CIDR
    Value: !Select [ 0, !GetAtt PublicSubnet03.Ipv6CidrBlocks ] # Example value: 2600:1f16:844:9c02::/64