AWSTemplateFormatVersion: "2010-09-09"
Description: IAM - Access Analyzer

Resources:

  Analyzer:
    Type: AWS::AccessAnalyzer::Analyzer
    Properties:
      #AnalyzerName: MyAccountAnalyzer
      Type: ACCOUNT
      ArchiveRules:
        -
          # Archive findings for a trusted AWS account
          RuleName: ArchiveTrustedAccountAccess
          Filter:
            -
              Property: 'principal.AWS'
              Eq:
                - '5057435343'
            - Property: isPublic
              Eq:
                - false
      Tags:
        -
          Key: Kind
          Value: Dev

Outputs:

  AnalyzerArn:
    Value: !Ref Analyzer
