AWSTemplateFormatVersion: "2010-09-09"
Description: CloudWatch

Resources:

  CloudWatchAlarmSnsTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: "Cloudwatch Alarm Topic"
      Tags:
        -
          Key: "Name"
          Value: "cloudwatch-alarm-topic"

  CloudWatchAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: true
      #AlarmName: "MyCloudWatchAlarm"
      AlarmDescription: "CloudWatch Alarm"
      Namespace: MyNamespace
      MetricName: ErrorCount
      Dimensions:
        - Name: InstanceId
          Value: "1662602716588"
      AlarmActions:
        - !Ref CloudWatchAlarmSnsTopic
      OKActions:
        - !Ref CloudWatchAlarmSnsTopic
      InsufficientDataActions:
        - !Ref CloudWatchAlarmSnsTopic
      Statistic: Average #Average | Maximum | Minimum | SampleCount | Sum
      Period: 60 #10, 30, 60, and any multiple of 60
      DatapointsToAlarm: 10
      EvaluationPeriods: 10
      Threshold: 5
      TreatMissingData: ignore  # breaching, notBreaching, ignore, and missing
      ComparisonOperator: GreaterThanOrEqualToThreshold

Outputs:

  CloudWatchAlarmArn:
    Description: CloudWatch Alarm Arn
    Value: !GetAtt CloudWatchAlarm.Arn