AWSTemplateFormatVersion: "2010-09-09"
Description: Cloudwatch - Log Group

Parameters:

  LogGroupName:
    Type: "String"
    Default: "logs/my-log-group"
    Description: "Log Group name"

  KmsKeyId:
    Type: "String"
    Default: "my-key-alias"
    Description: "KMS Key ID"


Resources:

  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties: 
      KmsKeyId: !Ref KmsKeyId # Key Policy must give kms permissions to "Service": "logs.<region>.amazonaws.com"
      LogGroupName: !Ref LogGroupName
      RetentionInDays: 3
      Tags:
        - Key: Environment
          Value: dev
        - Key: Application
          Value: app

Outputs:

  LogGroupArn:
    Value: !GetAtt LogGroup.Arn