AWSTemplateFormatVersion: "2010-09-09"
Description: Cloudwatch - Log Resource Policy

Resources:

  LogResourcePolicy:
    Type: AWS::Logs::ResourcePolicy
    Properties:
      PolicyName: "Route53CloudWatchLogs"
      PolicyDocument: "{ \"Version\": \"2012-10-17\", \"Statement\": [ { \"Sid\": \"Route53LogsToCloudWatchLogs\", \"Effect\": \"Allow\", \"Principal\": { \"Service\": [ \"route53.amazonaws.com\" ] }, \"Action\":\"logs:PutLogEvents\", \"Resource\": \"logArn\" } ] }"


Outputs:

  LogResourcePolicyName:
    Value: !Ref LogResourcePolicy
