AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template for Amazon Bedrock Knowledge Base with Amazon Redshift Serverless for Financial Analytics - Dev/Test Environment'

Parameters:
  DatabaseName:
    Type: String
    Default: 'dev'
    Description: 'Name of the Redshift database'

  AdminUsername:
    Type: String
    Default: 'admin'
    Description: 'Admin username for Redshift'

  AdminPassword:
    Type: String
    NoEcho: true
    MinLength: 8
    Description: 'Admin password for Redshift (min 8 characters, must contain uppercase, lowercase, and numbers)'

  KnowledgeBaseName:
    Type: String
    Default: 'financial-analytics-kb'
    Description: 'Name for the Bedrock Knowledge Base'

  NamespaceIdentifier:
    Type: String
    Default: 'financial-namespace'
    Description: 'Identifier for Redshift Serverless namespace'

  WorkgroupIdentifier:
    Type: String
    Default: 'financial-workgroup'
    Description: 'Identifier for Redshift Serverless workgroup'

  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: 'VPC ID where Redshift Serverless will be deployed'

  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: 'List of at least 3 subnet IDs in different AZs for Redshift Serverless'

  AllowedCidrBlock:
    Type: String
    Default: '10.0.0.0/8'
    Description: 'CIDR block allowed to access Redshift (use your VPC CIDR or specific IP range)'
    AllowedPattern: '^(\d{1,3}\.){3}\d{1,3}/\d{1,2}$'

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: 'Network Configuration'
        Parameters:
          - VpcId
          - SubnetIds
          - AllowedCidrBlock
      - Label:
          default: 'Redshift Configuration'
        Parameters:
          - DatabaseName
          - AdminUsername
          - AdminPassword
          - NamespaceIdentifier
          - WorkgroupIdentifier
      - Label:
          default: 'Bedrock Configuration'
        Parameters:
          - KnowledgeBaseName

Resources:
  # S3 Bucket for storing sample data (CloudFormation generated name)
  DataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      Tags:
        - Key: Purpose
          Value: FinancialDataStorage
        - Key: Environment
          Value: Dev

  # IAM Role for Redshift (general purpose, not limited to S3)
  RedshiftRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'RedshiftRole-${AWS::StackName}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - redshift.amazonaws.com
                - redshift-serverless.amazonaws.com
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: S3AccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 's3:GetObject'
                  - 's3:ListBucket'
                Resource:
                  - !GetAtt DataBucket.Arn
                  - !Sub '${DataBucket.Arn}/*'
        - PolicyName: BedrockAccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'bedrock:InvokeModel'
                  - 'bedrock:InvokeModelWithResponseStream'
                Resource: '*'
      Tags:
        - Key: Purpose
          Value: RedshiftAccess
        - Key: Environment
          Value: Dev

  # Security Group for Redshift Serverless (CloudFormation generated name)
  RedshiftSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: 'Security group for Redshift Serverless - Dev Environment'
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5439
          ToPort: 5439
          CidrIp: !Ref AllowedCidrBlock
          Description: 'Redshift access from specified CIDR'
      Tags:
        - Key: Name
          Value: !Sub 'redshift-sg-${AWS::StackName}'
        - Key: Purpose
          Value: RedshiftAccess
        - Key: Environment
          Value: Dev

  # Redshift Serverless Namespace
  RedshiftNamespace:
    Type: AWS::RedshiftServerless::Namespace
    Properties:
      NamespaceName: !Ref NamespaceIdentifier
      AdminUsername: !Ref AdminUsername
      AdminUserPassword: !Ref AdminPassword
      DbName: !Ref DatabaseName
      IamRoles:
        - !GetAtt RedshiftRole.Arn
      DefaultIamRoleArn: !GetAtt RedshiftRole.Arn
      Tags:
        - Key: Environment
          Value: Dev
        - Key: Purpose
          Value: FinancialAnalytics

  # Redshift Serverless Workgroup (Minimum capacity for dev/test)
  RedshiftWorkgroup:
    Type: AWS::RedshiftServerless::Workgroup
    DependsOn: RedshiftNamespace
    Properties:
      WorkgroupName: !Ref WorkgroupIdentifier
      NamespaceName: !Ref NamespaceIdentifier
      BaseCapacity: 8
      PubliclyAccessible: false
      SubnetIds: !Ref SubnetIds
      SecurityGroupIds:
        - !Ref RedshiftSecurityGroup
      Tags:
        - Key: Environment
          Value: Dev
        - Key: Purpose
          Value: FinancialAnalytics
        - Key: CostCenter
          Value: Development

  # IAM Role for Bedrock Knowledge Base
  BedrockKnowledgeBaseRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'BedrockKnowledgeBaseRole-${AWS::StackName}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: bedrock.amazonaws.com
            Action: 'sts:AssumeRole'
            Condition:
              StringEquals:
                'aws:SourceAccount': !Ref AWS::AccountId
              ArnLike:
                'aws:SourceArn': !Sub 'arn:aws:bedrock:${AWS::Region}:${AWS::AccountId}:knowledge-base/*'
      Policies:
        - PolicyName: BedrockKnowledgeBasePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'bedrock:InvokeModel'
                  - 'bedrock:InvokeModelWithResponseStream'
                Resource: 
                  - !Sub 'arn:aws:bedrock:${AWS::Region}::foundation-model/amazon.nova-pro-v1:0'
              - Effect: Allow
                Action:
                  - 'redshift-data:ExecuteStatement'
                  - 'redshift-data:DescribeStatement'
                  - 'redshift-data:GetStatementResult'
                  - 'redshift-data:ListDatabases'
                  - 'redshift-data:ListSchemas'
                  - 'redshift-data:ListTables'
                  - 'redshift-data:DescribeTable'
                Resource: '*'
              - Effect: Allow
                Action:
                  - 'redshift-serverless:GetCredentials'
                Resource: !Sub 'arn:aws:redshift-serverless:${AWS::Region}:${AWS::AccountId}:workgroup/*'
              - Effect: Allow
                Action:
                  - 'secretsmanager:GetSecretValue'
                Resource: !Ref RedshiftSecret
      Tags:
        - Key: Purpose
          Value: BedrockKnowledgeBase
        - Key: Environment
          Value: Dev

  # Bedrock Knowledge Base
  BedrockKnowledgeBase:
    Type: AWS::Bedrock::KnowledgeBase
    DependsOn: 
      - RedshiftWorkgroup
      - BedrockKnowledgeBaseRole
    Properties:
      Name: !Ref KnowledgeBaseName
      Description: 'Knowledge Base for Financial Analytics using Amazon Redshift - Dev Environment'
      RoleArn: !GetAtt BedrockKnowledgeBaseRole.Arn
      KnowledgeBaseConfiguration:
        Type: VECTOR
        VectorKnowledgeBaseConfiguration:
          EmbeddingModelArn: !Sub 'arn:aws:bedrock:${AWS::Region}::foundation-model/amazon.titan-embed-text-v1'
      StorageConfiguration:
        Type: RDS
        RdsConfiguration:
          ResourceArn: !Sub 'arn:aws:redshift-serverless:${AWS::Region}:${AWS::AccountId}:workgroup/${WorkgroupIdentifier}'
          CredentialsSecretArn: !Ref RedshiftSecret
          DatabaseName: !Ref DatabaseName
          TableName: 'bedrock_integration'
          FieldMapping:
            PrimaryKeyField: 'id'
            VectorField: 'embedding'
            TextField: 'text'
            MetadataField: 'metadata'
      Tags:
        Environment: Dev
        Purpose: FinancialAnalytics

  # Secrets Manager Secret for Redshift Credentials
  RedshiftSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub 'redshift-credentials-${AWS::StackName}'
      Description: 'Credentials for Redshift Serverless'
      SecretString: !Sub |
        {
          "username": "${AdminUsername}",
          "password": "${AdminPassword}"
        }
      Tags:
        - Key: Purpose
          Value: RedshiftCredentials
        - Key: Environment
          Value: Dev

  # Lambda Execution Role for Custom Resource
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'LambdaExecutionRole-${AWS::StackName}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
      Policies:
        - PolicyName: RedshiftDataAPIPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'redshift-data:ExecuteStatement'
                  - 'redshift-data:DescribeStatement'
                  - 'redshift-data:GetStatementResult'
                Resource: '*'
              - Effect: Allow
                Action:
                  - 'redshift-serverless:GetCredentials'
                Resource: !Sub 'arn:aws:redshift-serverless:${AWS::Region}:${AWS::AccountId}:workgroup/*'
              - Effect: Allow
                Action:
                  - 'secretsmanager:GetSecretValue'
                Resource: !Ref RedshiftSecret
      Tags:
        - Key: Purpose
          Value: TableCreation
        - Key: Environment
          Value: Dev

  # Lambda Function to Create Tables
  CreateTablesFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub 'CreateRedshiftTables-${AWS::StackName}'
      Runtime: python3.11
      Handler: index.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Timeout: 300
      Environment:
        Variables:
          WORKGROUP_NAME: !Ref WorkgroupIdentifier
          DATABASE_NAME: !Ref DatabaseName
          SECRET_ARN: !Ref RedshiftSecret
      Code:
        ZipFile: |
          import json
          import boto3
          import time
          import cfnresponse
          import os

          redshift_data = boto3.client('redshift-data')

          def lambda_handler(event, context):
              print(f"Event: {json.dumps(event)}")

              try:
                  if event['RequestType'] == 'Delete':
                      cfnresponse.send(event, context, cfnresponse.SUCCESS, {})
                      return

                  workgroup_name = os.environ['WORKGROUP_NAME']
                  database_name = os.environ['DATABASE_NAME']
                  secret_arn = os.environ['SECRET_ARN']

                  # SQL statements to create tables
                  create_table_statements = [
                      """
                      CREATE TABLE IF NOT EXISTS accounts (
                          id integer,
                          account_id integer PRIMARY KEY,
                          customer_id integer,
                          account_type varchar(256),
                          opening_date date,
                          balance bigint,
                          currency varchar(256)
                      );
                      """,
                      """
                      CREATE TABLE IF NOT EXISTS customer (
                          id integer,
                          customer_id integer PRIMARY KEY,
                          name varchar(256),
                          age integer,
                          gender varchar(256),
                          address varchar(256),
                          phone varchar(256),
                          email varchar(256)
                      );
                      """,
                      """
                      CREATE TABLE IF NOT EXISTS investments (
                          id integer,
                          investment_id integer PRIMARY KEY,
                          customer_id integer,
                          investment_type varchar(256),
                          investment_name varchar(256),
                          purchase_date date,
                          purchase_price bigint,
                          quantity integer
                      );
                      """,
                      """
                      CREATE TABLE IF NOT EXISTS loans (
                          id integer,
                          loan_id integer PRIMARY KEY,
                          customer_id integer,
                          loan_type varchar(256),
                          loan_amount bigint,
                          interest_rate integer,
                          start_date date,
                          end_date date
                      );
                      """,
                      """
                      CREATE TABLE IF NOT EXISTS orders (
                          id integer,
                          order_id integer PRIMARY KEY,
                          customer_id integer,
                          order_type varchar(256),
                          order_date date,
                          investment_id integer,
                          quantity integer,
                          price integer
                      );
                      """,
                      """
                      CREATE TABLE IF NOT EXISTS transactions (
                          id integer,
                          transaction_id integer PRIMARY KEY,
                          account_id integer REFERENCES accounts(account_id),
                          transaction_type varchar(256),
                          transaction_date date,
                          amount integer,
                          description varchar(256)
                      );
                      """
                  ]

                  # Execute each CREATE TABLE statement
                  for sql in create_table_statements:
                      response = redshift_data.execute_statement(
                          WorkgroupName=workgroup_name,
                          Database=database_name,
                          SecretArn=secret_arn,
                          Sql=sql
                      )

                      statement_id = response['Id']
                      print(f"Executed statement: {statement_id}")

                      # Wait for statement to complete
                      while True:
                          status_response = redshift_data.describe_statement(Id=statement_id)
                          status = status_response['Status']

                          if status == 'FINISHED':
                              print(f"Statement {statement_id} completed successfully")
                              break
                          elif status == 'FAILED':
                              error = status_response.get('Error', 'Unknown error')
                              raise Exception(f"Statement {statement_id} failed: {error}")
                          elif status == 'ABORTED':
                              raise Exception(f"Statement {statement_id} was aborted")

                          time.sleep(2)

                  cfnresponse.send(event, context, cfnresponse.SUCCESS, {
                      'Message': 'Tables created successfully'
                  })

              except Exception as e:
                  print(f"Error: {str(e)}")
                  cfnresponse.send(event, context, cfnresponse.FAILED, {
                      'Message': str(e)
                  })
      Tags:
        - Key: Purpose
          Value: TableCreation
        - Key: Environment
          Value: Dev

  # Custom Resource to Trigger Table Creation
  CreateTablesCustomResource:
    Type: Custom::CreateTables
    DependsOn: RedshiftWorkgroup
    Properties:
      ServiceToken: !GetAtt CreateTablesFunction.Arn

Outputs:
  S3BucketName:
    Description: 'S3 Bucket for storing financial data CSV files'
    Value: !Ref DataBucket
    Export:
      Name: !Sub '${AWS::StackName}-DataBucket'

  RedshiftWorkgroupName:
    Description: 'Redshift Serverless Workgroup Name'
    Value: !Ref WorkgroupIdentifier
    Export:
      Name: !Sub '${AWS::StackName}-WorkgroupName'

  RedshiftNamespaceName:
    Description: 'Redshift Serverless Namespace Name'
    Value: !Ref NamespaceIdentifier
    Export:
      Name: !Sub '${AWS::StackName}-NamespaceName'

  RedshiftDatabaseName:
    Description: 'Redshift Database Name'
    Value: !Ref DatabaseName
    Export:
      Name: !Sub '${AWS::StackName}-DatabaseName'

  RedshiftWorkgroupEndpoint:
    Description: 'Redshift Serverless Workgroup Endpoint'
    Value: !GetAtt RedshiftWorkgroup.Workgroup.Endpoint.Address
    Export:
      Name: !Sub '${AWS::StackName}-WorkgroupEndpoint'

  BedrockKnowledgeBaseId:
    Description: 'Bedrock Knowledge Base ID'
    Value: !Ref BedrockKnowledgeBase
    Export:
      Name: !Sub '${AWS::StackName}-KnowledgeBaseId'

  BedrockKnowledgeBaseRoleArn:
    Description: 'IAM Role ARN for Bedrock Knowledge Base'
    Value: !GetAtt BedrockKnowledgeBaseRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-KnowledgeBaseRoleArn'

  RedshiftRoleArn:
    Description: 'IAM Role ARN for Redshift'
    Value: !GetAtt RedshiftRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-RedshiftRoleArn'

  SecretArn:
    Description: 'Secrets Manager Secret ARN for Redshift Credentials'
    Value: !Ref RedshiftSecret
    Export:
      Name: !Sub '${AWS::StackName}-SecretArn'

  SecurityGroupId:
    Description: 'Security Group ID for Redshift Serverless'
    Value: !Ref RedshiftSecurityGroup
    Export:
      Name: !Sub '${AWS::StackName}-SecurityGroupId'

  EstimatedMonthlyCost:
    Description: 'Estimated monthly cost for dev/test environment'
    Value: 'Redshift Serverless: ~$43/month (8 RPU * 730 hours * $0.36/RPU-hour). Bedrock charges apply per query.'

  NextSteps:
    Description: 'Next steps to complete the setup'
    Value: !Sub |
      1. Download sample data from the blog post
      2. Upload CSV files to S3 bucket: ${DataBucket}
      3. Use Redshift Query Editor V2 to run COPY commands
      4. Grant permissions to Bedrock service role: ${BedrockKnowledgeBaseRole}
      5. Sync the Knowledge Base in Bedrock console
      6. Test queries in Bedrock Knowledge Base console