AWSTemplateFormatVersion: "2010-09-09"
Description: Example template for a Step Functions state machine.

Resources:

  LambdaExecutionRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: "sts:AssumeRole"

  LambdaFunction:
    Type: "AWS::Lambda::Function"
    Properties:
      Handler: "index.handler"
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        ZipFile: |
          exports.handler = (event, context, callback) => {
              callback(null, event);
          };
      Runtime: "nodejs12.x"
      Timeout: "25"

  StateMachineExecutionRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - !Sub states.${AWS::Region}.amazonaws.com
            Action: "sts:AssumeRole"
      Path: "/"
      Policies:
        - PolicyName: StatesExecutionPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "lambda:InvokeFunction"
                Resource: "*"

  StateMachine:
    Type: "AWS::StepFunctions::StateMachine"
    Properties:
      #StateMachineName: StateMachine
      RoleArn: !GetAtt StateMachineExecutionRole.Arn
      DefinitionString:
        !Sub
          - |-
            {
              "Comment": "An example of the Amazon States Language using a choice state.",
              "StartAt": "FirstState",
              "TimeoutSeconds": 30,
              "States": {
                "FirstState": {
                  "Type": "Task",
                  "Comment": "State Comment",
                  "Resource": "${lambdaArn}",
                  "TimeoutSeconds": 5,
                  "HeartbeatSeconds": 3,
                  "Next": "PassState"
                },
                "PassState": {
                  "Type": "Pass",
                  "Result": {
                    "x-datum": 0.381018,
                    "y-datum": 622.2269926397355
                  },
                  "ResultPath": "$.coords",
                  "Next": "ChoiceState"
                },
                "ChoiceState": {
                  "Type" : "Choice",
                  "Choices": [
                    {
                      "Variable": "$.foo",
                      "NumericEquals": 1,
                      "Next": "FirstMatchState"
                    },
                    {
                      "Variable": "$.foo",
                      "NumericEquals": 2,
                      "Next": "SecondMatchState"
                    },
                    {
                      "Variable": "$.foo",
                      "NumericEquals": 3,
                      "Next": "SuccessState"
                    }
                  ],
                  "Default": "DefaultState"
                },
                "FirstMatchState": {
                  "Type" : "Task",
                  "Resource": "${lambdaArn}",
                  "Next": "NextState"
                },
                "SecondMatchState": {
                  "Type" : "Task",
                  "Resource": "${lambdaArn}",
                  "Next": "NextState"
                },
                "DefaultState": {
                  "Type": "Fail",
                  "Error": "DefaultStateError",
                  "Cause": "No Matches!"
                },
                "SuccessState": {
                  "Type": "Succeed"
                },
                "NextState": {
                  "Type": "Task",
                  "Resource": "${lambdaArn}",
                  "Next": "FinalState",
                  "Catch": [ {
                    "ErrorEquals": [ "java.lang.Exception" ],
                    "ResultPath": "$.error-info",
                    "Next": "FinalState"
                  }, {
                    "ErrorEquals": [ "States.ALL" ],
                    "Next": "FinalState"
                  } ]
                },
                "FinalState": {
                  "Type": "Task",
                  "Resource": "${lambdaArn}",
                  "End": true
                }
              }
            }
          - {lambdaArn: !GetAtt [ LambdaFunction, Arn ]}
      
      Tags:
        -
          Key: "Environment"
          Value: "dev"
        -
          Key: "Application"
          Value: "app"

