AWSTemplateFormatVersion: "2010-09-09"
Description: Elasticache Redis Basic (cluster mode disabled) - Launch Redis inside VPC with 2 Nodes. 
# The Redis cluster will have a single shard (node group) with one primary node and up to 5 read replica. 

Parameters:

  VpcId:
    Description: VPC ID
    Type: AWS::EC2::VPC::Id

  VpcSubnet1:
    Description: EC2 subnet 1
    Type: AWS::EC2::Subnet::Id

  VpcSubnet2:
    Description: EC2 subnet 2
    Type: AWS::EC2::Subnet::Id

Resources:

  ECacheSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties: 
      VpcId: !Ref VpcId
      #GroupName: !Ref ECacheSecurityGroupName
      GroupDescription: Security Group for Elasticache Redis
      SecurityGroupIngress:
        - 
          IpProtocol: tcp
          CidrIp: '0.0.0.0/0'
          FromPort: 6379
          ToPort: 6379
        - 
          IpProtocol: tcp
          CidrIpv6: '::/0'
          FromPort: 6379
          ToPort: 6379
      Tags:
        - Key: environment
          Value: dev

  ECacheSubnetGroup:
    Type: "AWS::ElastiCache::SubnetGroup"
    Properties:
      CacheSubnetGroupName: ecache-redis-subnet-group
      Description: Redis Subnet Group
      SubnetIds:
        - !Ref VpcSubnet1
        - !Ref VpcSubnet2

  ECacheReplicationGroup:
    Type: "AWS::ElastiCache::ReplicationGroup"
    Properties:
      ReplicationGroupId: ecache-redis-replication-group # (Optional)
      ReplicationGroupDescription: 'Elasticache Redis Replication Group'
      AtRestEncryptionEnabled: true
      AutomaticFailoverEnabled: true
      AutoMinorVersionUpgrade: true
      CacheNodeType: cache.t2.micro
      CacheParameterGroupName: default.redis6.x
      CacheSubnetGroupName: !Ref ECacheSubnetGroup
      #TransitEncryptionEnabled: true
      #AuthToken: 
      #UserGroupIds:
      Engine: redis
      EngineVersion: 6.2
      NumCacheClusters: 2 # The maximum permitted value for NumCacheClusters is 6 (1 primary plus 5 replicas).
      MultiAZEnabled: true
      SecurityGroupIds:
        - !Ref ECacheSecurityGroup
      #PreferredCacheClusterAZs:
      #  - 
      LogDeliveryConfigurations:
        - DestinationType: cloudwatch-logs # cloudwatch-logs or kinesis-firehose
          LogFormat: json # json or text
          LogType: engine-log #slow-log engine-log
          DestinationDetails:
            CloudWatchLogsDetails:
              LogGroup: !Ref ECacheRedisLogGroupEngine
        - DestinationType: cloudwatch-logs # cloudwatch-logs or kinesis-firehose
          LogFormat: json # json or text
          LogType: slow-log #slow-log engine-log
          DestinationDetails:
            CloudWatchLogsDetails:
              LogGroup: !Ref ECacheRedisLogGroupSlowLog
      PreferredMaintenanceWindow: 'sun:17:00-sun:20:00'
      SnapshotRetentionLimit: 5
      SnapshotWindow: '03:15-08:15'
      Tags:
        - Key: environment
          Value: dev

  ECacheRedisLogGroupEngine:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/ecache/redis/redis-cluster-engine"
      RetentionInDays: 1

  ECacheRedisLogGroupSlowLog:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/ecache/redis/redis-cluster-slowlog"
      RetentionInDays: 1

Outputs:

  # Redis (cluster mode disabled) replication groups don't have this attribute. 
  #ECacheRedisClusterEndpoint:
  #  Value: !GetAtt ECacheReplicationGroup.ConfigurationEndpoint.Address

  # Redis (cluster mode disabled) replication groups don't have this attribute. 
  #ECacheRedisClusterEndpointPort:
  #  Value: !GetAtt ECacheReplicationGroup.ConfigurationEndpoint.Port

  ECacheRedisPrimaryEndPoint:
    Value: !GetAtt ECacheReplicationGroup.PrimaryEndPoint.Address

  ECacheRedisPrimaryEndPointPort:
    Value: !GetAtt ECacheReplicationGroup.PrimaryEndPoint.Port

  ECacheRedisReaderEndPoint:
    Value: !GetAtt ECacheReplicationGroup.ReaderEndPoint.Address

  ECacheRedisReaderEndPointPort:
    Value: !GetAtt ECacheReplicationGroup.ReaderEndPoint.Port
