AWSTemplateFormatVersion: "2010-09-09"
Description: ElastiCache Memcached

Metadata:

  AWS::CloudFormation::Interface:

    ParameterGroups:
      -
        Label:
          default: "Network Configuration"
        Parameters:
          - VpcId
          - VpcSubnet1
          - VpcSubnet2
          - AvailabilityZone1
          - AvailabilityZone2
      -
        Label:
          default: "Cache Configuration"
        Parameters:
          - ECacheNodeType
          - ECacheNodeCount

#TODO
#  VpcSubnetListCache:
#    Description: Public VpcSubnets for ElastiCache
#    Type: List<AWS::EC2::Subnet::Id>

Parameters:

  VpcId:
    Description: VPC ID
    Type: AWS::EC2::VPC::Id

  VpcSubnet1:
    Description: EC2 subnet 1
    Type: AWS::EC2::Subnet::Id

  VpcSubnet2:
    Description: EC2 subnet 2
    Type: AWS::EC2::Subnet::Id

  AvailabilityZone1:
    Description: Please input Availability Zone
    Type: AWS::EC2::AvailabilityZone::Name
    AllowedPattern: ".+"

  AvailabilityZone2:
    Description: Please input Availability Zone
    Type: AWS::EC2::AvailabilityZone::Name
    AllowedPattern: ".+"

  ECacheNodeType:
    Description: Memcached Node Type
    Type: String
    Default: "cache.t2.micro"

  ECacheNodeCount:
    Description: Number of Memcached Nodes
    Type: Number
    Default: "2"

Resources:

  ECacheSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties: 
      VpcId: !Ref VpcId
      #GroupName: !Ref ECacheSecurityGroupName
      GroupDescription: Security Group for Elasticache Memcached
      SecurityGroupIngress:
        - 
          IpProtocol: tcp
          CidrIp: '0.0.0.0/0'
          FromPort: 11211
          ToPort: 11211
        - 
          IpProtocol: tcp
          CidrIpv6: '::/0'
          FromPort: 11211
          ToPort: 11211
      Tags:
        - Key: environment
          Value: dev

  ECacheSubnetGroup:
    Type: "AWS::ElastiCache::SubnetGroup"
    Properties:
      CacheSubnetGroupName: ecache-memcached-subnet-group #(Optional)
      Description: Memcached Subnet Group
      SubnetIds:
        - !Ref VpcSubnet1
        - !Ref VpcSubnet2

  ECacheMemcachedParameterGroup:
    Type: "AWS::ElastiCache::ParameterGroup"
    Properties:
      Description: "Memcached Parameter Group"
      CacheParameterGroupFamily: memcached1.6 # memcached1.4 | memcached1.5 | memcached1.6 |
      Properties:
        cas_disabled: '1'
        chunk_size_growth_factor: '1.02'
      Tags:
        - Key: environment
          Value: dev

  ECacheMemcachedCluster:
    Type: "AWS::ElastiCache::CacheCluster"
    Properties:
      AutoMinorVersionUpgrade: false
      AZMode: cross-az #cross-az | single-az
      CacheNodeType: !Ref ECacheNodeType
      CacheParameterGroupName: !Ref ECacheMemcachedParameterGroup
      CacheSubnetGroupName: !Ref ECacheSubnetGroup
      ClusterName: memcached-cluster #(Optional)
      Engine: memcached
      EngineVersion: 1.6.12
      NumCacheNodes: !Ref ECacheNodeCount
      Port: 11211
      PreferredAvailabilityZones:
        - !Ref AvailabilityZone1
        - !Ref AvailabilityZone2
      PreferredMaintenanceWindow: 'sun:17:00-sun:20:00'
      VpcSecurityGroupIds:
        - !Ref ECacheSecurityGroup
      #LogDeliveryConfigurations:
      #  - DestinationType: cloudwatch-logs # cloudwatch-logs or kinesis-firehose
      #    LogFormat: json # json or text
      #    LogType: engine-log #slow-log engine-log
      #    DestinationDetails:
      #      CloudWatchLogsDetails:
      #        LogGroup: !Ref ECacheMemcachedLogGroup
      #NotificationTopicArn
      Tags:
        - Key: environment
          Value: dev

Outputs:

  ECacheMemcachedClusterEndpoint:
    Value: !GetAtt ECacheMemcachedCluster.ConfigurationEndpoint.Address
