AWSTemplateFormatVersion: "2010-09-09"
Description: CodeCommit - Event Triggers to SNS

Parameters:

  RepositoryName:
    Type: "String"
    Default: "code-repository-trigger"
    Description: "Code Commit Repository Name"

Resources:

  CodeCommitRepository:
    Type: AWS::CodeCommit::Repository
    #DeletionPolicy: Retain
    Properties:
      RepositoryDescription: "Demo Repository"
      RepositoryName: !Ref RepositoryName
      Triggers:
      - Name: EventAll
        CustomData: Version-1
        DestinationArn: !Ref SNSTopic
        Branches:
        - main
        Events: # all | updateReference | createReference | deleteReference
        - all
      - Name: EventMainCreateOrUpdate
        CustomData: Version-1
        DestinationArn: !Ref SNSTopic
        Branches:
        - main
        Events:
        - createReference
        - updateReference
      Tags:
        - Key: environment
          Value: stg

  SNSTopic:
    Type: "AWS::SNS::Topic"
    Properties:
      DisplayName: "My Topic"
      Tags:
        -
          Key: "Environment"
          Value: "dev"
        -
          Key: "Application"
          Value: "acme"

Outputs:

  CodeCommitRepositoryArn:
    Value: !GetAtt CodeCommitRepository.Arn

  CodeCommitRepositoryCloneUrlHttp:
    Value: !GetAtt CodeCommitRepository.CloneUrlHttp
