AWSTemplateFormatVersion: "2010-09-09"
Description: EC2 Load Balancer + Autoscaling Group. EC2 on Private Subnet.

Metadata:

  StackVersion: 1

  AWS::CloudFormation::Interface:

    ParameterGroups:
      -
        Label:
          default: "Network Configuration"
        Parameters:
          - VpcId
          - VpcSubnetCidr
          - VpcPublicSubnet1
          - VpcPublicSubnet2
          - VpcPrivateSubnet1
          - VpcPrivateSubnet2
          - StaticIPforSSH
      -
        Label:
          default: "Instance Configuration"
        Parameters:
          - Ec2ImageId
          - Ec2InstanceType
          - Ec2InstanceKeyName
      -
        Label:
          default: "Auto Scaling Configuration"
        Parameters:
          - Ec2AutoscaleMinSize
          - Ec2AutoscaleMaxSize
          - Ec2AutoscaleDesiredCapacity

    ParameterLabels: 
      VpcId: 
        default: "Vpc ID"
      VpcPublicSubnet1: 
        default: "Public Subnet 1"

Parameters:

  VpcId:
    Description: VPC ID
    Type: AWS::EC2::VPC::Id

  VpcSubnetCidr:
    Description: VPC subnet CIDR
    Type: String
    Default: 10.0.0.0/16

  VpcPublicSubnet1:
    Description: Public Subnet 1
    Type: AWS::EC2::Subnet::Id

  VpcPublicSubnet2:
    Description: Public Subnet 2
    Type: AWS::EC2::Subnet::Id

  VpcPrivateSubnet1:
    Description: Private Subnet 1
    Type: AWS::EC2::Subnet::Id

  VpcPrivateSubnet2:
    Description: Private Subnet 2
    Type: AWS::EC2::Subnet::Id

  StaticIPforSSH:
    Description: Static IP for SSH access
    Type: String
    Default: 127.0.0.1/32

  Ec2ImageId:
    Description: AMI ID
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'

  Ec2InstanceType:
    Description: EC2 InstanceType
    Type: String
    Default: t2.micro

  Ec2InstanceKeyName:
    Description: EC2 SSH KEY
    Type: AWS::EC2::KeyPair::KeyName
    Default: SSHKey

  Ec2AutoscaleMinSize:
    Description: AutoScalingGroup MinSize
    Type: String
    Default: '1'

  Ec2AutoscaleMaxSize:
    Description: AutoScalingGroup MaxSize
    Type: String
    Default: '1'

  Ec2AutoscaleDesiredCapacity:
    Description: AutoScalingGroup DesiredCapacity
    Type: String
    Default: '1'

Resources:

  Ec2IAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - ec2.amazonaws.com
          Action:
          - sts:AssumeRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      Path: /
      Policies: !Ref 'AWS::NoValue'
      RoleName: !Ref 'AWS::NoValue'

  Ec2RolePolicies:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: Ec2RolePolicies
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - s3:List*
          Resource:
          - '*'
        - Effect: Allow
          Action:
          - logs:CreateLogGroup
          - logs:CreateLogStream
          - logs:PutLogEvents
          - logs:DescribeLogStreams
          Resource:
          - arn:aws:logs:*:*:*
      Roles:
      - !Ref 'Ec2IAMRole'

  Ec2IAMProfile:
    Type: AWS::IAM::InstanceProfile
    DependsOn: Ec2IAMRole
    Properties:
      Path: /
      Roles:
      - !Ref Ec2IAMRole

  LoadBalancerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref 'VpcId'
      GroupDescription: allow ICMP via same VPC
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: "0.0.0.0/0"

  Ec2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref 'VpcId'
      GroupDescription: allow ICMP via same VPC
      SecurityGroupIngress:
      - IpProtocol: icmp
        FromPort: -1
        ToPort: -1
        CidrIp: !Ref 'VpcSubnetCidr'
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        SourceSecurityGroupId: !Ref LoadBalancerSecurityGroup
      #- IpProtocol: tcp
      #  FromPort: 80
      #  ToPort: 80
      #  CidrIp: "0.0.0.0/0"

  Ec2SecurityGroupSSH:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref 'VpcId'
      GroupDescription: allow SSH via static IP
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: !Ref 'StaticIPforSSH'

  Ec2InstanceLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData:
        ImageId: !Ref 'Ec2ImageId'
        InstanceType: !Ref 'Ec2InstanceType'
        IamInstanceProfile:
          Arn: !GetAtt 'Ec2IAMProfile.Arn'
        KeyName: !Ref 'Ec2InstanceKeyName'
        SecurityGroupIds:
        - !Ref 'Ec2SecurityGroup'
        - !Ref 'Ec2SecurityGroupSSH'
        InstanceInitiatedShutdownBehavior: terminate
        CreditSpecification: 
          CpuCredits: Unlimited
        #InstanceMarketOptions:
        #  SpotOptions:
        #    SpotInstanceType: one-time # one-time | persistent If you are using Spot Instances with an Auto Scaling group, use one-time requests
        #    InstanceInterruptionBehavior: terminate #hibernate | stop | terminate
        #  MarketType: spot
        Monitoring: #Detailed CloudWatch monitoring
          Enabled: false
        BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeSize: 8
            VolumeType: gp2
            DeleteOnTermination: true
        UserData:
          Fn::Base64: |
            #!/bin/bash
            yum update -y
            yum install -y httpd
            systemctl start httpd
            systemctl enable httpd
            echo "<h1>Hi from $(hostname -f)</h1>" > /var/www/html/index.html
        TagSpecifications: #The specified tags are applied to all instances or volumes that are created during launch.
        - ResourceType: instance
          Tags:
          - Key: Env
            Value: "dev"
        - ResourceType: volume
          Tags:
          - Key: Env
            Value: "dev"
        - ResourceType: instance
          Tags:
          - Key: Name
            Value: !Ref 'AWS::StackName'

  TargetGroup: 
    Type: "AWS::ElasticLoadBalancingV2::TargetGroup"
    Properties: 
      VpcId: !Ref VpcId
      #Name: !Sub "${PJPrefix}-${InternetALBName}-tg"
      Protocol: HTTP # GENEVE | HTTP | HTTPS | TCP | TCP_UDP | TLS | UDP
      ProtocolVersion: HTTP2 # GRPC, HTTP1, and HTTP2
      Port: 80
      HealthCheckProtocol: HTTP
      HealthCheckPath: "/"
      HealthCheckPort: "traffic-port"
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 2
      HealthCheckTimeoutSeconds: 5
      HealthCheckIntervalSeconds: 10
      Matcher: 
        HttpCode: 200
      #TargetGroupAttributes: 
      #  - Key: "deregistration_delay.timeout_seconds"
      #    Value: 300
      #  - Key: "stickiness.enabled"
      #    Value: false
      #  - Key: "stickiness.type"
      #    Value: lb_cookie
      #  - Key: "stickiness.lb_cookie.duration_seconds"
      #    Value: 86400
      # load_balancing.algorithm.type round_robin | least_outstanding_requests
      # slow_start.duration_seconds 30-900 seconds (15 minutes). The default is 0 seconds (disabled)
      #Targets: 
      #  - Id: !Ref EC2Instance
      #    Port: 80
      #Tags:
      #  - Key: Name
      #    Value: !Sub "${PJPrefix}-${InternetALBName}-tg"

  LoadBalancer:
    Type: "AWS::ElasticLoadBalancingV2::LoadBalancer"
    Properties: 
      #Name: !Sub "${PJPrefix}-${InternetALBName}-alb"
      #"Tags: 
      #  - Key: Name
      #    Value: !Sub "${PJPrefix}-${InternetALBName}-alb"
      Scheme: "internet-facing"
      #LoadBalancerAttributes: 
      #  - Key: "deletion_protection.enabled"
      #    Value: false
      #  - Key: "idle_timeout.timeout_seconds"
      #    Value: 60
      SecurityGroups:
        - !Ref LoadBalancerSecurityGroup
      Subnets: 
        - !Ref VpcPublicSubnet1
        - !Ref VpcPublicSubnet2

  LoadBalancerListener: 
    Type: "AWS::ElasticLoadBalancingV2::Listener"
    Properties: 
      DefaultActions: 
        - TargetGroupArn: !Ref TargetGroup
          Type: forward
      LoadBalancerArn: !Ref LoadBalancer
      Port: 80
      Protocol: HTTP

  Ec2InstanceAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      #AutoScalingGroupName: ApplicationAsg
      VPCZoneIdentifier:
      - !Ref VpcPrivateSubnet1
      - !Ref VpcPrivateSubnet2
      LaunchTemplate:
        LaunchTemplateId: !Ref 'Ec2InstanceLaunchTemplate'
        Version: !GetAtt 'Ec2InstanceLaunchTemplate.LatestVersionNumber'
      MinSize: !Ref 'Ec2AutoscaleMinSize'
      MaxSize: !Ref 'Ec2AutoscaleMaxSize'
      DesiredCapacity: !Ref 'Ec2AutoscaleDesiredCapacity'
      HealthCheckType: ELB #EC2 (default) and ELB
      HealthCheckGracePeriod: 60 #  amount of time, in seconds, that Amazon EC2 Auto Scaling waits before checking the health status
      TargetGroupARNs:
        - !Ref TargetGroup
      Tags:
        - Key: Environment
          Value: Production
          PropagateAtLaunch: "false"
        - Key: Purpose
          Value: WebServerGroup
          PropagateAtLaunch: "true"

Outputs:

  LoadBalancerDomainName:
    Value: !GetAtt LoadBalancer.DNSName
