AWSTemplateFormatVersion: "2010-09-09"
Description: "Vpc Endpoint - Instance Connect Endpoint"

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: "Application Configuration"
        Parameters:
          - Application
          - Environment
      -
        Label:
          default: "Network Configuration"
        Parameters:
          - VpcId
          - VpcSubnetList

Parameters:

  Application:
    Type: String
    Default: lab
    Description: Application Name
    
  Environment:
    Type: String
    Default: dev
    Description: Environment

  VpcId:
    Description : "VPC ID"
    Type: AWS::EC2::VPC::Id

  VpcSubnet:
    Description: "Private VpcSubnets for Endpoint"
    Type: AWS::EC2::Subnet::Id

  InstanceConnectClientToken:
    Type: String
    Default: "foobar432987432"
    Description: InstanceConnectClientToken

Resources:

  EicSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "InstanceConnectEndpoint"
      VpcId: !Ref VpcId
        
  EicEndpoint:
    Type: "AWS::EC2::InstanceConnectEndpoint"
    Properties: 
      ClientToken: !Ref InstanceConnectClientToken #Unique, case-sensitive identifier that you provide to ensure the idempotency of the request.
      PreserveClientIp: "true"
      SecurityGroupIds: #One or more security groups to associate with the endpoint. 
        - !Ref EicSecurityGroup
      SubnetId: !Ref VpcSubnet
      Tags:
        - Key: Name
          Value: "instance-connect-endpoint"
