AWSTemplateFormatVersion: "2010-09-09"
Description: "Vpc Endpoint (Interface Endpoint) - Bedrock"

# https://docs.aws.amazon.com/bedrock/latest/userguide/usingVPC.html

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: "Application Configuration"
        Parameters:
          - Application
          - Environment
      -
        Label:
          default: "Network Configuration"
        Parameters:
          - VpcId
          - VpcSubnetList

Parameters:

  Application:
    Type: String
    Default: lab
    Description: Application Name
    
  Environment:
    Type: String
    Default: dev
    Description: Environment

  VpcId:
    Description : "VPC ID"
    Type: AWS::EC2::VPC::Id

  VpcSubnetList:
    Description: "Private VpcSubnets for Endpoint"
    Type: List<AWS::EC2::Subnet::Id>

Resources:

 VpcEndpointBedrock:
  Type: "AWS::EC2::VPCEndpoint"
  Properties:
    VpcEndpointType: Interface
    ServiceName: !Sub "com.amazonaws.${AWS::Region}.bedrock"
    VpcId: !Ref VpcId
    SubnetIds: !Ref VpcSubnetList
    PrivateDnsEnabled: true

 VpcEndpointBedrockRuntime:
  Type: "AWS::EC2::VPCEndpoint"
  Properties:
    VpcEndpointType: Interface
    ServiceName: !Sub "com.amazonaws.${AWS::Region}.bedrock-runtime"
    VpcId: !Ref VpcId
    SubnetIds: !Ref VpcSubnetList
    PrivateDnsEnabled: true

 VpcEndpointBedrockAgent:
  Type: "AWS::EC2::VPCEndpoint"
  Properties:
    VpcEndpointType: Interface
    ServiceName: !Sub "com.amazonaws.${AWS::Region}.bedrock-agent"
    VpcId: !Ref VpcId
    SubnetIds: !Ref VpcSubnetList
    PrivateDnsEnabled: true

 VpcEndpointBedrockAgentRuntime:
  Type: "AWS::EC2::VPCEndpoint"
  Properties:
    VpcEndpointType: Interface
    ServiceName: !Sub "com.amazonaws.${AWS::Region}.bedrock-agent-runtime"
    VpcId: !Ref VpcId
    SubnetIds: !Ref VpcSubnetList
    PrivateDnsEnabled: true

Outputs:

  VpcEndpointBedrockID:
    Description: The Endpoint Id
    Value: !Ref VpcEndpointBedrock

  VpcEndpointBedrockRuntimeOD:
    Description: The Endpoint Id
    Value: !Ref VpcEndpointBedrockRuntime

  VpcEndpointBedrockAgentID:
    Description: The Endpoint Id
    Value: !Ref VpcEndpointBedrockAgent

  VpcEndpointBedrockAgentRuntimeID:
    Description: The Endpoint Id
    Value: !Ref VpcEndpointBedrockAgentRuntime