AWSTemplateFormatVersion: "2010-09-09"
Description: DataSync - Log Resource Policy

Resources:

  LogResourcePolicy:
    Type: AWS::Logs::ResourcePolicy
    Properties:
      PolicyName: "DataSyncCloudWatchLogs"
      PolicyDocument: !Sub |
        {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Principal": {
                "Service": "datasync.amazonaws.com"
              },
              "Action": [
                "logs:CreateLogStream",
                "logs:PutLogEvents"
              ],
              "Resource": [ "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:*:*" ],
              "Condition": {
                "StringEquals": { "aws:SourceAccount": "${AWS::AccountId}" },
                "ArnLike": { "aws:SourceArn": [ "arn:aws:datasync:${AWS::Region}:${AWS::AccountId}:task/*" ] }
              }
            }
          ]
        }

Outputs:

  LogResourcePolicyName:
    Value: !Ref LogResourcePolicy
