AWSTemplateFormatVersion: 2010-09-09
Description: DataSync S3 to S3

Resources:

  DataSyncSourceBucket:
    Type: AWS::S3::Bucket
    #DeletionPolicy: Retain
    Properties:
      #BucketName: !Sub ${SystemName}-${EnvType}-${Tagprefix}-${S3BucketName1}-${AWS::AccountId}
      PublicAccessBlockConfiguration: 
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Suspended          
      BucketEncryption:
        ServerSideEncryptionConfiguration: 
          - ServerSideEncryptionByDefault: 
              SSEAlgorithm: AES256                  
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced
      NotificationConfiguration:
        EventBridgeConfiguration:
          EventBridgeEnabled: false           
      Tags:
        - Key: "Name"
          Value: "datasync-src-bucket"      

  DataSyncSourceServiceRole:
    Type: AWS::IAM::Role
    Properties:
      #RoleName: !Sub ${SystemName}-${EnvType}-${Tagprefix}-DataSync-Source-IAM-Role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "datasync.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      #MaxSessionDuration: 3600        
      Path: /
      Tags:
        - Key: "Name"
          Value: "datasync-service-role"

  DataSyncSourceServiceRolePolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Policy to Access DataSync Source
      Path: /
      #ManagedPolicyName: !Sub ${SystemName}-${EnvType}-${Tagprefix}-DataSync-Source-IAM-Policy
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Sid: bucket
            Action:
              - s3:GetBucketLocation
              - s3:ListBucket
              - s3:ListBucketMultipartUploads
            Resource:
              - !Sub "arn:${AWS::Partition}:s3:::${DataSyncSourceBucket}"
          - Effect: Allow
            Sid: bucketobject
            Action:
              - s3:AbortMultipartUpload
              - s3:DeleteObject
              - s3:GetObject
              - s3:ListMultipartUploadParts
              - s3:PutObjectTagging
              - s3:GetObjectTagging
              - s3:PutObject
            Resource:
              - !Sub "arn:${AWS::Partition}:s3:::${DataSyncSourceBucket}/*"
      Roles:
        - !Ref DataSyncSourceServiceRole

  DataSyncSourceBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref DataSyncSourceBucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              AWS: !GetAtt DataSyncSourceServiceRole.Arn
            Action: 
              - s3:GetBucketLocation
              - s3:ListBucket
              - s3:ListBucketMultipartUploads
              - s3:AbortMultipartUpload
              - s3:DeleteObject
              - s3:GetObject
              - s3:ListMultipartUploadParts
              - s3:PutObject
              - s3:GetObjectTagging
              - s3:PutObjectTagging
            Resource: 
              - !Sub "arn:${AWS::Partition}:s3:::${DataSyncSourceBucket}"
              - !Sub "arn:${AWS::Partition}:s3:::${DataSyncSourceBucket}/*"

  DataSyncSource:
    Type: AWS::DataSync::LocationS3
    DependsOn: 
      - DataSyncSourceBucketPolicy 
    Properties:
      S3BucketArn: !Sub "arn:${AWS::Partition}:s3:::${DataSyncSourceBucket}"
      S3Config:
        BucketAccessRoleArn: !GetAtt DataSyncSourceServiceRole.Arn
      S3StorageClass: STANDARD
      #Subdirectory: ""
      Tags:
        - Key: "Name"
          Value: "datasync-source"

Outputs:

  DataSyncSourceBucket:
    Description: DataSyncSourceBucket
    Value: !Ref DataSyncSourceBucket

  DataSyncSource:
    Description: DataSyncSource
    Value: !Ref DataSyncSource
