AWSTemplateFormatVersion: "2010-09-09"
Description: S3 Basic Template

Metadata:
  "AWS::CloudFormation::Interface":
    ParameterGroups:
      - Label: 
          default: "S3 Configuration"
        Parameters: 
          - BucketName

    ParameterLabels: 
      BucketName: 
        default: "Bucket Name"

Parameters:

  BucketName:
    Type: "String"
    Default: "my-bucket"
    Description: "Must contain only lowercase letters, numbers, periods (.), and dashes (-) "

Resources:

  Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Ref BucketName
      AccessControl: "Private" # Private, PublicRead, PublicReadWrite, AuthenticatedRead, LogDeliveryWrite, BucketOwnerRead, BucketOwnerFullControl, or AwsExecRead.
      VersioningConfiguration:
         Status: Suspended
      Tags:
        - Key: "management"
          Value: "manual"

Outputs:

  BucketArn:
    Value: !GetAtt Bucket.Arn