AWSTemplateFormatVersion: "2010-09-09"
Description: S3 Bucket  - Encryption

# Describes the default server-side encryption to apply to new objects in the bucket.
# If a PUT Object request doesn't specify any server-side encryption, this default encryption will be applied.
# If you don't specify a customer managed key at configuration, Amazon S3 automatically creates an AWS KMS key in your AWS account 
#  the first time that you add an object encrypted with SSE-KMS to a bucket. 
#  By default, Amazon S3 uses this KMS key for SSE-KMS. 

Resources:

  BucketEncryptS3:
    Type: "AWS::S3::Bucket"
    DeletionPolicy: Delete
    Properties:
      #BucketName: !Ref BucketName
      AccessControl: "Private" # Private, PublicRead, PublicReadWrite, AuthenticatedRead, LogDeliveryWrite, BucketOwnerRead, BucketOwnerFullControl, or AwsExecRead.
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        IgnorePublicAcls: True
        BlockPublicPolicy: True
        RestrictPublicBuckets: True
      VersioningConfiguration:
         Status: Suspended
      BucketEncryption: # SSE-S3
        ServerSideEncryptionConfiguration: 
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: AES256
          BucketKeyEnabled: true
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced
      NotificationConfiguration:
         EventBridgeConfiguration:
            EventBridgeEnabled: false
      Tags:
        - Key: "Name"
          Value: "s3-bucket-encryption-sse-s3"

  BucketEncryptKms:
    Type: "AWS::S3::Bucket"
    DeletionPolicy: Delete
    Properties:
      #BucketName: !Ref BucketName
      AccessControl: "Private" # Private, PublicRead, PublicReadWrite, AuthenticatedRead, LogDeliveryWrite, BucketOwnerRead, BucketOwnerFullControl, or AwsExecRead.
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        IgnorePublicAcls: True
        BlockPublicPolicy: True
        RestrictPublicBuckets: True
      VersioningConfiguration:
         Status: Suspended
      BucketEncryption: # SSE-KMS
        ServerSideEncryptionConfiguration: 
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: 'aws:kms' #AES256 | aws:kms | aws:kms:dsse
            KMSMasterKeyID: !Sub "arn:aws:kms:${AWS::Region}:${AWS::AccountId}:alias/aws/s3"
          BucketKeyEnabled: true
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced
      NotificationConfiguration:
         EventBridgeConfiguration:
            EventBridgeEnabled: false
      Tags:
        - Key: "Name"
          Value: "s3-bucket-encryption-sse-kms"


Outputs:

  BucketEncryptS3Arn:
    Value: !GetAtt BucketEncryptS3.Arn
