AWSTemplateFormatVersion: "2010-09-09"
Description: S3 Template

Metadata:
  "AWS::CloudFormation::Interface":
    ParameterGroups:
      - Label: 
          default: "S3 Configuration"
        Parameters: 
          - BucketName

    ParameterLabels: 
      BucketName: 
        default: "Bucket Name"

Parameters:

  BucketName:
    Type: "String"
    Default: "my-bucket"
    Description: "Must contain only lowercase letters, numbers, periods (.), and dashes (-) "

Resources:

  Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Ref BucketName
      AccessControl: "Private" # Private, PublicRead, PublicReadWrite, AuthenticatedRead, LogDeliveryWrite, BucketOwnerRead, BucketOwnerFullControl, or AwsExecRead.
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True
      VersioningConfiguration:
         Status: Enabled
      BucketEncryption: 
        ServerSideEncryptionConfiguration: 
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: AES256
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced
      LifecycleConfiguration:
        Rules:
          - Id: !Sub "${BucketName}-lifecycle-rule-1"
            Status: Enabled
            Prefix: logs/
            TagFilters:
              - Key: key1
                Value: value1
              - Key: key2
                Value: value2
            ExpirationInDays: 365
            Transitions:
              - StorageClass: STANDARD_IA
                TransitionInDays: 90
              - StorageClass: GLACIER
                TransitionInDays: 120
          - Id: !Sub "${BucketName}-lifecycle-rule-2"
            Status: Enabled
            Prefix: uploads/
            AbortIncompleteMultipartUpload:
                DaysAfterInitiation: 3
            #ExpirationInDays: 365
            #NoncurrentVersionExpirationInDays: 145
            # ObjectSizeGreaterThan: 
            # ObjectSizeLessThan
            #Transitions:
              #- StorageClass: STANDARD_IA
                #TransitionInDays: 90
      Tags:
        - Key: "management"
          Value: "manual"



Outputs:
  BucketArn:
    Value: !GetAtt Bucket.Arn
