AWSTemplateFormatVersion: "2010-09-09"
Description: S3 Bucket Replication

Resources:

  BucketBackupDestination:
    Type: 'AWS::S3::Bucket'
    Properties:
      VersioningConfiguration:
        Status: Enabled
      AccessControl: "Private" # Private, PublicRead, PublicReadWrite, AuthenticatedRead, LogDeliveryWrite, BucketOwnerRead, BucketOwnerFullControl, or AwsExecRead.
      Tags:
        - Key: "management"
          Value: "manual"

  BucketBackupSource:
    Type: 'AWS::S3::Bucket'
    #DeletionPolicy: Retain
    Properties:
      ReplicationConfiguration:
        Role: !GetAtt BucketBackupRole.Arn
        Rules:
          - Destination:
              Bucket: !Sub "arn:aws:s3:::${BucketBackupDestination}"
              StorageClass: STANDARD
            Id: Backup
            Prefix: ''
            Status: Enabled
      VersioningConfiguration:
        Status: Enabled
      Tags:
        - Key: "management"
          Value: "manual"

  BucketBackupRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - 'sts:AssumeRole'
            Effect: Allow
            Principal:
              Service:
                - s3.amazonaws.com

  BucketBackupPolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - 's3:GetReplicationConfiguration'
              - 's3:ListBucket'
            Effect: Allow
            Resource:
              - !Sub "arn:aws:s3:::${BucketBackupSource}"
          - Action:
              - 's3:GetObjectVersion'
              - 's3:GetObjectVersionAcl'
            Effect: Allow
            Resource:
              - !Sub "arn:aws:s3:::${BucketBackupSource}/*"
          - Action:
              - 's3:ReplicateObject'
              - 's3:ReplicateDelete'
            Effect: Allow
            Resource:
              - !Sub "arn:aws:s3:::${BucketBackupDestination}/*"
      PolicyName: BucketBackupPolicy
      Roles:
        - !Ref BucketBackupRole

Outputs:

  BucketBackupSourceArn:
    Value: !GetAtt BucketBackupSource.Arn

  BucketBackupDestinationArn:
    Value: !GetAtt BucketBackupDestination.Arn