AWSTemplateFormatVersion: "2010-09-09"
Description: S3 Template

Metadata:
  "AWS::CloudFormation::Interface":
    ParameterGroups:
      - Label: 
          default: "S3 Configuration"
        Parameters: 
          - BucketName

    ParameterLabels: 
      BucketName: 
        default: "Bucket Name"
        MinLength: 5
        MaxLength: 64

Parameters:

  BucketName:
    Type: "String"
    Default: "my-bucket"
    Description: "Must contain only lowercase letters, numbers, periods (.), and dashes (-) "

Resources:

  Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Ref BucketName
      AccessControl: "Private" # Private, PublicRead, PublicReadWrite, AuthenticatedRead, LogDeliveryWrite, BucketOwnerRead, BucketOwnerFullControl, or AwsExecRead.
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        IgnorePublicAcls: True
        BlockPublicPolicy: True
        RestrictPublicBuckets: True
      VersioningConfiguration:
         Status: Suspended
      #BucketEncryption: # SSE-S3
      #  ServerSideEncryptionConfiguration: 
      #  - ServerSideEncryptionByDefault:
      #      SSEAlgorithm: AES256
      BucketEncryption: # SSE-KMS
        ServerSideEncryptionConfiguration: 
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: 'aws:kms' #AES256 | aws:kms | aws:kms:dsse
            KMSMasterKeyID: !Sub "arn:aws:kms:${AWS::Region}:${AWS::AccountId}:alias/aws/s3"
          BucketKeyEnabled: true
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced
      LifecycleConfiguration:
        Rules:
          - Id: !Sub "${BucketName}-lifecycle-rule"
            Status: Enabled
            Prefix: uploads/
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 2 # Specifies the number of days after which Amazon S3 stops an incomplete multipart upload.
            #ExpirationInDays: 365
            NoncurrentVersionExpiration:
              NewerNoncurrentVersions: 1 #0 newest noncurrent versions are retained
              NoncurrentDays: 3 #All other noncurrent versions are permanently deleted
      NotificationConfiguration:
         EventBridgeConfiguration:
            EventBridgeEnabled: true
      Tags:
        - Key: "management"
          Value: "manual"

  BucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket: !Ref Bucket
      PolicyDocument:
        Statement:
        - Action: "s3:GetObject"
          Effect: Allow
          Resource: !Sub "arn:aws:s3:::${Bucket}/*"
          Principal: '*'
          Condition:
            StringEquals: 
              aws:SourceAccount: ${AWS::AccountId}

Outputs:
  BucketArn:
    Value: !GetAtt Bucket.Arn
