AWSTemplateFormatVersion: "2010-09-09"
Description: S3 with Event Notification - Trigger SNS

Metadata:

  StackVersion: 1

  "AWS::CloudFormation::Interface":
    ParameterGroups:
      - Label: 
          default: "S3 Configuration"
        Parameters: 
          - BucketName

    ParameterLabels: 
      BucketName: 
        Default: "Bucket Name"
        MinLength: 5
        MaxLength: 64

Parameters:

  BucketName:
    Type: "String"
    Default: "s3-handler-sns-bucket"
    Description: "Must contain only lowercase letters, numbers, periods (.), and dashes (-) "

Resources:
        
  Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Ref BucketName
      AccessControl: "Private" # Private, PublicRead, PublicReadWrite, AuthenticatedRead, LogDeliveryWrite, BucketOwnerRead, BucketOwnerFullControl, or AwsExecRead.
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        IgnorePublicAcls: True
        BlockPublicPolicy: True
        RestrictPublicBuckets: True
      VersioningConfiguration:
         Status: Suspended
      NotificationConfiguration:
         TopicConfigurations:
            - Event: "s3:ObjectCreated:*"
              Topic: !Ref SNSTopic
              Filter:
                 S3Key:
                    Rules:
                       - Name: prefix
                         Value: notify
                       - Name: suffix
                         Value: txt
            - Event: "s3:ObjectRemoved:*"
              Topic: !Ref SNSTopic
            - Event: "s3:ObjectRestore:*"
              Topic: !Ref SNSTopic
      Tags:
        - Key: "management"
          Value: "manual"


  SNSTopic:
    Type: "AWS::SNS::Topic"
    Properties:
      #TopicName: !Sub "${Application}-${Environment}-${TopicName}"
      DisplayName: "My Topic"
      FifoTopic: false
      Tags:
        -
          Key: "Environment"
          Value: "prd"
        -
          Key: "Application"
          Value: "app"

  SNSTopicPolicy:
    Type: "AWS::SNS::TopicPolicy"
    Properties:
      Topics:
        - !Ref SNSTopic
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: TopicPolicy
            Effect: Allow
            Principal:
              Service: s3.amazonaws.com
            Action:
              - "sns:Publish"
            Resource: !Ref SNSTopic

Outputs:

  SNSTopicArn:
    Value: !Ref SNSTopic
