AWSTemplateFormatVersion: "2010-09-09"
Description: S3 with Event Notification - Trigger SNS

Metadata:

  StackVersion: 1

  "AWS::CloudFormation::Interface":
    ParameterGroups:
      - Label: 
          default: "S3 Configuration"
        Parameters: 
          - BucketName

    ParameterLabels: 
      BucketName: 
        Default: "Bucket Name"
        MinLength: 5
        MaxLength: 64

Parameters:

  BucketName:
    Type: "String"
    Default: "s3-handler-evtbridge-bucket"
    Description: "Must contain only lowercase letters, numbers, periods (.), and dashes (-) "

Resources:
        
  Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Ref BucketName
      AccessControl: "Private" # Private, PublicRead, PublicReadWrite, AuthenticatedRead, LogDeliveryWrite, BucketOwnerRead, BucketOwnerFullControl, or AwsExecRead.
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        IgnorePublicAcls: True
        BlockPublicPolicy: True
        RestrictPublicBuckets: True
      VersioningConfiguration:
         Status: Suspended
      NotificationConfiguration:
         EventBridgeConfiguration:
            EventBridgeEnabled: true
      Tags:
        - Key: "management"
          Value: "manual"

#TODO: Add Resources for EventRules and Subscription