
AWSTemplateFormatVersion: "2010-09-09"
Description: 
  S3 Server Access Logging

Metadata:
  "AWS::CloudFormation::Interface":
    ParameterGroups:
      - Label: 
          default: "S3 Configuration"
        Parameters: 
          - BucketName

    ParameterLabels: 
      BucketName: 
        default: "Bucket Name"

Parameters:
  BucketName:
    Type: "String"
    Default: "demo-bucket-server-log"
    Description: "Must contain only lowercase letters, numbers, periods (.), and dashes (-) "

Resources:
   
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      AccessControl: "Private" # Private, PublicRead, PublicReadWrite, AuthenticatedRead, LogDeliveryWrite, BucketOwnerRead, BucketOwnerFullControl, or AwsExecRead.
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        IgnorePublicAcls: True
        BlockPublicPolicy: True
        RestrictPublicBuckets: True
      VersioningConfiguration:
         Status: Suspended
      LoggingConfiguration:
        DestinationBucketName: !Ref BucketServerLog
        LogFilePrefix: server-logs
      Tags:
        - Key: "management"
          Value: "manual"

  BucketServerLog:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: LogDeliveryWrite
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerPreferred
      LifecycleConfiguration:
        Rules: 
        - Id: ExpireRule
          Status: Enabled
          ExpirationInDays: 7
          #NoncurrentVersionExpirationInDays: 7
      Tags:
        - Key: "usage"
          Value: !Sub "Server Log for ${BucketName}"

Outputs:

  BucketName:
    Value: !Ref Bucket
    Description: S3 bucket with server logging

  BucketServerLogName:
    Value: !Ref BucketServerLog
    Description: Server Log Bucket
