AWSTemplateFormatVersion: "2010-09-09"
Description: S3 Static Website - Redirects All HTTP Traffic

Metadata:
  "AWS::CloudFormation::Interface":
    ParameterGroups:
      - Label: 
          Default: "S3 Website Configuration"
        Parameters: 
          - BucketName
          - RedirectTargetDomain

    ParameterLabels: 
      BucketName: 
        Default: "Bucket Name"
        MinLength: 5
        MaxLength: 64
      RedirectTargetDomain: 
        Default: "Redirect Target Domain"
        MinLength: 3
        MaxLength: 64

Parameters:

  BucketName:
    Type: "String"
    Default: "s3-bucket-website"
    Description: "Name of the bucket"

  RedirectTargetDomain:
    Type: "String"
    Default: "www.google.com"
    Description: "Redirect target domain name"


Resources:

  Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Ref BucketName
      AccessControl: "PublicRead"
      VersioningConfiguration:
         Status: Suspended
      BucketEncryption: 
        ServerSideEncryptionConfiguration: 
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: AES256
      WebsiteConfiguration:
        RedirectAllRequestsTo:
          HostName: !Sub "${RedirectTargetDomain}"
          Protocol: http
      Tags:
        - Key: "management"
          Value: "manual"

  BucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket: !Ref Bucket
      PolicyDocument:
        Statement:
        - Action: "s3:GetObject"
          Effect: Allow
          Resource: !Sub "arn:aws:s3:::${Bucket}/*"
          Principal: '*'

Outputs:

  BucketArn:
    Value: !GetAtt Bucket.Arn

  BucketWebsiteUrl:
    Value: !GetAtt Bucket.WebsiteURL
