AWSTemplateFormatVersion: "2010-09-09"
Description: AppConfig - Basic

Metadata:

  AWS::CloudFormation::Interface:

    ParameterGroups:
      -
        Label:
          default: "Application Configuration"
        Parameters:
          - Application
          - Environment


Parameters:

  Application:
    Type: String
    Default: myapp
    Description: Application Name

  Environment:
    Type: String
    Default: dev
    Description: Environment

Resources:

  AppConfigApplication:
    Type: "AWS::AppConfig::Application"
    Properties:
      Name: "MyApplication"
      Description: !Sub "App Config Application ${Application}-${Environment}"
      Tags:
        - Key: "Application"
          Value: !Ref Application
        - Key: "Environment"
          Value: !Ref Environment

  AppConfigEnvironment:
    Type: "AWS::AppConfig::Environment"
    Properties:
      ApplicationId: !Ref AppConfigApplication
      Name: "Dev"
      Description: !Sub "App Config Envionment ${Application}-${Environment}"
      Tags:
        - Key: "Application"
          Value: !Ref Application
        - Key: "Environment"
          Value: !Ref Environment

  AppConfigConfigurationProfile:
    Type: "AWS::AppConfig::ConfigurationProfile"
    Properties:
      Name: "MyFeatureFlags"
      ApplicationId: !Ref AppConfigApplication
      LocationUri: hosted
      Type: AWS.AppConfig.FeatureFlags

  AppConfigDeploymentStrategy:
    Type: AWS::AppConfig::DeploymentStrategy
    Properties:
      Name: "MyDeploymentStrategy"
      Description: "Example deployment strategy"
      DeploymentDurationInMinutes: 3
      FinalBakeTimeInMinutes: 4
      GrowthFactor: 10
      GrowthType: LINEAR
      ReplicateTo: NONE
      Tags:
        - Key: Env
          Value: test


Outputs:

  AppConfigApplicationId:
    Value: !Ref AppConfigApplication
