AWSTemplateFormatVersion: "2010-09-09"
Description: Service Catalog - Product - Cloudformation

Metadata:

  StackVersion: 1

  AWS::CloudFormation::Interface:

    ParameterGroups:
      -
        Label:
          default: "Portfolio Configuration"
        Parameters:
          - ServiceCatalogPortfolioId
      -
        Label:
          default: "Product Configuration"
        Parameters:
          - ServiceCatalogProductVersion
          - CloudformationTemplateUrl

Parameters:

  CloudformationTemplateUrl:
    Type: "String"
    Default: "https://<bucket-id>/service-catalog/development-environment.template"
    Description: "Template Url"

  ServiceCatalogProductVersion:
    Type: "String"
    Default: "v1.0"
    Description: "Product Version"

  ServiceCatalogPortfolioId:
    Type: "String"
    Default: "<portfolio-id>"
    Description: "ServiceCatalogPortfolioId"
    
Resources:

  ServiceCatalogProduct:
    Type: "AWS::ServiceCatalog::CloudFormationProduct"
    Properties:
      AcceptLanguage: "jp"
      Description: "Cloud development environment configured for engineering staff. Runs AWS Linux."
      Distributor: "distributor"
      Name: "Linux Desktop"
      Owner: "IT"
      ProductType: "CLOUD_FORMATION_TEMPLATE" #CLOUD_FORMATION_TEMPLATE | MARKETPLACE | TERRAFORM_CLOUD | TERRAFORM_OPEN_SOURCE
      ProvisioningArtifactParameters:
        - Type: "CLOUD_FORMATION_TEMPLATE"
          Name: !Ref ServiceCatalogProductVersion
          Info: 
            LoadTemplateFromURL: !Sub "${CloudformationTemplateUrl}"
          Description: "Base Version"
          DisableTemplateValidation: false
      ReplaceProvisioningArtifacts: false
      SupportDescription: "Contact the IT department for issues deploying or connecting to this product."
      SupportEmail: "ITSupport@example.com"
      SupportUrl: "https://wiki.example.com/IT/support"
      Tags:
        - Key: "Name"
          Value: "dproduct"

  ServiceCatalogPortfolioProductAssociation:
    Type: "AWS::ServiceCatalog::PortfolioProductAssociation"
    Properties:
      AcceptLanguage: "jp"
      PortfolioId: !Ref ServiceCatalogPortfolioId
      ProductId: !Ref ServiceCatalogProduct
      #SourcePortfolioId: "Linux Desktop"

  ServiceCatalogPortfolioLaunchTemplateConstraint:
    Type: AWS::ServiceCatalog::LaunchTemplateConstraint
    Properties: 
      AcceptLanguage: "jp"
      Description: "Launch Template Constraints"
      PortfolioId: !Ref ServiceCatalogPortfolioId
      ProductId: !Ref ServiceCatalogProduct
      Rules: |
        {
          "Rule1": {
            "Assertions": [
              {
                "Assert" : {"Fn::Contains": [["t2.micro", "t2.small"], {"Ref": "InstanceType"}]},
                "AssertDescription": "Instance type should be t2.micro or t2.small"
              }
            ]
          }
        }

# Launch Constraint Role

  ServiceCatalogPortfolioLaunchRole:
    Type: AWS::IAM::Role
    DeletionPolicy: Delete
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service:
                - servicecatalog.amazonaws.com
      Policies:
        - PolicyName: LinuxDesktopPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - cloudformation:CreateStack
                  - cloudformation:DeleteStack
                  - cloudformation:DescribeStackEvents
                  - cloudformation:DescribeStacks
                  - cloudformation:GetTemplateSummary
                  - cloudformation:SetStackPolicy
                  - cloudformation:ValidateTemplate
                  - cloudformation:UpdateStack
                Resource: "*"
              - Effect: Allow
                Action:
                  - servicecatalog:*
                Resource: "*"
              - Effect: Allow
                Action:
                  - sns:*
                Resource: "*"
              - Effect: Allow
                Action:
                  - ec2:*
                Resource: "*"
              - Effect: Allow
                Action:
                  - s3:GetObject
                Resource: "*"
                Condition:
                  StringEquals:
                    s3:ExistingObjectTag/servicecatalog:provisioning: true

  ServiceCatalogPortfolioLaunchRoleConstraint:
    DependsOn:
      - ServiceCatalogProduct
      - ServiceCatalogPortfolioProductAssociation
      - ServiceCatalogPortfolioLaunchRole
    Type: AWS::ServiceCatalog::LaunchRoleConstraint
    Properties: 
      AcceptLanguage: "jp"
      Description: "Launch Role Constraint"
      PortfolioId: !Ref ServiceCatalogPortfolioId
      ProductId: !Ref ServiceCatalogProduct
      RoleArn: !GetAtt ServiceCatalogPortfolioLaunchRole.Arn

##

  ServiceCatalogPortfolioUserGroup:
    Type: AWS::IAM::Group
    Properties:
      #GroupName: iam-group-demo
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/AWSCodeCommitReadOnly
      Path: "/demo/"
      Policies:
      - PolicyName: inline-1
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - s3:*
            Resource: '*'

  ServiceCatalogPortfolioUserGroupPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: service-catalog-group-policy
      PolicyDocument:
        Statement:
        - Effect: Allow
          Action: cloudformation:*
          Resource: '*'
      Groups: 
        - !Ref ServiceCatalogPortfolioUserGroup

  ServiceCatalogPortfolioPrincipalAssociation:
    DependsOn:
      - ServiceCatalogProduct
      - ServiceCatalogPortfolioProductAssociation
      - ServiceCatalogPortfolioUserGroup
    Type: AWS::ServiceCatalog::PortfolioPrincipalAssociation
    Properties: 
      AcceptLanguage: "jp"
      PortfolioId: !Ref ServiceCatalogPortfolioId
      PrincipalARN: !GetAtt ServiceCatalogPortfolioUserGroup.Arn
      PrincipalType: IAM


Outputs:

  ServiceCatalogProductProductName:
    Value: !GetAtt ServiceCatalogProduct.ProductName

  ServiceCatalogProductProvisioningArtifactIds:
    Value: !GetAtt ServiceCatalogProduct.ProvisioningArtifactIds

  ServiceCatalogProductProvisioningArtifactNames:
    Value: !GetAtt ServiceCatalogProduct.ProvisioningArtifactNames
