AWSTemplateFormatVersion: "2010-09-09"
Description: CodeDeploy - Input S3 + Output EC2/Server

Parameters:

  RevisionBucketName:
    Description: Bucket containing revision
    Type: String
    Default: "my-bucket"

  RevisionObjectKey:
    Description: Name of the revision zip file
    Type: String
    Default: "code-codedeploy.zip"

Resources:

  CodeDeployServiceRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      #RoleName: !Sub "code-codedeploy-demo-role"
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: codedeploy.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSCodeDeployRole
        - !Ref CodeDeployServiceRolePolicy

  CodeDeployServiceRolePolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      Description: "CodeDeploy Role ManagedPolicy"
      #ManagedPolicyName: "code-deploy-demo-ec2-policy"
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - "ecs:DescribeServices"
            Effect: Allow
            Resource: "*"
      Tags:
        - Key: "Name"
          Value: "code-deploy-demo-ec2-policy"

  CodeDeployAplication:
    Type: AWS::CodeDeploy::Application
    Properties:
      #ApplicationName: "code-codedeploy-demo"
      ComputePlatform: Server #ComputePlatform: Server
      Tags:
        - Key: environment
          Value: stg

  CodeDeployGroup:
    Type: AWS::CodeDeploy::DeploymentGroup
    Properties:
      ApplicationName: !Ref CodeDeployAplication
      #DeploymentGroupName: "code-codedeploy-demo-deployment-group"
      DeploymentConfigName: CodeDeployDefault.OneAtATime
      Deployment: 
        Description: "Initial Deployment"
        IgnoreApplicationStopFailures: true 
        Revision: 
          RevisionType: S3 
          S3Location: 
            Bucket: 
              Ref: RevisionBucketName 
            Key: 
              Ref: RevisionObjectKey 
            BundleType: Zip 
            #ETag: 
              #Ref: ETag 
            #Version: 
              #Ref: Version  
      Ec2TagFilters:
        - Type: KEY_AND_VALUE
          Key: "Environment"
          Value: "Development"
        - Type: KEY_AND_VALUE
          Key: "Name"
          Value: "Webserver"
      ServiceRoleArn: !GetAtt [CodeDeployServiceRole, Arn]
      #AutoRollbackConfiguration:
      #  Enabled: true
      #  Events: # DEPLOYMENT_FAILURE, DEPLOYMENT_STOP_ON_ALARM, or DEPLOYMENT_STOP_ON_REQUEST
      #    - DEPLOYMENT_FAILURE 
      #    - DEPLOYMENT_STOP_ON_ALARM

Outputs:

  CodeDeployAplicationName:
    Value: !Ref CodeDeployAplication

  CodeDeployGroupName:
    Value: !Ref CodeDeployGroup