AWSTemplateFormatVersion: "2010-09-09"
Description: Lambda with Version and Alias

Resources:

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      #RoleName: "basic-lambda-role"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
              - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AWSXrayWriteOnlyAccess

  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      #FunctionName : "basic-lambda"
      Description: "Basic Lambda"
      Runtime: nodejs16.x
      Role: !GetAtt LambdaExecutionRole.Arn
      Handler: index.handler
      Environment:
        Variables:
          DatabaseName: lambdadbv32
          DatabaseUser: admin
      EphemeralStorage: # The size of the functionfs /tmp directory in MB
        Size: 512
      MemorySize: 128 #Maximum: 10240
      Timeout: 3 #The default is 3 seconds. The maximum allowed value is 900 seconds.
      #ReservedConcurrentExecutions: 0
      Code:
        ZipFile: |
          exports.handler = async (event, context, callback) => {
              let envDatabaseName = process.env.DatabaseName;
              console.log(`DatabaseName: ${envDatabaseName}`);
              const response = {
                  statusCode: 200,
                  body: JSON.stringify('Version-3.2'),
              };
              return response;
          };
      TracingConfig:
        Mode: "Active"
      Tags:
        - Key: "name"
          Value: "lambda-basic"

  LambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${LambdaFunction}"
      RetentionInDays: 1

  LambdaVersion1:
    Type: AWS::Lambda::Version
    Properties:
      FunctionName: !Ref LambdaFunction
      Description: v1
      #DeletionPolicy: RETAIN

  LambdaVersion2:
    Type: AWS::Lambda::Version
    Properties:
      FunctionName: !Ref LambdaFunction
      Description: v2

  LambdaVersion3:
    Type: AWS::Lambda::Version
    Properties:
      FunctionName: !Ref LambdaFunction
      Description: v3

  LambdaAliasDev:
    Type: AWS::Lambda::Alias
    Properties:
      FunctionName: !Ref LambdaFunction
      FunctionVersion: !GetAtt LambdaVersion3.Version
      Name: dev
      Description: Dev

  LambdaAliasStg:
    Type: AWS::Lambda::Alias
    Properties:
      FunctionName: !Ref LambdaFunction
      FunctionVersion: !GetAtt LambdaVersion2.Version
      Name: stg
      Description: Staging
      RoutingConfig:
        AdditionalVersionWeights:
          - FunctionVersion: !GetAtt LambdaVersion3.Version
            FunctionWeight: 0.1

  LambdaAliasPrd:
    Type: AWS::Lambda::Alias
    Properties:
      FunctionName: !Ref LambdaFunction
      FunctionVersion: !GetAtt LambdaVersion1.Version
      Name: prd
      Description: Production
      RoutingConfig:
        AdditionalVersionWeights:
          - FunctionVersion: !GetAtt LambdaVersion2.Version
            FunctionWeight: 0.6

Outputs:

  LambdaFunctionArn:
    Value: !GetAtt LambdaFunction.Arn

  LambdaExecutionRoleArn:
    Value: !GetAtt LambdaExecutionRole.Arn

  LambdaAliasDevArn:
    Value: !Ref LambdaAliasDev

  LambdaAliasStgArn:
    Value: !Ref LambdaAliasStg

  LambdaAliasPrdArn:
    Value: !Ref LambdaAliasPrd

