AWSTemplateFormatVersion: 2010-09-09
Description: IAM Role

Resources:

  RootRole: 
    Type: AWS::IAM::Role
    Properties:
      #RoleName:
      Description: Developer Role
      #Path: "/demo/" # must begin and end with / and contain only alphanumeric characters
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Principal: 
              Service: 
                - "ec2.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
        - arn:aws:iam::aws:policy/AmazonEKSServicePolicy
      Policies:
        - PolicyName: access-secrets
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - 'ssm:GetParameters'
                Resource: '*'
              - Effect: Allow
                Action:
                  - 'secretsmanager:GetSecretValue' 
                Resource: '*' #arn:aws:secretsmanager:<region>:<aws_account_id>:secret:<secret_name>
              - Effect: Allow
                Action:
                  - 'kms:Decrypt'
                Resource: '*' #arn:aws:kms:<region>:<aws_account_id>:key/<key_id>
      Tags:
        - Key: "Name"
          Value: "developer-role"

  RootRolePolicies: 
    Type: AWS::IAM::Policy
    Properties: 
      PolicyName: "root"
      PolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - Effect: "Allow"
            Action: "s3:*"
            Resource: "*"
      Roles: 
        - Ref: "RootRole"
 
Outputs:

  RootRoleArn:
    Value: !GetAtt RootRole.Arn
