
AWSTemplateFormatVersion: "2010-09-09"
Description: EventBridge Rule (CodeCommit) - Transform Output - Send to SNS

Metadata:

  StackVersion: 1

Resources:

  EventBridgeCodeCommitSnsTopic:
    Type: "AWS::SNS::Topic"
    Properties:
      TopicName: !Sub "eventbridge-codecommit-sns-topic"
      DisplayName: "CodeCommit - Event"
      Tags:
        - Key: "management"
          Value: "manual"

  EventBridgeCodeCommitSnsTopicOnPush:
    Type: "AWS::SNS::Topic"
    Properties:
      TopicName: !Sub "eventbridge-codecommit-sns-topic-on-push"
      DisplayName: "CodeCommit - OnPush"
      #DisplayName: "EventBridgeCodeCommitSnsTopicOnPush"
      #KmsMasterKeyId: alias/aws/sns
      #FifoTopic: false
      Tags:
        - Key: "management"
          Value: "manual"

  EventBridgeCodeCommitSnsTopicOnPrMerge:
    Type: "AWS::SNS::Topic"
    Properties:
      TopicName: !Sub "eventbridge-codecommit-sns-topic-on-prmerge"
      DisplayName: "CodeCommit - OnPullRequestMerge"
      #DisplayName: "EventBridgeCodeCommitSnsTopicOnPush"
      #KmsMasterKeyId: alias/aws/sns
      #FifoTopic: false
      Tags:
        - Key: "management"
          Value: "manual"

  EventBridgeRuleCodeCommitOnPush: 
    Type: AWS::Events::Rule
    Properties: 
      Name: eventbridge-rule-codecommit-on-push-sns
      Description: "CodeCommit OnPush Trigger"
      #EventBusName: default
      EventPattern:
        source:
          - aws.codecommit
        detail-type:
          - "CodeCommit Repository State Change"
        detail:
          event:
            - referenceCreated
            - referenceUpdated
          referenceType:
            - branch
          referenceName:
            - main
            - staging
        resources:
          - !Sub "arn:aws:codecommit:${AWS::Region}:${AWS::AccountId}:repository"
      State: "ENABLED"
      Targets:
        -
          Arn: !Ref EventBridgeCodeCommitSnsTopicOnPush
          Id: "TargetSnsTopic"
          InputTransformer: 
            InputPathsMap:
              "CallerUserArn" : "$.detail.callerUserArn"
              "ReferenceName" : "$.detail.referenceName"
              "RepositoryName" : "$.detail.repositoryName"
              "CommitId" : "$.detail.commitId"
            InputTemplate: |
              {
                "Message": "Code pushed by <CallerUserArn> on <RepositoryName>",
                "Repository": "<RepositoryName>",
                "Branch" : "<ReferenceName>",
                "User" : "<CallerUserArn>",
                "Commit": "<CommitId>"
              }

  EventBridgeRuleCodeCommitOnPrComment: 
    Type: AWS::Events::Rule
    Properties: 
      Name: eventbridge-rule-codecommit-on-prcomment-sns
      Description: "CodeCommit Notification Trigger on Pull Request Comment"
      #EventBusName: default
      EventPattern:
        source:
          - aws.codecommit
        detail-type:
          - "CodeCommit Comment on Pull Request"
        detail:
          event:
            - commentOnPullRequestCreated
            - commentOnPullRequestUpdated
        resources:
          - !Sub "arn:aws:codecommit:${AWS::Region}:${AWS::AccountId}:repository"
      State: "ENABLED"
      Targets:
        - 
          Arn: !Ref EventBridgeCodeCommitSnsTopicOnPrMerge
          Id: "TargetSnsTopic"
          InputTransformer:
            InputPathsMap:
              "CallerUserArn" : "$.detail.callerUserArn"
              "RepositoryName" : "$.detail.repositoryName"
              "PullRequestId" : "$.detail.pullRequestId"
              "CommentId" : "$.detail.commentId"
              "NotificationBody" : "$.detail.notificationBody"
            InputTemplate: |
              {
                "Message": "PR Comment by <CallerUserArn>",
                "Repository" : "<RepositoryName>",
                "PullRequest" : "<PullRequestId>",
                "Comment" : "<CommentId>",
                "User" : "<CallerUserArn>",
                "Details" : "<NotificationBody>"
              }

  EventBridgeRuleCodeCommitOnPrCreate: 
    Type: AWS::Events::Rule
    Properties: 
      Name: eventbridge-rule-codecommit-on-prcreate-sns
      Description: "CodeCommit Notification Trigger on Pull Request Create"
      #EventBusName: default
      EventPattern:
        source:
          - aws.codecommit
        detail-type:
          - "CodeCommit Pull Request State Change"
        detail:
          event:
            - pullRequestCreated
          destinationReference:
            - refs/heads/main
          isMerged:
            - "False"
          pullRequestStatus:
            - "Open"
        resources:
          - !Sub "arn:aws:codecommit:${AWS::Region}:${AWS::AccountId}:repository"
      State: "ENABLED"
      Targets:
        - 
          Arn: !Ref EventBridgeCodeCommitSnsTopicOnPrMerge
          Id: "TargetSnsTopic"
          InputTransformer:
            InputPathsMap:
              "Author" : "$.detail.author"
              "CallerUserArn" : "$.detail.callerUserArn"
              "Title" : "$.detail.title"
              "Description" : "$.detail.description"
              "RepositoryName" : "$.detail.repositoryNames[0]"
              "DestinationReference" : "$.detail.destinationReference"
              "NotificationBody" : "$.detail.notificationBody"
              "PullRequestId" : "$.detail.pullRequestId"
            InputTemplate: |
              {
                "Message": "PR Create by <CallerUserArn> on <DestinationReference>",
                "Repository" : "<RepositoryName>",
                "DestinationBranch" : "<DestinationReference>",
                "Author" : "<Author>",
                "User" : "<CallerUserArn>",
                "Title" : "<Title>",
                "Description" : "<Description>",
                "PullRequest" : "<PullRequestId>",
                "Details" : "<NotificationBody>"
              }

  EventBridgeRuleCodeCommitOnPrModify: 
    Type: AWS::Events::Rule
    Properties: 
      Name: eventbridge-rule-codecommit-on-prmodify-sns
      Description: "CodeCommit Notification Trigger on Pull Request Modify"
      #EventBusName: default
      EventPattern:
        source:
          - aws.codecommit
        detail-type:
          - "CodeCommit Pull Request State Change"
        detail:
          event:
            - pullRequestStatusChanged
            - pullRequestSourceBranchUpdated
          destinationReference:
            - refs/heads/main
          isMerged: 
            - "False"
        resources:
          - !Sub "arn:aws:codecommit:${AWS::Region}:${AWS::AccountId}:repository"
      State: "ENABLED"
      Targets:
        - 
          Arn: !Ref EventBridgeCodeCommitSnsTopicOnPrMerge
          Id: "TargetSnsTopic"
          InputTransformer:
            InputPathsMap:
              "Author" : "$.detail.author"
              "CallerUserArn" : "$.detail.callerUserArn"
              "Title" : "$.detail.title"
              "Description" : "$.detail.description"
              "RepositoryName" : "$.detail.repositoryNames[0]"
              "SourceReference" : "$.detail.sourceReference"
              "DestinationReference" : "$.detail.destinationReference"
              "NotificationBody" : "$.detail.notificationBody"
              "PullRequestId" : "$.detail.pullRequestId"
            InputTemplate: |
              {
                "Message": "PR Modify by <CallerUserArn> on <DestinationReference>",
                "Repository" : "<RepositoryName>",
                "SourceBranch" : "<SourceReference>",
                "DestinationBranch" : "<DestinationReference>",
                "Author" : "<Author>",
                "User" : "<CallerUserArn>",
                "Title" : "<Title>",
                "Description" : "<Description>",
                "PullRequest" : "<PullRequestId>",
                "Details" : "<NotificationBody>"
              }


  EventBridgeRuleCodeCommitOnPrMerge: 
    Type: AWS::Events::Rule
    Properties: 
      Name: eventbridge-rule-codecommit-on-prmerge-sns
      Description: "CodeCommit Notification Trigger on Pull Request Merge"
      #EventBusName: default
      EventPattern:
        source:
          - aws.codecommit
        detail-type:
          - "CodeCommit Pull Request State Change"
        detail:
          event:
            - pullRequestMergeStatusUpdated
          destinationReference:
            - refs/heads/main
          isMerged: 
            - "True"
          pullRequestStatus:
            - "Closed"
        resources:
          - !Sub "arn:aws:codecommit:${AWS::Region}:${AWS::AccountId}:repository"
      State: "ENABLED"
      Targets:
        - 
          Arn: !Ref EventBridgeCodeCommitSnsTopicOnPrMerge
          Id: "TargetSnsTopic"
          InputTransformer:
            InputPathsMap:
              "Author" : "$.detail.author"
              "CallerUserArn" : "$.detail.callerUserArn"
              "Title" : "$.detail.title"
              "Description" : "$.detail.description"
              "RepositoryName" : "$.detail.repositoryNames[0]"
              "DestinationReference" : "$.detail.destinationReference"
              "NotificationBody" : "$.detail.notificationBody"
              "PullRequestId" : "$.detail.pullRequestId"
            InputTemplate: |
              {
                "Message": "PR Merge by <CallerUserArn> on <DestinationReference>",
                "Repository" : "<RepositoryName>",
                "DestinationBranch" : "<DestinationReference>",
                "Author" : "<Author>",
                "User" : "<CallerUserArn>",
                "Title" : "<Title>",
                "Description" : "<Description>",
                "PullRequest" : "<PullRequestId>",
                "Details" : "<NotificationBody>"
              }

  InvokeSnsTopicPermissionCodeCommit:
    Type: AWS::SNS::TopicPolicy
    Properties:
      Topics:
        - !Ref EventBridgeCodeCommitSnsTopic
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: 'sns:Publish'
            #Resource: '*'
            Resource: !Ref EventBridgeCodeCommitSnsTopic

  InvokeSnsTopicPermissionCodeCommitOnPush:
    Type: AWS::SNS::TopicPolicy
    Properties:
      Topics:
        - !Ref EventBridgeCodeCommitSnsTopicOnPush
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: 'sns:Publish'
            #Resource: '*'
            Resource: !Ref EventBridgeCodeCommitSnsTopicOnPush

  InvokeSnsTopicPermissionCodeCommitOnPrMerge:
    Type: AWS::SNS::TopicPolicy
    Properties:
      Topics:
        - !Ref EventBridgeCodeCommitSnsTopicOnPrMerge
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: 'sns:Publish'
            #Resource: '*'
            Resource: !Ref EventBridgeCodeCommitSnsTopicOnPrMerge

Outputs:

  EventBridgeCodeCommitSnsTopicArn:
    Value: !Ref EventBridgeCodeCommitSnsTopic
  EventBridgeCodeCommitSnsTopicOnPushArn:
    Value: !Ref EventBridgeCodeCommitSnsTopicOnPush
  EventBridgeCodeCommitSnsTopicOnPrMergeArn:
    Value: !Ref EventBridgeCodeCommitSnsTopicOnPrMerge

  EventBridgeRuleCodeCommitOnPushArn:
    Value: !GetAtt EventBridgeRuleCodeCommitOnPush.Arn
  EventBridgeRuleCodeCommitOnPrCreateArn:
    Value: !GetAtt EventBridgeRuleCodeCommitOnPrCreate.Arn
  EventBridgeRuleCodeCommitOnPrMergeArn:
    Value: !GetAtt EventBridgeRuleCodeCommitOnPrMerge.Arn
