AWSTemplateFormatVersion: "2010-09-09"
Description: EventBridge - EventBus

Parameters:

  EventBusName: 
    Description: Event Bus Name
    Type: String
    Default: custom-event-bus

Resources:

  EventBridgeEventBus:
    Type: AWS::Events::EventBus
    Properties: 
      Name: !Ref EventBusName
      Tags:
        - Key: "Name"
          Value: "custom-event-bus"

Outputs:

  EventBridgeEventBusArn:
    Value: !GetAtt EventBridgeEventBus.Arn
