AWSTemplateFormatVersion: "2010-09-09"
Description: EventBridge Rule (S3) - Call SNS

# Source Bucket must have event bridge notification enabled
#  Bucket:
#    Type: "AWS::S3::Bucket"
#    Properties:
#      ...
#      NotificationConfiguration:
#         EventBridgeConfiguration:
#            EventBridgeEnabled: true

# Target SNS Topic must define AWS::SNS::TopicPolicy to permit events.amazonaws.com to publish message


Metadata:

  StackVersion: 1

  "AWS::CloudFormation::Interface":
    ParameterGroups:
      - Label: 
          default: "Source Configuration"
        Parameters: 
          - BucketName
      - Label: 
          default: "Target Configuration"
        Parameters: 
          - SnsTopicArn
    ParameterLabels: 
      BucketArn: 
        Default: "BucketName"
        MinLength: 5
        MaxLength: 124
        

Parameters:

  BucketName:
    Type: "String"
    Default: "bucket-name"
    Description: "Name of the Source Bucket"

  SnsTopicArn:
    Type: "String"
    Default: "arn:aws:sns:us-east-1:9000000000:topic"
    Description: "Arn of the Target Sns Topic"
        
Resources:

  EvenBridgeRole:
    Type: AWS::IAM::Role
    Properties:
      #RoleName: !Sub "event-bridge-role"
      Description: !Sub "Event Bridge Role - S3 Call SNS"
      Path: /
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action:
              - 'sts:AssumeRole'
            Effect: Allow
            Principal:
              Service: events.amazonaws.com
      ManagedPolicyArns:
        - !Ref EvenBridgeRolePolicy
        #- arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryPowerUser
      Tags:
        - Key: 'environment'
          Value: common
        - Key: "name"
          Value: "event-bridge-role-s3-call-sns"

  EvenBridgeRolePolicy:
    Type: "AWS::IAM::ManagedPolicy"
    Properties:
      Description: "Event Bridge ManagedPolicy - S3 Call SNS"
      #ManagedPolicyName: "event-bridge-policy"
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - 'logs:CreateLogGroup'
              - 'logs:CreateLogStream'
              - 'logs:PutLogEvents'
            Effect: Allow
            Resource: '*'     

  SnsTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      Topics:
        - !Ref SnsTopicArn
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - "events.amazonaws.com"
            Action: 
              - "sns:Publish"
            Resource: !Ref SnsTopicArn

  EventBridgeRule: 
    Type: AWS::Events::Rule
    Properties: 
      #Name: eventbridge-rule-s3-call-sns
      Description: "Event Bridge Rule S3 Call SNS"
      EventBusName: default
      EventPattern:
        source:
          - aws.s3
        detail-type:
          - "Object Created"
        detail:
          bucket:
            name: 
              - !Ref BucketName
      State: "ENABLED"
      RoleArn: !GetAtt EvenBridgeRole.Arn
      Targets:
        - 
          Arn: !Ref SnsTopicArn
          Id: "TargetSNS"
          #RoleArn : Not Supported. Use Resource Policy AWS::SNS::TopicPolicy
          RetryPolicy:
            MaximumEventAgeInSeconds: 3600 #86400
            MaximumRetryAttempts: 1 #185
          #DeadLetterConfig:
          #   Arn: xx


Outputs:

  EventBridgeRuleName:
    Value: !Ref EventBridgeRule
