AWSTemplateFormatVersion: "2010-09-09"
Description: EventBridge Rule (S3) - Call StepFunctions

# Bucket must have event bridge notification enabled
#  Bucket:
#    Type: "AWS::S3::Bucket"
#    Properties:
#      ...
#      NotificationConfiguration:
#         EventBridgeConfiguration:
#            EventBridgeEnabled: true

Metadata:

  StackVersion: 1

  "AWS::CloudFormation::Interface":
    ParameterGroups:
      -
        Label:
          default: "Application Configuration"
        Parameters:
          - Application
          - Environment
      - Label: 
          default: "Source Configuration"
        Parameters: 
          - BucketName
      - Label: 
          default: "Target Configuration"
        Parameters: 
          - StepFunctionArn
    ParameterLabels: 
      BucketArn: 
        Default: "BucketName"
        MinLength: 5
        MaxLength: 124
        

Parameters:

  Application:
    Type: String
    Default: myapp
    Description: Application Name

  Environment:
    Type: String
    Default: dev
    Description: Environment

  BucketName:
    Type: "String"
    Default: "bucket-name"
    Description: "Name of the Source Bucket"

  StepFunctionArn:
    Type: "String"
    Default: "arn:aws:states:us-east-1:937921569138:stateMachine:StateMachine-AzPfXPRklJX7"
    Description: "Arn of the Target Job Definition"

Resources:

  EvenBridgeRole:
    Type: AWS::IAM::Role
    Properties:
      #RoleName: !Sub "event-bridge-role"
      Description: !Sub "Event Bridge Role - S3 Call Step Function"
      Path: /
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action:
              - 'sts:AssumeRole'
            Effect: Allow
            Principal:
              Service: events.amazonaws.com
      ManagedPolicyArns:
        - !Ref EvenBridgeRolePolicy
        #- arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryPowerUser
      Tags:
        - Key: 'environment'
          Value: common
        - Key: "name"
          Value: "event-bridge-role-s3-call-stepfunction"

  EvenBridgeRolePolicy:
    Type: "AWS::IAM::ManagedPolicy"
    Properties:
      Description: "Event Bridge ManagedPolicy - S3 Call Step Function"
      #ManagedPolicyName: "event-bridge-policy"
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - 'states:StartExecution'
            Effect: Allow
            Resource: '*'
          - Action:
              - 'logs:CreateLogGroup'
              - 'logs:CreateLogStream'
              - 'logs:PutLogEvents'
            Effect: Allow
            Resource: '*'     
              
  EventBridgeRule: 
    Type: AWS::Events::Rule
    Properties: 
      #Name: eventbridge-rule-s3-call-batch
      Description: "Event Bridge Rule S3 Call Batch"
      EventBusName: default
      EventPattern:
        source:
          - aws.s3
        detail-type:
          - "Object Created"
        detail:
          bucket:
            name: 
              - !Ref BucketName
      State: "ENABLED"
      #"RoleArn" : String, # (ARN) of the role that is used for target invocation.
      Targets:
        - 
          Arn: !Ref StepFunctionArn
          Id: "TargetStepFunction"
          RoleArn : !GetAtt EvenBridgeRole.Arn
          RetryPolicy:
            MaximumEventAgeInSeconds: 3600 #86400
            MaximumRetryAttempts: 1 #185
            
Outputs:

  EventBridgeRuleName:
    Value: !Ref EventBridgeRule
