AWSTemplateFormatVersion: "2010-09-09"
Description: "Cognito User Pool with Domain Hosted UI"

Parameters:

  CognitoDomainName:
    Type: String
    MinLength: 3
    MaxLength: 63
    AllowedPattern: ^[a-z0-9](?:[a-z0-9\-]{0,61}[a-z0-9])?$
    Description: Cognito Domain Name. xxx.auth.us-west-2.amazoncognito.com
    Default: "r53lb277domain"

  CognitoClientCallbackUrlList:
    Type: CommaDelimitedList
    Description: Callback
    Default: "https://r53lb277.xxx.com/oauth2/idpresponse,https://r53lb277.xxx.com"

  CognitoClientRedirectUrl:
    Type: String
    Description: Redirect URL
    Default: "https://r53lb277.xxx.com" #http://localhost:3000"

  CognitoClientLogoutUrlList:
    Type: CommaDelimitedList
    Description: Callback
    Default: "https://r53lb277.xxx.com/logout" #http://localhost:3000"

Resources:

  UserPool:
    Type: "AWS::Cognito::UserPool"
    Properties:
      #UserPoolName: "cognito-userpool-domain"
      AdminCreateUserConfig:
          AllowAdminCreateUserOnly: false
          #UnusedAccountValidityDays: 7
          InviteMessageTemplate:
            EmailMessage: "Custom - Your username is {username} and temporary password is {####}."
            EmailSubject: "Custom - Your temporary password."
            #SMSMessage: String
      #UsernameAttributes:
      #  - email
      AliasAttributes:
        - email
      AutoVerifiedAttributes:
        - email
      MfaConfiguration: "OFF"
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: false
          RequireUppercase: true
          TemporaryPasswordValidityDays: 7
      Schema:
        - AttributeDataType: "String"
          DeveloperOnlyAttribute: false
          Mutable: true
          Name: "email"
          StringAttributeConstraints:
            MaxLength: "128"
            MinLength: "0"
          Required: true
        - AttributeDataType: "String"
          DeveloperOnlyAttribute: false
          Mutable: true
          Name: "name"
          StringAttributeConstraints:
            MaxLength: "256"
            MinLength: "0"
          Required: false
        - AttributeDataType: "String"
          DeveloperOnlyAttribute: false
          Mutable: true
          Name: "custom-attributes"
          StringAttributeConstraints:
            MaxLength: "256"
            MinLength: "0"
          Required: false
      UserPoolTags:
        Environment: "cmn"
        Name: !Sub "${CognitoDomainName}-userpool-1"

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      #ClientName: 
      UserPoolId: !Ref UserPool
      GenerateSecret: true
      AllowedOAuthFlowsUserPoolClient: true
      CallbackURLs: !Ref CognitoClientCallbackUrlList
      AllowedOAuthFlows:
        - code
        - implicit
      AllowedOAuthScopes:
        - phone
        - email
        - openid
        - profile
      SupportedIdentityProviders:
        - COGNITO
      DefaultRedirectURI: !Ref CognitoClientRedirectUrl
      ExplicitAuthFlows:
        - "ALLOW_REFRESH_TOKEN_AUTH"
      LogoutURLs: !Ref CognitoClientLogoutUrlList
      PreventUserExistenceErrors: ENABLED
      WriteAttributes:
        - "email"
      #AccessTokenValidity: 3
        
  UserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: !Ref CognitoDomainName
      UserPoolId: !Ref UserPool
      #CustomDomainConfig:
        #CertificateArn: !Ref CertificateArn

Outputs:

  UserPoolArn:
    Description: "The name of the user pool"
    Value: !GetAtt UserPool.Arn

  UserPoolProviderName:
    Description: "The ProviderName of the user pool"
    Value: !GetAtt UserPool.ProviderName

  UserPoolProviderURL:
    Description: "The ProviderURL of the user pool"
    Value: !GetAtt UserPool.ProviderURL
    
  UserPoolName:
    Description: "The name of the user pool"
    Value: !Ref UserPool

  UserPoolDomainName:
    Description: "name of the user pool domain"
    Value: !Ref UserPoolDomain
    
  UserPoolClientID:
    Value: !Ref UserPoolClient
    Description: The app client

  HostedAuthUrl:
    Value: !Sub https://${CognitoDomainName}.auth.${AWS::Region}.amazoncognito.com/login?client_id=${UserPoolClient}&response_type=code&scope=email+openid+phone+profile&redirect_uri=${CognitoClientRedirectUrl}
    Description: The hosted UI URL
