AWSTemplateFormatVersion: "2010-09-09"
Description: SSM - Document - Run Command

Resources:

  CommandDocument: 
    Type: AWS::SSM::Document
    Properties:
      #Name: 'CFN_2.2_command_example' # Cannot start with aws amazon amzn
      DocumentType: Command # ApplicationConfigurationSchema | Automation | Automation.ChangeTemplate | Command | DeploymentStrategy | Package | Policy | Session
      DocumentFormat: YAML # JSON | TEXT | YAML
      #VersionName: "Release12.1"
      TargetType: "/AWS::EC2::Instance"
      Content:
        schemaVersion: '2.2'
        description: 'Run a script on Linux instances.'
        parameters:
          commands:
            type: String
            description: "(Required) The commands to run or the path to an existing script on the instance."
            default: 'echo Hello World'
        mainSteps:
        - action: aws:runShellScript
          name: runCommands
          precondition:
            StringEquals:
            - platformType
            - Linux          
          inputs:
            timeoutSeconds: '60'
            runCommand:
            - "{{ commands }}"
        - action: aws:runShellScript
          name: configureApache
          inputs:
            runCommand:
            - 'sudo yum update -y'
            - 'sudo yum install -y httpd'
            - 'sudo systemctl start httpd'
            - 'sudo systemctl enable httpd'
            - 'echo "Hi from $(hostname -f)" > /var/www/html/index.html'
      Tags:
        - Key: "keyname1"
          Value: "value1"
        - Key: "keyname2"
          Value: "value2"
      
Outputs:

  CommandDocumentName:
    Value: !Ref CommandDocument