AWSTemplateFormatVersion: "2010-09-09"
Description: Systems Manager - Parameter Store Reference

Parameters:

  Application:
    Type: String
    Default: xxx
    Description: Application Name

  VpcId: 
    Type: AWS::EC2::VPC::Id

  ParameterVpcId: 
    Type: AWS::SSM::Parameter::Value<AWS::EC2::VPC::Id>
    Default: /xxx/dev/vpc/id

  ParameterSubnetId: 
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Subnet::Id>
    Default: /xxx/dev/vpc/subnet/private-subnet-1/id

  ParameterDatabaseEndpoint:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /xxx/database/endpoint

Resources:

  Ec2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VpcId
      GroupDescription: !Sub "VpcId=${ParameterVpcId} SubnetId=${ParameterSubnetId} DB=${ParameterDatabaseEndpoint}"
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: "0.0.0.0/0"

Outputs:

  ParameterVpcId:
    Value: !Ref ParameterVpcId

  ResolveVpcId: # Resolve the latest version
    Value: "{{resolve:ssm:/xxx/dev/vpc/id}}"

  ResolveVpcIdVersions1: # Resolve version 1
    Value: "{{resolve:ssm:/xxx/dev/vpc/id:1}}"

# SSM Secure reference is not supported in: Outputs
#  ResolveDatabasePassword:
#    Value: "{{resolve:ssm-secure:/xxx/database/password}}"

#  ResolveDatabasePasswordVersion1:
#    Value: "{{resolve:ssm-secure:/xxx/database/password:1}}"
