AWSTemplateFormatVersion: "2010-09-09"
Description: Secrets Manager

Resources:

  SecretsManagerSecret:
    Type: AWS::SecretsManager::Secret'
    Properties:
      #Name: secret-api-key
      Description: Secrets Manager Secret
      #KmsKeyId: aws/secretsmanager
      GenerateSecretString:
        SecretStringTemplate: '{"username": "test-user"}'
        GenerateStringKey: "password"
        PasswordLength: 32
        ExcludeCharacters: '"@/\'
        IncludeSpace: false
      Tags:
      - Key: Name
        Value: "secret-api-key"

Outputs:

  SecretsManagerSecretArn:
    Value: !Ref SecretsManagerSecret
